// itemDat.length  -  колл-во всех солдат
// sitemDat[0].length  -  колл-во элементов у солдат
// 0 - имя рус, 1 - имя англ., 2 - тип вещи, 3 - ОЗ, 4 - атк, 5 - инт, 6 - защ, 7 - мзащ, 8 - навык, 9 - описание рус, 10 - описание англ.
var itemDat = [
    [
        "NAME (RUS)",
        "NAME (ENG)",
        "TYPE (weapon, body, hat, accessoir)",
        "HP",
        "ATK",
        "INT",
        "DEF",
        "MDEF",
        "SKILL",
        "DESCRIPTION (RUS)",
        "DESCRIPTION (ENG)"
    ],
    [
        "Амулет короля",
        "King Amulet",
        "accessoir",
        "509",
        "",
        "",
        "48",
        "",
        "",
        "Если в радиусе 2 клеток есть союзник, ЗАЩ и МЗАЩ в бою увеличиваются на 10%.",
        "When a friendly unit is within 2 blocks, in battle, DEF and MDEF is increase by 10%."
    ],
    [
        "Ангел бедствия",
        "Apostle of doom",
        "accessoir",
        "",
        "75",
        "75",
        "",
        "",
        "",
        "АТК и ИНТ +5%. При активной атаке и вступлении в бой есть 100% шанс снизить случайный атрибут врага на 30% (кроме ОЗ). Длится 1 раунд. Если это несмешанная армия, этот эффект нельзя снять.",
        "ATK and INT +5%. When actively attacking and entering battle, there is a 100% chance to reduce a random enemy attribute by 30% (except HP). Lasts 1 round. If it's an unmixed army, this effect cannot be removed."
    ],
    [
        "Апексовые сапоги",
        "Apex Boots",
        "accessoir",
        "",
        "75",
        "",
        "",
        "43",
        "",
        "АТК +5%. Мобильность +1.",
        "ATK +5%. Mobility +1."
    ],
    [
        "Божественные сапоги",
        "Divine Boots",
        "accessoir",
        "509",
        "",
        "",
        "48",
        "",
        "",
        "ЗАЩ +8%. Мобильность +1",
        "DEF +8%. Mobility +1."
    ],
    [
        "Ботинки духа",
        "Spirit Boots",
        "accessoir",
        "509",
        "",
        "",
        "48",
        "",
        "",
        "ЗАЩ +8%. После атаки можно передвинуться ещё на 2 клетки.",
        "DEF +8%. Can move 2 blocks after attacking a target."
    ],
    [
        "Браслет одинокой звезды",
        "Lone Star Armlet",
        "accessoir",
        "509",
        "75",
        "",
        "",
        "",
        "",
        "Если в радиусе 2 клеток нет союзников, АТК и ЗАЩ во время боя повышаются на 10%.",
        "When no friendly units within 2 blocks, ATK and DEF increase by 10% during combat."
    ],
    [
        "Бриллиант измерения",
        "Dimensional Jewel",
        "accessoir",
        "509",
        "",
        "75",
        "",
        "",
        "",
        "ИНТ +8%. При активном нанесении урона навыком есть 30% шанс снизить перезарядку навыка на 1 ход.",
        "INT +8%. When attacking with a skill, 30% chance t reduce cooldown by 1"
    ],
    [
        "Драупнир",
        "Draupnir",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "ИНТ +8%. Подвергнувшись дальней атаке, юнит отражает 30% полученного урона.",
        "INT +8%. When attacked with a ranged attack, reflects damage taken this time by 30%."
    ],
    [
        "Закон созидания",
        "Law of Creation",
        "accessoir",
        "509",
        "",
        "75",
        "",
        "",
        "",
        "ИНТ +8%. При атаке и вступлении в бой, если используемый навык особо эффективен против врага, то герой наносит на 10% больше магического урона.",
        "INT +8%. When attacking and entering battle, if the skill used is super effective against the enemy hero, than the hero deals 10% increased magic damage."
    ],
    [
        "Звёздные серьги",
        "Star Earring",
        "accessoir",
        "509",
        "",
        "75",
        "",
        "",
        "",
        "ИНТ +8%. В боях против лучников и убийц ЗАЩ увеличивается на 30%.",
        "INT +8%. When battling against Assassin and Archer DEF increases by 30%."
    ],
    [
        "Значок повелителя",
        "Overlord Badge",
        "accessoir",
        "509",
        "75",
        "",
        "",
        "",
        "",
        "Все характеристики +5%. Иммунитет к снижению ЗАЩ и МЗАЩ, снижению АТК и ИНТ, снижению мобильности.",
        "All stats +5%. Grants immunity to DEF and MDEF reduction, ATK and INT reduction, mobility reduction."
    ],
    [
        "Истинный крест",
        "True Cross",
        "accessoir",
        "509",
        "",
        "75",
        "",
        "",
        "",
        "Эффекты исцеления +15%. В боях против демонов и магов ИНТ, ЗАЩ и МЗАЩ увеличиваются на 20%.",
        "Healing effects +15%. When battling against Demons and Mages, INT, DEF and MDEF increase by 20%."
    ],
    [
        "Кровопьющий шип",
        "Bloodthirsty Nail",
        "accessoir",
        "",
        "75",
        "",
        "43",
        "",
        "",
        "АТК +8%. Иммунитет к безмолвию активного умения.",
        "ATK +8%. Immune to active skill silence."
    ],
    [
        "Крылатые щитки на голень",
        "Winged Shin Guards",
        "accessoir",
        "",
        "75",
        "",
        "43",
        "",
        "",
        "АТК +8%. Когда атакованы, ЗАЩ увеличивается на 10%.",
        "ATK +8%. When attacked, DEF increases by 10%."
    ],
    [
        "Крылья скрытого великолепия",
        "Wings of Hidden Splendor",
        "accessoir",
        "509",
        "75",
        "",
        "",
        "",
        "",
        "Все аттрибуты +5%. В конце действия, если герой не нанёс никакого урона, 100% шанс получить мобильность +2. Длится 1 раунд. (Если уже есть другое повышение мобильности, дает Мобильность +3)",
        "All attributes +5%. At the end of the action, if the hero has not dealt any damage, there is a 100% chance to gain +2 mobility. Lasts 1 round. (If there is already another mobility boost, gives Mobility +3)"
    ],
    [
        "Кулон заговора",
        "Insidious Pendant",
        "accessoir",
        "",
        "75",
        "",
        "",
        "",
        "37",
        "Все статы увеличиваются на 5%. При вступлении в бой крит увеличивается на 5%.",
        "All stats increase by 5%. When entering battle, crit increases by 5%."
    ],
    [
        "Лезвие воспоминаний",
        "The Edge of Memories.",
        "accessoir",
        "",
        "75",
        "",
        "43",
        "",
        "",
        "АТК +8%. При атаке с умением, наносящим урон, есть 30% шанс снизить перезарядку этого умения на 1-2 хода случайно.",
        "ATK +8%. When entering battle with a damage-dealing skill, 30% chance to reduce that skill's cooldown by 1-2 at random."
    ],
    [
        "Медаль кузнеца",
        "Swordsmith's Medal",
        "accessoir",
        "",
        "",
        "",
        "48",
        "43",
        "",
        "Все статы +5%. Иммунитет к фиксированному урону и эффектам, оглушающим активные навыки.",
        "All stats +5%. Immune to fixed damage and effects that silence active skills."
    ],
    [
        "Ожерелье Тора",
        "Thor's Necklace",
        "accessoir",
        "",
        "75",
        "",
        "43",
        "",
        "",
        "АТК +5%. При инициировании боя может с 50% шансом нанести один раз фиксированный урон врагу после боя (урон - 1хАТК героя).",
        "ATK +5%. When initiating battle, has a 50% chance to deal fixed damage once to the enemy unit after battle. This damage is equal to 1x the hero's attack."
    ],
    [
        "Око смотрящего",
        "Eye of the Beholder",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "ИНТ +8%. Когда атакуете, после боя дает 50% шанс снизить наносимый врагом урон на 15%. Длится 1 ход.",
        "INT +8%. When attacking, after battle, grants a 50% chance to reduce enemy's damage dealt to 15%. Lasts 1 turn."
    ],
    [
        "Пакт крови",
        "Blood Pact",
        "accessoir",
        "1102",
        "",
        "",
        "",
        "",
        "",
        "ОЗ +15%. Иммунитет к отмене исцеления и запрету на баффы.",
        "HP +15%. Grantes immunity to effects that prevent you from being healed or buffed."
    ],
    [
        "Пелена света",
        "Veil of Light",
        "accessoir",
        "509",
        "",
        "",
        "",
        "48",
        "",
        "МЗАЩ +8%.Иммунитет к снижению ЗАЩ и МЗАЩ.",
        "MDEF +8%. Immune to DEF and MDEF reduction."
    ],
    [
        "Перо ангела",
        "Angel Feather",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "ОЗ +10%. Эффекты исцеления +10%. Иммунитет к оглушению.",
        "HP +10%. Healing effects +10%. Grants immunity to stun."
    ],
    [
        "Плюшевый Джаглер",
        "Jugler Plushy",
        "accessoir",
        "509",
        "",
        "75",
        "",
        "",
        "",
        "Эффект исцеления +15%. Если вы применяете навык поддержки на 1 юнита, эффект длится +1 ход.",
        "Heal effect +15%. When you use a single unit assist skill, the effect lasts +1 turn."
    ],
    [
        "Ползучий прилив",
        "Creeping Tide",
        "accessoir",
        "509",
        "",
        "75",
        "",
        "",
        "",
        "ИНТ +8%. После атаки и нанесения урона 70% шанс снизить МЗАЩ врага на 20% на 1 ход.",
        "INT +8%. After attacking and dealing damage, 70% chance to reduse enemy's MDEF for 20% by 1 turn."
    ],
    [
        "Пояс великана",
        "Giant Belt",
        "accessoir",
        "509",
        "",
        "",
        "48",
        "",
        "",
        "Когда подвергаетесь ближней атаке, ЗАЩ и МЗАЩ увеличиваются в бою на 10%.",
        "When attacked with a melee attack, DEF and MDEF increase by 10% in battle."
    ],
    [
        "Роза Видара",
        "Vidar's Rose",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "ИНТ +8%. При активном нанесении урона имеет 50% шанс снять с врага 1 бафф.",
        "INT +8%. When dealing damage on your turn is 50% chance to dispell 1 buff from the enemy."
    ],
    [
        "Святое кольцо",
        "Holy Ring",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "ИНТ +8%. Иммунитет к безмолвию активного умения.",
        "INT +8%. Immune to active skill silence."
    ],
    [
        "Святой грааль",
        "Holy Grail",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "ИНТ +5%. При нанесении урона восстанавливает 15% ОЗ остальным дружественным юнитам в радиусе 1 клетки после совершения действия.",
        "INT +5%. When dealing damage, restores 15% HP of other friendly unit 1 block adjacent to you after taking action."
    ],
    [
        "Священный ковчег",
        "Holy Ark",
        "accessoir",
        "509",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +8%. Когда подвергаетесь ближней атаке, отражается 30% урона.",
        "HP +8%. When attacked with a melee attack, reflects 30% damage."
    ],
    [
        "Сердце Геи",
        "Heart of Gaia",
        "accessoir",
        "",
        "75",
        "",
        "43",
        "",
        "",
        "Все статы увеличиваются на 5%. Иммунитет к ранящему проклятию (получаемое исцеление превращается в урон) и отмене исцеления (применяемое исцеление превращается в урон).",
        "All stats increase by 5%. Immune to Curse of Wounding (healing received is converted into damage) and Heal Reversal (healing applied is converted into damage)."
    ],
    [
        "Сердце искупления",
        "Heart of Redemption",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "Эффекты исцеления +15%. Иммунитет к фиксированному урону.",
        "Healing effects +15%. Immune to fixed damage."
    ],
    [
        "Слеза богини",
        "Goddess Tear",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "Эффекты исцеления +15%. После завершения действия снимает 2 дебафф с 2 дружественного юнита в радиусе 2 клеток.",
        "Healing effects +15%. After taking action, dispels 2 debuff from 2 nearby friendly unit within 2 blocks (not including this unit)."
    ],
    [
        "Сокровище узника",
        "Prisoner's Gear",
        "accessoir",
        "509",
        "75",
        "",
        "",
        "",
        "",
        "АТК +8%. В сражении с кавалерией АТК увеличивается дополнительно на 12%.",
        "ATK +8%. When battling against Cavalry, increases ATK by an additional 12%."
    ],
    [
        "Сумеречная звезда",
        "Twiight Star",
        "accessoir",
        "",
        "75",
        "75",
        "",
        "",
        "",
        "АТК и ИНТ +5%. Перед инициированием боя наносит фиксированный урон в 1хАТК или ИНТ (смотря, что ниже). Если вражеский юнит состоит из смешанных войск, он не получает иммунитет к наносимому в этот раз урону.",
        "ATK and INT +5%. Before initiating battle, deales fixed damage to the enemy 1 time, equal to 1x of hero's ATK of INT (whichever is lowest). If the enemy is formed of mixed units, they will not be unvulnerable to damage dealed this time."
    ],
    [
        "Талисман судьи",
        "Judge Talisman",
        "accessoir",
        "",
        "75",
        "",
        "43",
        "",
        "",
        "АТК +8%. В сражениях со святыми АТК увеличивается ещё на 12%.",
        "ATK +8%. When battling against Holy units, ATK increases by an extra 12%."
    ],
    [
        "Узы Араши",
        "Bond of Arashi",
        "accessoir",
        "509",
        "",
        "",
        "48",
        "",
        "",
        "Все характеристики +5%. Иммунитет к оглушению и безмолвию пассивного умения.",
        "All stats +5%. Immune to stun and passive skill silence."
    ],
    [
        "Эльфийский пояс",
        "Elven Belt",
        "accessoir",
        "509",
        "",
        "",
        "48",
        "",
        "",
        "Когда подвергаетесь дальней атаке, ЗАЩ и МЗАЩ увеличиваются в бою на 10%.",
        "When attacked with a ranged attack, DEF and MDEF increase by 10% in battle."
    ],
    [
        "Эльфийское кольцо",
        "Elven Ring",
        "accessoir",
        "509",
        "75",
        "",
        "",
        "",
        "",
        "Когда атакуете, АТК и ЗАЩ увеличиваются на 8%.",
        "When attacking, ATK and DEF increase by 8%."
    ],
    [
        "Эмблема истребителя",
        "Slayer's Emblem",
        "accessoir",
        "509",
        "75",
        "",
        "",
        "",
        "",
        "АТК +8%. В боях против асов АТК увеличивается на 12%.",
        "ATK +8%. When battling against Fliers, ATK increases by extra 12%."
    ],
    [
        "Ядро хитрости",
        "Core of Guile",
        "accessoir",
        "",
        "",
        "",
        "48",
        "43",
        "",
        "Все характеристики +5%. Когда втянуты в бой, ЗАЩ или МЗАЩ ( что ниже) увеличивается на 5%.",
        "All stats +5%. When forced into battle, DEF or MDEF (whichever is lower) increases by 5%."
    ],
    [
        "Акс2",
        "---",
        "accessoir",
        "",
        "",
        "",
        "48",
        "43",
        "",
        "Все аттрибуты +5%. В начале раунда получает 'Иммунитет к 1 дебафу. Восстанавливает 20% ОЗ при срабатывании'. Не может быть снят'",
        "All attributes +5%. At the beginning of the round, gains 'Immunity to 1 debuff. Restores 20% HP when triggered.' Cannot be removed.'"
    ],
    [
        "Акс 3",
        "---",
        "accessoir",
        "",
        "75",
        "75",
        "",
        "",
        "",
        "АТК и ИНТ +5%. При активной атаке и вступлении в бой, заглушает навык аксессуара противника. Если цель неигровой герой - вместо этого эффект заменяется на 'Получаемый урон увеличивается на 10%'",
        "ATK and INT +5%. When actively attacking and entering battle, it silence the skill of the enemy’s accessory. If the target is a non-player hero, the effect is instead replaced with 'Damage taken increases by 10%'"
    ],
    [
        "Белая мантия Бальдра",
        "Baldr's White Robe",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "МЗАЩ +10%. Перед вынужденным вступлением в ближний бой с 20% шансом отменяет снижение урона в ближнем бою.",
        "MDEF +10%. Before being forced into battle through melee attack, 20% chance that the unit's damage will not e reduced in melee battle."
    ],
    [
        "Благородная броня",
        "Noble Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ +10%. Уменьшает АоЕ урон на 10%.",
        "DEF +10%. Reduce AoE damage by 10%."
    ],
    [
        "Благословение Тиамат",
        "Tiamaat's Blessing",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ и МЗАЩ +5%. Юниты получают на 20% меньше магического урона, когда у них Смешанные войска.",
        "HP and MDEF +5%. Unit takes 20% less Magic Damage when in mixed units."
    ],
    [
        "Боевая броня Эола",
        "Aeolus' Battle Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ и ЗАЩ +5%. Подвергнувшись дальней атаке с 30% шансом снижает весь получаемый вашим юнитом урон в этой битве на 30%.",
        "HP and DEF +5%. When under ranged attack, has a 30% chance to lower damage taken by your unit in this battle by 30%."
    ],
    [
        "Броня Геи",
        "Gaea's Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "Когда атакованы, ЗАЩ увеличивается на 15%. При ОЗ больше 80% получаемый магический урон снижен на 10%.",
        "When attacked, DEF increases by 15%. When unit's HP is above 80%, Mdamage taken decreases by 10%."
    ],
    [
        "Броня пограничного авангарда",
        "Frontier Vangard Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ и МЗАЩ +5%. При обороне ЗАЩ и МЗАЩ увеличиваются еще на 10%.",
        "DEF and MDEF +5%. When guarding, DEF and MDEF increase by a futher 10%."
    ],
    [
        "Броня родовой магии",
        "Bloodline Magic Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ и ЗАЩ +5%. Подвергнувшись ближней атаке с 30% шансом снижает весь получаемый вашим юнитом урон в этой битве на 30%.",
        "HP and DEF +5%. When under melee attack, has a 30% chance to lower damage taken by your unit in this battle by 30%."
    ],
    [
        "Броня Энея",
        "Aeneas' Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ +10%, получаемый эффект исцеления +10%.",
        "DEF +10%. Received Heal Effect +10%."
    ],
    [
        "Галактический плащ",
        "Galaxy Cloak",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "МЗАЩ +10%, ОЗ +5%.",
        "MDEF +10%, HP +5%."
    ],
    [
        "Доспехи хранителя",
        "Forbidden Defender's Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ и МЗАЩ +5%. Когда вступает в навязанный бой, может с 30% шансом уменьшить урон, получаемый в этом бою, на 20%.",
        "DEF and MDEF +5%. When forced into battle, has a 30% chance to reduce unit damage taken in this battle by 20%."
    ],
    [
        "Древний доспех",
        "Ancient Plate Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "Защита повышается на 10%. Получаемый фиксированный урон снижается на 10%.",
        "DEF +10%. Fixed damage taken decreased by 10%."
    ],
    [
        "Жилет Короля обезьян",
        "Monkey King's Vest",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "Когда атакованы, АТК и крит увеличиваются на 15%.",
        "When attacked, ATK and Crit increase by 15%."
    ],
    [
        "Зеркальная броня",
        "Mirror Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ и ЗАЩ +5%. Когда атакованы, наносит врагу фиксированный урон (Урон - 1,5х ЗАЩ заклинателя).",
        "HP and DEF +5%. Before attacked with a melee attack, deals fixed damage to enemy (damage - 1,5x Hero's DEF)"
    ],
    [
        "Кожа ящерицы - демона",
        "Demon Lizard Skin",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ОЗ +10%. Когда атакованы, с 50% шансом накладывает один мощный дебафф.",
        "HP +10%. When attacked, 50% to deal one random debuff"
    ],
    [
        "Костюм штурма",
        "Assault Suit",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ОЗ +5%. Когда атакуете, ЗАЩ и МЗАЩ увеличиваются на 10%.",
        "HP +5%. When attacking, increases DEF and MDEF by 10%."
    ],
    [
        "Крылья Хугина",
        "Fujin's Wing",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +5%. Будучи атакованным в ближнем бою, юнит получает +15% к ЗАЩ и МЗАЩ.",
        "HP +5%. When melee attacked, DEF and MDEF +15%."
    ],
    [
        "Куртка горгульи",
        "Gargoyle Jacket",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ОЗ +5%. Когда атакованы, ЗАЩ увеличивается на 15%.",
        "HP +5%. When attacked, DEF increases by 15%."
    ],
    [
        "Лазаревая легенда",
        "Azure's Legend",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ОЗ +10%. Когда ОЗ выше 50%, ЗАЩ увеличивается на 10%. Когда ОЗ ниже 50%, МЗАЩ увеличивается на 10%.",
        "HP +10%. When unit HP is above 50%, DEF increases by 10%. When unit HP is below 50%, MDEF increases by 10%."
    ],
    [
        "Мантия смерти",
        "Death's Robe",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "Крит снижается на 40%. Когда атакованы, с 30% шансом повышает получаемый врагом урон на 20%. Длится 2 хода.",
        "Chance of being criically hit is reduced by 40%. When attacked, 30% chance to increase enemy's damage taken by 20%. Lasts 2 turn."
    ],
    [
        "Мантия Теннио",
        "Tennyo's Robe",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +10%. Когда атакованы, с 30% шансом снимает с противника 1 бафф и накладывает 1 случайный дебафф.",
        "HP +10%. When attacked, 30% chance to dispel 1 enemy's buff and inflict 1 random debuff to the enemy."
    ],
    [
        "Мрачные одеяния",
        "Nebulous Robe",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +10%. При инициировании боя получаемый отраженный урон снижается на 30%.",
        "HP +10%. When initiating battle, reflect demage taken is reduced by 30%."
    ],
    [
        "Новое одеяние жнеца",
        "The Reaper's New Clothes",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "Вероятность критического удара уменьшается на 40%. Вступая в навязанный бой, 30% шанс уменьшить наносимый противником урон на 20%. Длится 2 хода.",
        "Chance of being critically hit is redused by 40%. Before forced into battle, 30% chance to reduse enemy's damage dealt by 20%. Lasts 2 turn."
    ],
    [
        "Одеяния Альянса",
        "Alliance Robes",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ОЗ +10%. ЗАЩ и МЗАЩ героев увеличивается на 8%, если они не состоят из смешанных сил.",
        "HP +10%. Hero DEF and MDEF inrease by 8%, when not composed of mixed force."
    ],
    [
        "Охотничьи угодья",
        "Hunter King's Harness",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ОЗ и ЗАЩ +5%. При вступлении в бой, если НАВЫК выше, чем у противника, есть шанс 30% снижения получаемого урона на 20%.",
        "HP and DEF +5%. When entering battle, if the SKILL is higher than the enemy, there is a 30% chance of reducing damage taken by 20%."
    ],
    [
        "Плащ неповиновения",
        "Cloak of Defiance",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ЗАЩ и МЗАЩ +5%. Перед вступлением в навязанный в результате дальней атаки бой наносит врагу фиксированный урон (Урон - 1,5х МЗАЩ заклинателя).",
        "DEF and MDEF +5%. When attacked with a range attack, deals fixed damage to enemy (damage = 1,5x Hero's MDEF)"
    ],
    [
        "Последние обряды",
        "Last Rites",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ЗАЩ +10%. Когда ОЗ этого юнита равно 100% снижает весь получаемый урон на 40%.",
        "DEF +10%. When HP of this unit is on 100%, lowers all damage taken by 40%."
    ],
    [
        "Решимость гиганта",
        "Giant's Resolve",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ +10%. Шанс получения крита -20%.",
        "DEF +10%. Chance of being critically hit -20%."
    ],
    [
        "Ритуал замешательства",
        "Ritual of Confusion",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "Получаемый АоЕ урон снижен на 15%, эффекты лечения +10%.",
        "AoE damage taken decreases by 15% and healing effects +10%."
    ],
    [
        "Ряса Богини",
        "Goddess Dress",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ЗАЩ +10%. Получаемый эффект исцеления +10%.",
        "DEF +10%. Received Heal Effect +10%."
    ],
    [
        "Сияющие латы",
        "Shimmering Battlesuit",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "Получаемый АоЕ урон снижен на 20%. Когда втянуты в бой, с 50% шансом снижает АТК и ИНТ врага на 20%. Длится 1 ход.",
        "AoE damage taken decreases by 20%. When forced into battle, 50% chance to reduce enemy's ATK and INT by 20% before battle. Lasts 1 turn."
    ],
    [
        "Сумеречная броня",
        "Twilight Armor",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "МЗАЩ +8%, ЗАЩ +8%.",
        "MDEF +8%, DEF +8%."
    ],
    [
        "Сумеречный страж",
        "Twiight Guard",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "МЗАЩ +10%. Эффекты исцеления увеличиваются на 10%.",
        "MDEF +10%. Healing effect increased by 10%."
    ],
    [
        "Таинственный боевой доспех",
        "Arcane Battlegarb",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ и МЗАЩ +5%. При инициировании атаки наносит фиксированный урон врагу после атаки (урон - 1,5хМЗАЩ героя).",
        "HP and MDEF +5%. When attacking, after battle deals fixed damage once to the enemy (Damage - 1,5x Hero's MDEF)."
    ],
    [
        "Тёмная мантия",
        "Dark Robe",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +5%. Когда подвергаетесь дальней атаке, ЗАЩ и МЗАЩ увеличиваются на 15%.",
        "HP +5%. When attacked with a range attack, DEF and MDEF increase by 15%."
    ],
    [
        "Углеродная броня",
        "Carbon Fiber Armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "Когда ОЗ юнита выше 50%, ЗАЩ и МЗАЩ увеличиваются на 8%. Когда ОЗ юнита ниже 50%, АТК и Навык увеличиваются на 8%.",
        "When unit HP is about 50%, DEF and MDEF increase by 8%. When unit HP is below 50%, ATK and SKILL increase by 8%."
    ],
    [
        "Броня2",
        "---",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "Если ОЗ юнита выше 50%, ЗАЩ и МЗАЩ +8%. Если ОЗ ниже 50%, сила исцеления и получаемое исцеление +8%.",
        "If the unit's HP is above 50%, DEF and MDEF +8%. If HP is below 50%, healing power and received healing +8%."
    ],
    [
        "Броня 3",
        "---",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ОЗ +10%. При активной атаке и вступлении в бой, получаемый урон в бою снижается на 6% за каждую клетку перемещённую перед боем (до 18%).",
        "HP +10%. When actively attacking and entering battle, the damage received in battle is reduced by 6% for each cell moved before the battle (up to 18%)."
    ],
    [
        "Благословение Коронет",
        "Benediction Coronet",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. После совершения действия дает одному смежному союзному юниту иммунитет к превращению лечения в урон и запрету на баффы на 1 ход.",
        "HP +10%. After taking action, grants 1 adjacent ally 20% increased DEF and immunity to Curse of Wounding (converts healing received into damage) and buff block for 1 turn."
    ],
    [
        "Боевой шлем Одина",
        "Odin's Battle Helm",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "МЗАЩ +10%. В случае уничтожения врага на этом ходу снимает 5 бафф с 1 врага в радиусе 3 клеток после совершения действия.",
        "MDEF +10%. When eliminating an enemy on this turn, dispels 5 buff from 1 enemy within 3 blocks after taking action."
    ],
    [
        "Венок Иггдрасиля",
        "Yggdrasil Wreath",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ+10%. После совершения действия дает одному союзнику рядом (не себе) 20% дополнительной МЗАЩ, а также иммунитет к оглушению, блокированию баффов и замедлению на 1 ход.",
        "HP +10%. After taking action, grants 1 friendly unit near you (not including this unit) 20% extra MDEF and negates stun, buff block and speed decrease effects for 1 turn."
    ],
    [
        "Вестник Судного дня",
        "Doomsday Herald",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "МЗАЩ +10%, После совершения действия может с 50% шансом наложить на 1 вражеского юнита в пределах 2 клеток запрет на получение лечения. Длится 1 ход.",
        "MDEF +10%. After taking action has a 50% chance to render 1 enemy unit within 2 blocks unable to receive healing. Lasts 1 turn."
    ],
    [
        "Взгляд демона дракона",
        "Demon Dragon's Gaze",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +5%. Когда герой вынужден вступить в бой под дальней атакой, ЗАЩ +15%.",
        "HP +5%. When forced into battle by a ranged attack, Hero DEF increses by 15%."
    ],
    [
        "Гнев Иерофанта",
        "Wrath of the Hierophant",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. Когда атакован, АТК увеличивается на 8%.",
        "HP +10%. When attacked, ATK increases by 8%."
    ],
    [
        "Головной убор похитителя душ",
        "Soul Stealer Headdress",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "МЗАЩ +10%. После завершения действия с 50% шансом деактивирует активные навыки 1 врага в радиусе 3 клеток. Длится 1 ход.",
        "MDEF +10%. After taking action, 50% chance to silence active skills of 1 enemy within 3 blocks. Lasts 1 turn."
    ],
    [
        "Головной убор Теннио",
        "Tennyo's Headdress",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. После совершения действия с 100% шансом накладывает 1 случайный бафф на 1 союзника в радиусе 2 клеток.",
        "HP +10%. After taking action, 100% chance to grant 1 random buff to 1 friendly unit within 2 blocks (not including this unit)."
    ],
    [
        "Дыхание жнеца",
        "Reaper Breath",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. Уничтожив врага на этом ходу, после завершения действия наносит один фиксированный урон по врагам в радиусе 2 клеток (урон - 20% от максимального ОЗ).",
        "HP +10%. When eliminating enemy on this turn, after taking action, deals fixed damage once to enemies within 2 blocks at the end of your next turn (damage = 20% of max HP)."
    ],
    [
        "Завеса звезд",
        "Star crown",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Если ОЗ юнита >80%, после исцеления другими дружественными войсками, получает 'урон умений увеличен на 10%' и 'АТК +10%', длится 1 раунд.",
        "HP +10%. If a unit's HP >80%, after being healed by other friendly units, receives 'skill damage increased by 10%' and 'ATK +10%', lasts 1 round."
    ],
    [
        "Королевская корона",
        "King's Crown",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ и МЗАЩ +5%. После завершения действия дает 1 смежному союзному юниту (не себе) 20% дополнительного урона на 1 ход.",
        "HP and MDEF +5%. After taking damage, grants 1 adjacent friendly unit (not including this unit) 20% extra damage for 1 turn)."
    ],
    [
        "Корона ледяного пламени",
        "Frostfire Crown",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "МЗАЩ +10%. При инициировании боя полученный урон снижается на 10%.",
        "MDEF +10%. When initiating battle, damage taken is reduces by 10%."
    ],
    [
        "Крылатый шлем сумерек",
        "Winged Helm of Twilight",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. Перед активным вступлением в бой, добавляет к ЗАЩ или МЗАЩ (смотря какой ниже) 8% аттрибуты который выше.",
        "HP +10%. Before actively entering battle, adds 8% of the higher attribute of DEF or MDEF to lower."
    ],
    [
        "Маска вампира",
        "Vampire's Mask",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ЗАЩ +10%. После совершения действия может с 50% шансом снизить ЗАЩ 1 врага в радиусе 2 клеток на 20%. Длится 1 ход.",
        "DEF +10%. After taking action has a 50% chance to reduce the DEF of 1 enemy within 2 blocks by 20%. Lasts 1 turn."
    ],
    [
        "Маска Локи",
        "Loki's Mask",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +5%. Когда подвергаетесь ближней атаке, ЗАЩ увеличивается на 15%.",
        "HP +5%. When attacked with a melee attack, DEF increases by 15%."
    ],
    [
        "Меховые наушники",
        "Utlimate Ear Muffs",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. После совершения действия 1 расположенного рядом союзника получать на 15% меньше урона и дает иммунитет к фиксированному урону. Длится 1 ход.",
        "HP +10%. After taking action makes 1 adjacent ally take 15% less damage and become immune to fixed damage for 1 turn."
    ],
    [
        "Око Ермунганда",
        "Jormungandr's Eye",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ и ЗАЩ +5%. После завершения действия есть 50% шанс на снижение наносимого урона на 15% у 1 врага в радиусе 2 клеток. Длится 1 ход.",
        "HP and Def +5%. After taking action, 50% chance to decrease damage dealt by 15% for 1 enemy within 2 blocks. Lasts 1 turn."
    ],
    [
        "Отголосок ведьмы",
        "Witch's Reminiscence",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. После совершения действия НАВЫК 1 ближайшего союзного юнита увеличивается на 20%. Получает иммунитет к отмене исцеления (получаемое исцеление превращается в урон) и эффектам, запрещающим Повторное действие на 1 ход.",
        "HP +10%. After taking action, increses SKILL of 1 nearby friendly unit by 20%. Grants immunity to heal reversal (healing dealt is converted into damage) and effectsthat stop you from acting again for 1 turn."
    ],
    [
        "Перьевая корона Ньорда",
        "Njord's Feathered Crown",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. В битвах против юнитов с меньшим ОЗ ЗАЩ и МЗАЩ увеличиваются на 15%.",
        "HP +10%. When battling unit with les HP, DEF and MDEF increase by 15%."
    ],
    [
        "Повелитель разрядов",
        "Electric Headwear",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ+10%. После совершения действия, если рядом стоит союзник, наносит на 10% больше урон контратаки и получает иммунитет к перемещению на 1 ход.",
        "HP +10%. After taking action, if another friendly unit is adjacent, then both the hero and 1 adjacent friendly unit deal 10% increased counterattack damage and gain immunity for displacement for 1 turn."
    ],
    [
        "Сияние мира",
        "Glory of the World",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Перед тем, как быть втянутым в бой, восстанавливает 10% ОЗ цели, если юнит состоит из смешанного войска. Блокирует смертельные удары, вызванные фиксированным уроном (активируется только 1 раз за бой).",
        "HP +10%. Before being forced into battle, heals 10% of HP if unit is formed of mixed units. Blocks fatal strikes caused by fixed damage (only triggers 1 time per battle)."
    ],
    [
        "Снежная шапочка",
        "Snow Beanie",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. При нападении и принуждении к битве 50% шанс увеличить ЗАЩ на 20%.",
        "HP +10%. When attacked and forced into battle, 50% to increase DEF by 20%."
    ],
    [
        "Сумеречный шлем",
        "Twilight Helmet",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "МЗАЩ +8%, ЗАЩ +8%.",
        "MDEF +8%, DEF +8%."
    ],
    [
        "Тёмная корона",
        "Dark Crown",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "МЗАЩ +10%, ОЗ +5%.",
        "MDEF +10%, HP +5%."
    ],
    [
        "Тиара",
        "Tiara",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "Когда у юнита 100% ОЗ, ЗАЩ и МЗАЩ увеличиваются на 15%.",
        "When unit HP is at 100%, MDEF and DEF increase by 15%."
    ],
    [
        "Углеродный Шлем",
        "Carbon Fiber Helm",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "Когда ОЗ юнита выше 50%, ЗАЩ и МЗАЩ увеличиваются на 8%. Когда ОЗ юнита ниже 50%, АТК и Навык увеличиваются на 8%.",
        "When unit HP is above 50%, DEF and MDEF increase by 8%. When unit HP is below 50%, ATK and SKILL increase 8%."
    ],
    [
        "Харон",
        "Charon",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ЗАЩ +10%. В конце хода есть 50% шанс на увеличение всего получаемого урона на 15% у 1 врага в радиусе 3 клеток. Длится 1 ход.",
        "DEF +10%. After taking action has a 50% chance to increase all damage received by 15% for 1 enemy within 3 blocks. Lasts 1 turn."
    ],
    [
        "Шапка штурма",
        "Assault Headgear",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +5%. Когда атакуете, ЗАЩ и МЗАЩ увеличиваются на 10%.",
        "HP +5%. When attacking, increases DEF and MDEF by 10%."
    ],
    [
        "Шлем Виндлера",
        "Rigel Helm",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. Урон контратаки +15% при защите союзников.",
        "HP +10%. Increases counterattack damage by 15% when guarding allies."
    ],
    [
        "Шлем Геи",
        "Gaea's Helmet",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "Когда атакованы, МЗАЩ +15%. При ОЗ выше 80% получаемый физический урон снижен на 10%.",
        "When attacked, MDEF increases by 15%. When unit HP is above 80%, physical damage taken is reduced by 10%."
    ],
    [
        "Шлем правителя",
        "Chief's Helmet",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. После совершения действия дает одному смежному союзному юниту (не себе) дополнительно 20% ЗАЩ и запрещает эффекты снижения ЗАЩ, МЗАЩ и запрета на исцеление на 1 ход.",
        "HP+10%. After taking action grants 1 adjacent ally (not including this unit) 20% extra DEF and negates DEF and MDEF reduction effects and effects that prevent them from being healed for 1 turn."
    ],
    [
        "Шлем Энея",
        "Aeneas' Helmet",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%, ЗАЩ +5%.",
        "HP +10%, DEF +5%."
    ],
    [
        "Шляпа с цветком",
        "Flower Boon Bonnet",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. После совершения действия, если ОЗ юнита меньше 50%, исцеляет 20% ОЗ.",
        "HP+10%. After taking action, if this unit HP is below than 50%, heals 20% of HP."
    ],
    [
        "Ярость Тюра",
        "Fury of Tyr",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ЗАЩ +10%. Если после совершения действия вы не нанесли урон, урон навыка повышается на 10%, урон контратаки повышается на 10% на 1 ход.",
        "DEF +10%. After taking action, if you haven't dealt damage, skill damage is increased by 10% and counterattack damage increases by 10% for 1 turn."
    ],
    [
        "Шлем2",
        "---",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. Если в конце действия в пределах 2 блоков нет врагов, получает 'Урон умений увеличивается на 5%' и 'АоЕ урон увеличивается на 10%', длится 1 ход.",
        "HP +10%. If at the end of the action there are no enemies within 2 blocks, receives 'Skill damage increased by 5' and 'AoE damage increased by 10', lasts 1 turn."
    ],
    [
        "Головной убор 3",
        "---",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +5%. Когда атакован врагом ОЗ которого равно или ниже вашего, ЗАЩ +10% в бою.",
        "HP +5%. When attacked by an enemy whose HP is equal to or lower than yours, DEF +10% in battle."
    ],
    [
        "Алый жнец",
        "Scarlet Reaper",
        "weapon",
        "364",
        "118",
        "",
        "",
        "",
        "",
        "АТК +10%, Если перед активным нанесением урона ОЗ врага меньше 100%, то наносимый урон в этот раз повышается на 5%, а после нанесения урона наносит фиксированный урон, равный АТК героя х0,5 1 раз.",
        "ATK +10%. Before actively dealing damage, if the enemy's HP is less then 100%, damage dealt this time is increased by 5%, and after dealing damage, deals fixed damage 1 time equal to Hero's ATKx0,5."
    ],
    [
        "Астарот",
        "Astaroth",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "Во время боя с врагами, пораженными дебаффами, ИНТ увеличивается на 15%. Перед атакой, с 30% шансом оглушает врага после боя. Длится 1 ход.",
        "When battling enemies afflicted by debuff, INT increases by 15%. When attacking, 30% chance to stun the enemy after battle. Lasts 1 turn"
    ],
    [
        "Блеклый посох",
        "Pale Staff",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "Урон увеличивается на 15% при использовании навыка, поражающего одну цель. После активного вступления в битву с 50% шансом накладывает на врага дебафф Уязвимость. Длится 1 ход.",
        "Damage increases by 15% when casting single-target skills. When actively entering battle, has 50% chance of afflicting the enemy with a random debuff. Lasts for 1 turn."
    ],
    [
        "Божественный скипетр",
        "Scepter of Divinity",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ОЗ +5%. Когда юнит находится на местности без бонуса к защите и использует дальние навыки для иницирования боя, его дальность увеличивается на 1 (этот эффект перекрывает эффект, который игнорирует снижение ближнего урона)",
        "HP +5%. When on terrain with no defensive bonus and using ranged skills to initiate battle, unit range is increased by 1. (Skills that ignored melee penalty override this effect)."
    ],
    [
        "Ветвь Иггдрасиля",
        "Yggdrasil Branch",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "ЗАЩ +10%. В бою игнорирует 15% ЗАЩ врага.",
        "DEF +10%. In battle, ignores 15% of enemy's DEF."
    ],
    [
        "Врата истины",
        "Gate of Truth",
        "weapon",
        "583",
        "",
        "85",
        "",
        "",
        "",
        "Когда атакуете, увеличивает ИНТ, ЗАЩ, и МЗАЩ на 15%.",
        "When attacking, increases iNT, DEF and MDEF by 15%."
    ],
    [
        "Дар вечной жизни",
        "Gift of Eternal Life",
        "weapon",
        "583",
        "",
        "85",
        "",
        "",
        "",
        "ИНТ +5%. После атаки исцеляет дружеского юнита с наименьшим ОЗ (3х ИНТ заклинателя).",
        "INT +5%. When attacking,after battle heals friendly unit with the lowest HP (3x caster's INT)."
    ],
    [
        "Драконоборец Грам",
        "Dragonslayer Gram",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "АТК и ОЗ +8%. В битвах против драконов АТК, ЗАЩ и МЗАЩ увеличиваются на 10%.",
        "ATK and HP +8%. When battling against dragons, ATK, DEF and MDEF is increase by 10%."
    ],
    [
        "Дух печали",
        "Spirit Griever",
        "weapon",
        "",
        "96",
        "",
        "",
        "",
        "54",
        "Когда атакуете, увеличивает крит на 15% и уменьшает получаемый урон на 30%.",
        "When attacking, increases Crit by 15% and reduses damage taken by 30%."
    ],
    [
        "Дьявольский топор",
        "Devil Axe",
        "weapon",
        "364",
        "118",
        "",
        "",
        "",
        "",
        "ОЗ +5%, АТК +5%. Когда атакуете, наносит врагу фиксированный урон один раз (урон - 1хАТК героя) после боя.",
        "HP +5%, ATK +5%. When attacking, after battle deals fixed damage once to the enemy (damage = 1x Hero's ATK)."
    ],
    [
        "Жало скрытня",
        "Lurker's Sting",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "Шанс критического удара +10%, ОЗ +5%. Если перемещается меньше 3 блоков, получает +1 дальность действия при использовании навыка физического урона для вступления в бой.",
        "Crit chance +10%, HP +5%. If moving fewer than 3 blocks, gains +1 unit range when using a physical damage skill to enter battle."
    ],
    [
        "Кинжал режущий ветер",
        "Wind Cutter Dagger",
        "weapon",
        "",
        "96",
        "",
        "",
        "",
        "54",
        "АТК +10%. При инициировании боя дает 50% шанс на снижение ЗАЩ врага на 20% после боя. Длится 1 ход.",
        "ATK +10%. When initiating battle, has a 50% chance to reduce the enemy's DEF by 20% after battle. Lasts 1 turn."
    ],
    [
        "Клятва справедливости",
        "Oath of Justice",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "ЗАЩ +8%, МЗАЩ +8%.",
        "DEF +8%, MDEF +8%."
    ],
    [
        "Козодой",
        "Nighthawk",
        "weapon",
        "",
        "96",
        "",
        "",
        "",
        "54",
        "АТК +10%, МЗАЩ +5%.",
        "ATK +10%, MDEF +5%."
    ],
    [
        "Копье Разрушителя заряда",
        "Charge Breaker Spear",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "АТК +10%. При вынужденном вступлении в бой, ЗАЩ увеличивается на 2% за каждый перемещенную противником клетку (до 10%).",
        "ATK +10%. When forced into battle, DEF increases by 2% for each cell moved by the enemy (up to 10%)."
    ],
    [
        "Копье сокрушения",
        "Routing Light",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "АТК +10%. Наносимый урон увеличивается на 2% за каждую клетку, пройденную до инициирования боя (до 10%). При прохождении 3 и более клеток враг не сможет применять эффект стража в течение 1 хода после боя.",
        "ATK +10%. Damage dealt is increased by 2% for each block, moved before initiating battle (up to 10%). When moving 3 or more blocks, the enemy's Guard is disabled for 1 turn after battle."
    ],
    [
        "Костедробящий молот",
        "Bone-Crusher's Hammer",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "АТК +10%. Перед вступлением в инициированный бой сводит на нет все навыки вражеской брони (кроме эффектов от максимального ОЗ). Если цель - герой, не являющийся игроком, то эффект вместо этого снизит ЗАЩ на 15% на 1 ход.",
        "ATK +10%. When initiating battle and before battle, nullifies all enemy armor skill (aside from max HP effects). If the target is a non-player hero, the effect will instead reduce DEF by 15%. Lasts 1 turn."
    ],
    [
        "Красная луна",
        "Red Moon",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ +10%, ОЗ +5%.",
        "INT +10%, HP +5%."
    ],
    [
        "Кристальное жало",
        "Crystal Stinger",
        "weapon",
        "",
        "96",
        "",
        "",
        "",
        "53",
        "Крит шанс и крит урон увеличиваются на 10%. Если перед боем ваш Навык выше, чем у врага, в этом бою вы игнорируете 20% ЗАЩ врага.",
        "Crit and Crit damage increased by 10%. If your SKILL is higher then the enemy's before battle, you ignore 20% of enemy's DEF in this battle."
    ],
    [
        "Кровавая мелодия",
        "Bloody Melody",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "АТК +10%, ЗАЩ +5%.",
        "ATK +10%, DEF + 5%."
    ],
    [
        "Кровавый меч Хрунтинг",
        "Blood Sword Hrunting",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "АТК +5%. После активного нанесения урона с 50% шансом наносит дополнительный фиксированный урон (урон - 1хАТК героя).",
        "ATK +5%. Has 50% chance to deal extra fixed damage after actively dealing damage (Damage = 1x Hero's ATK)."
    ],
    [
        "Левая рука богини",
        "Goddess's Left Hand",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "Эффекты исцеления +15%. Когда атакуете, с 100% шансом снижает мобильность врага на 2 клетки после боя. Длится 1 ход.",
        "Healing Effects +15%. When attacking, after battle grants a 100% chance to reduce enemy's mobility by 2 blocks. Lasts 1 turn."
    ],
    [
        "Лук гидры",
        "Hydra's Bow",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "АТК +10%. Перед атакой с 50% шансом уменьшает наносимый врагом урон на 20%. Длится 1 ход.",
        "ATK +10%. Before attacking, 50% chance to reduce enemy's damage dealt by 20%. Last 1 turn."
    ],
    [
        "Лук Уллра",
        "Ullr's Bow",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "Физический урон снижен на 10%. Дальность юнита увеличивается на 1.",
        "Physical damage decreases by 10%. Unit range increases by 1."
    ],
    [
        "Метёлка из перьев",
        "Feather Duster",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "Наносимый урон снижается на 10%. Дальность обычной атаки героя +1.",
        "Reduced damage dealt by 10%. Hero's normal attack range +1."
    ],
    [
        "Меч клятвы",
        "Allegiance Blade",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "АТК и ЗАЩ +5%. При наличии классового преимущества, АТК и ЗАЩ +5%.",
        "ATK and DEF +5%. If you have a Fusion Power effect, ATK and DEF +5%."
    ],
    [
        "Миротворец",
        "Peacemaker",
        "weapon",
        "364",
        "118",
        "",
        "",
        "",
        "",
        "АТК +10%. Перед атакой с 50% шансом отключает пассивные навыки врага. Длится 2 хода.",
        "ATK +10%. Before attacking, 50% chance to nullify enemy's passive skills. Lasts 2 turns."
    ],
    [
        "Молот Мимира",
        "Mimir's War-axe",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "АТК +10%. Атаковав и убив врага, или потеряв союзника, вы можете снять с себя 1 дебафф и восстановить 20% ОЗ, при этом получая +20% к урону героя в течение 1 хода.",
        "ATK +10%. After attacking and killing an enemy, or whenever the ally dies, dispel 1 debuff from youself and restore 20% HP, while also gaining Hero Damage +20% for 1 turn."
    ],
    [
        "Морозное лезвие",
        "Frostrend",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "АТК +10%. Когда атакуете, с 50% шансом снижает мобильность врага на 2 клетки после боя. Длится 1 ход после боя.",
        "ATK +10%. When attacking, 50% chance to reduce enemy's mobility by 2 blocks after battle. Lasts 1 turn."
    ],
    [
        "Мьельнир",
        "Mjolnir",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "АТК +10%. Перед атакой с 100% шансом снимает с врага 1 бафф.",
        "ATK +10%. Before attacking, 100% chance to dispel 1 buff from the enemy."
    ],
    [
        "Омела",
        "Mistletoe",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "Эффекты исцеления +15%. Когда атакуете, наносимый врагом урон снижается на 20% после боя. Длится 1 ход.",
        "Healing effects +15%. When attacking, after battle enemy's damage dealt decreases by 20%. Lasts 1 turn."
    ],
    [
        "Очищение сердца",
        "Heart Cleance",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ +10%. При инициировании боя имеет 100% шанс наложить запрет баффов на 1 ход.",
        "INT +10%. When actively entering battle, has a 100% chance of preventing enemy from receiving buffs for 1 turn."
    ],
    [
        "Печать бури",
        "Sigil of Storms",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "ЗАЩ +10%. Вступая в ближний бой, есть 100% шанс нанести врагу один раз фиксированный урон, равный 1хЗАЩ героя.",
        "DEF +10%. Before initiating battle with a melee attack, has 100% chance to deal fixed damage once to the enemy equal to 1x Hero's DEF."
    ],
    [
        "Последний рыцарь",
        "Last Knight",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "АТК +10%. Когда атакуете, с 50% шансом снижает АТК и ИНТ врага на 20%. Длится 1 ход.",
        "ATK +10%. When attackng, 50% to reduce enemy's ATK and INT by 20%. Lasts 1 turn."
    ],
    [
        "Посох Олвера",
        "Olver's Staff",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "Эффекты исцеления +15%. Когда атакуете, после боя дает 50% шанс на увеличение получаемого врагом урона на 20%. Длится 1 ход.",
        "Healing effects +15%. When attacking, after battle grants a 50% chance to increases enemy's damage taken by 20%. Lasts 1 turn."
    ],
    [
        "Призмовый разрушитель",
        "Prismatic Destroyer",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "АТК +10%, урон по площади +10%.",
        "ATK +10%, AoE damage +10%."
    ],
    [
        "Проклятое копье",
        "Cursed Lance",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "Когда атакуете, ЗАЩ увеличивается на 15%, МЗАЩ увеличивается на 15%. После боя с 50% деактивирует активные навыки врагов, не давая им исцелиться. Длится 1 ход.",
        "When attacking, DEF and MDEF +15%. After battle, 50% chance to silence enemy's active skills and prevent them from being healed. Lasts 1 turn."
    ],
    [
        "Рагнарёк",
        "Ragnarok",
        "weapon",
        "364",
        "118",
        "",
        "",
        "",
        "",
        "АТК +10%. Перед атакой с 100% шансом наносит врагу фиксированный урон один раз (урон - 1хАТК героя)",
        "ATK +10%. Before attacking, 100% chance to deal fixed damage once to the enemy (damage = 1x Hero's ATK)."
    ],
    [
        "Разбитая звезда",
        "Broken Star",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "АТК +10%, ЗАЩ +5%.",
        "ATK+10%, DEF+5%."
    ],
    [
        "Рыцарь ветра",
        "Unstoppable Knight",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "АТК +10%. Когда инициирует бой против врага, имеющего 100% ОЗ, АТК, ЗАЩ и МЗАЩ юнита увеличиваются на 5%.",
        "ATK +10%. When initiating battle against the enemy that has 100% HP, ATK, DEF and MDEF increase by 5%."
    ],
    [
        "Сбалансированный клинок",
        "Balanced Blade",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "ЗАЩ и МЗАЩ +5%. Дальность действия АоЕ - навыков +1. (Не может быть использовано с навыками дальностью 1. Не увеличивает ширину линейных АоЕ навыков).",
        "DEF and MDEF +5%. AoE - skill effective range +1. (Cannot be used on AoE-skills with a range of 1. Does not increase width of linear AoE-skills)."
    ],
    [
        "Синяя звезда",
        "Blue Star",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "Перед битвой АТК, ЗАЩ и МЗАЩ увеличиваются на 5% за каждую 1 пройденную клетку (до 15%).",
        "ATK, DEF and MDEF increase by 5% for every 1 block moved before battle (up to 15%)."
    ],
    [
        "Синяя луна",
        "Blue Moon",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ +10%, МЗАЩ +5%.",
        "INT +10%, MDEF +5%."
    ],
    [
        "Скипетр королевы",
        "Queen's Scepter",
        "weapon",
        "583",
        "",
        "85",
        "",
        "",
        "",
        "Когда ОЗ юнита выше 80%, ИНТ увеличивается на 15%.",
        "When unit HP is about 80%, INT increases by 15%."
    ],
    [
        "Соблазнительница Баттори",
        "Bathory, the Seductress",
        "weapon",
        "",
        "96",
        "",
        "",
        "",
        "54",
        "Крит увеличивается на 10%. После нанесения критического удара в бою наносит врагу фиксированный урон 1 раз (урон - 1х собственная АТК).",
        "Crit increases by 10%. After landing a critical hit in battle, deals fixed damage once to the enemy (damage = 1x own ATK)."
    ],
    [
        "Страж печати",
        "Seal Guardian",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "АТК +10%, ЗАЩ +5%.",
        "ATK +10%, DEF + 5%."
    ],
    [
        "Страж трона",
        "Throne Guardian",
        "weapon",
        "364",
        "118",
        "",
        "",
        "",
        "",
        "АТК +10%, ОЗ +5%.",
        "ATK +10%, HP +5%."
    ],
    [
        "Убийца демонов",
        "Demonslayer",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "АТК и Навык +8%. При нанесении критического урона снимает с врага 1 бафф и накладывает 1 дебафф.",
        "ATK and SKILL +8%. When attack results in a critical, dispels 1 enemy buff and apply 1 debuff."
    ],
    [
        "Цветок ночи",
        "Night Bloom",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ +10%. Рассеивает 1 дебафф, когда применяет навыки к союзным юнитам.",
        "INT +10%. Dispels 1 debuff whn casting skills on friendly units."
    ],
    [
        "Чистилище",
        "Purgatory",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ +5%. При нанесении урона враг получает фиксированный урон один раз (урон - 2хИНТ героя) в конце следующего хода.",
        "INT +5%. When attacking, at the end of the next turn the enemy takes the fixed damage once (Damage = 2x Hero's INT)."
    ],
    [
        "Чудесный посох",
        "Miracle Staff",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "Урон АоЕ навыка увеличивается на 15%. При нанесении урона есть 30% шанс получения врагом дебаффа.",
        "AoE skill damage increases by 15%. When dealing damage, there is 30% chance the enemy will receive a debuff."
    ],
    [
        "Экстремально магический лук",
        "Extreme Magic Bow",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "АТК +10%. Урон юнита в ближнем бою не снижается.",
        "ATK +10%. Unit's damage in not reduced in melee battles."
    ],
    [
        "Оружие2",
        "---",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "АТК +10%. Перед вступлением в бой, если ОЗ цели выше 80%, на врага будет наложен дебафф 'ЗАЩ -30%' на 1 ход.",
        "ATK +10%. Before entering battle, if the target's HP is above 80%, the enemy will be afflicted with the 'DEF -30%' debuff for 1 turn."
    ],
    [
        "Оружие 3",
        "---",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "ОЗ +5%. После применения навыка на враге, 100% шанс наложить 1 случайный дебафф.",
        "HP +5%. After using a skill on an enemy, there is a 100% chance to apply 1 random debuff."
    ]
]

function itemView (itemType) {
	var id = document.getElementById('item_data');
	id.innerHTML = '';
	//id.innerHTML = itemDat[111][8];
	var i;
	for (i=1;i<itemDat.length;i++){
		if (itemDat[i][2]==itemType){
			if (itemDat[i][3]!=''){var oz='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">ОЗ: ' + itemDat[i][3] + '</span>'}else{var oz=''};
			if (itemDat[i][4]!=''){var atk='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">АТК: ' + itemDat[i][4] + '</span>'}else{var atk=''};
			if (itemDat[i][5]!=''){var intt='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">ИНТ: ' + itemDat[i][5] + '</span>'}else{var intt=''};
			if (itemDat[i][6]!=''){var def='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">ЗАЩ: ' + itemDat[i][6] + '</span>'}else{var def=''};
			if (itemDat[i][7]!=''){var mdef='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">МЗАЩ: ' + itemDat[i][7] + '</span>'}else{var mdef=''};
			if (itemDat[i][8]!=''){var crit='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">НАВЫК: ' + itemDat[i][8] + '</span>'}else{var crit=''};
			id.innerHTML += '<div style="display:block;width:95%;height:140px;"><div style="display:block;width:150px;float:left;"><img src="images/itemIcons/all/' + itemDat[i][0] + 
			'.png" height="120px" /></div><div style="display:block;width:700px;float:left;"><b style="font-size: 23px;margin-right: 50px;float:left;">' + itemDat[i][0]+ 			'</b>' +
//			'<img src="images/Move_Walk.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][6] + 
//			'</span> <img src="images/Icon_Range.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][7] + 
//			'</span> <img src="images/icon.png" height="25px" />
			'<div style="display: block;float: left;padding-top: 4px;">'  + oz + ' ' + atk + ' ' + intt + ' ' + def + ' ' + mdef + ' ' + crit +
			'</div></div><br><br><div style="white-space: normal;"><span style="font-size:18px;font-style:italic;">' + itemDat[i][9]  + 
			'</div></div>';
		}
	}
}
