// itemDat.length  -  колл-во всех солдат
// sitemDat[0].length  -  колл-во элементов у солдат
// 0 - имя рус, 1 - имя англ., 2 - тип вещи, 3 - ОЗ, 4 - атк, 5 - инт, 6 - защ, 7 - мзащ, 8 - навык, 9 - описание рус, 10 - описание англ.
var itemDat = [
    [
        "Название (рус)",
        "Название (англ)",
        "Тип (weapon, body, hat, accessoir)",
        "ОЗ",
        "АТК",
        "ИНТ",
        "ЗАЩ",
        "МЗАЩ",
        "НАВЫК",
        "Описание начальное(рус)",
        "Описание начальное (англ)"
    ],
    [
        "Перо ангела",
        "Angel Feather",
        "accessoir",
        "",
        "",
        "6",
        "",
        "4",
        "",
        "ОЗ +2%. Эффекты исцеления +2%. Иммунитет к оглушению.",
        "HP +2%. Healing effects +2%. Grants immunity to stun."
    ],
    [
        "Апексовые сапоги",
        "Apex Boots",
        "accessoir",
        "",
        "6",
        "",
        "",
        "4",
        "",
        "АТК +1%. Мобильность +1.",
        "ATK +1%. Mobility +1."
    ],
    [
        "Ангел бедствия",
        "Apostle of doom",
        "accessoir",
        "",
        "6",
        "6",
        "",
        "",
        "",
        "АТК и ИНТ +1%. При активной атаке и вступлении в бой есть 50% шанс снизить случайный атрибут врага на 30% (кроме ОЗ). Длится 1 раунд. Если это несмешанная армия, этот эффект нельзя снять.",
        "ATK and INT +1%. When actively attacking and entering battle, there is a 50% chance to reduce a random enemy attribute by 30% (except HP). Lasts 1 round. If it's an unmixed army, this effect cannot be removed."
    ],
    [
        "Пакт крови",
        "Blood Pact",
        "accessoir",
        "73",
        "",
        "",
        "",
        "",
        "",
        "ОЗ +3%. Иммунитет к отмене исцеления и запрету на баффы.",
        "HP +3%. Grantes immunity to effects that prevent you from being healed or buffed."
    ],
    [
        "Кровопьющий шип",
        "Bloodthirsty Nail",
        "accessoir",
        "",
        "6",
        "",
        "4",
        "",
        "",
        "АТК +1,5%. Иммунитет к безмолвию активного умения.",
        "ATK +1,5%. Immune to active skill silence."
    ],
    [
        "Узы Араши",
        "Bond of Arashi",
        "accessoir",
        "29",
        "",
        "",
        "4",
        "",
        "",
        "Все характеристики +1%. Иммунитет к оглушению и безмолвию пассивного умения.",
        "All stats +1%. Immune to stun and passive skill silence."
    ],
    [
        "Ядро хитрости",
        "Core of Guile",
        "accessoir",
        "",
        "",
        "",
        "4",
        "4",
        "",
        "Все характеристики +1%. Когда втянуты в бой, ЗАЩ или МЗАЩ ( что ниже) увеличивается на 1%.",
        "All stats +1%. When forced into battle, DEF or MDEF (whichever is lower) increases by 1%."
    ],
    [
        "Ползучий прилив",
        "Creeping Tide",
        "accessoir",
        "29",
        "",
        "6",
        "",
        "",
        "",
        "ИНТ +1,5%. После атаки и нанесения урона 50% шанс снизить МЗАЩ врага на 20% на 1 ход.",
        "INT +1,5%. After attacking and dealing damage, 50% chance to reduse enemy's MDEF for 20% by 1 turn."
    ],
    [
        "Бриллиант измерения",
        "Dimensional Jewel",
        "accessoir",
        "29",
        "",
        "6",
        "",
        "",
        "",
        "ИНТ +1,5%. При активном нанесении урона навыком есть 15% шанс снизить перезарядку навыка на 1 ход.",
        "INT +1,5%. When attacking with a skill, 15% chance t reduce cooldown by 1"
    ],
    [
        "Божественные сапоги",
        "Divine Boots",
        "accessoir",
        "29",
        "",
        "",
        "4",
        "",
        "",
        "ЗАЩ +1,5%. Мобильность +1",
        "DEF +1,5%. Mobility +1."
    ],
    [
        "Драупнир",
        "Draupnir",
        "accessoir",
        "",
        "",
        "6",
        "",
        "4",
        "",
        "ИНТ +1,5%. Подвергнувшись дальней атаке, юнит отражает 10% полученного урона.",
        "INT +1,5%. When attacked with a ranged attack, reflects damage taken this time by 10%."
    ],
    [
        "Эльфийский пояс",
        "Elven Belt",
        "accessoir",
        "29",
        "",
        "",
        "4",
        "",
        "",
        "Когда подвергаетесь дальней атаке, ЗАЩ и МЗАЩ увеличиваются в бою на 2%.",
        "When attacked with a ranged attack, DEF and MDEF increase by 2% in battle."
    ],
    [
        "Эльфийское кольцо",
        "Elven Ring",
        "accessoir",
        "29",
        "6",
        "",
        "",
        "",
        "",
        "Когда атакуете, АТК и ЗАЩ увеличиваются на 1,5%.",
        "When attacking, ATK and DEF increase by 1,5%."
    ],
    [
        "Око смотрящего",
        "Eye of the Beholder",
        "accessoir",
        "",
        "",
        "6",
        "",
        "4",
        "",
        "ИНТ +1,5%. Когда атакуете, после боя дает 25% шанс снизить наносимый врагом урон на 15%. Длится 1 ход.",
        "INT +1,5%. When attacking, after battle, grants a 25% chance to reduce enemy's damage dealt to 15%. Lasts 1 turn."
    ],
    [
        "Пояс великана",
        "Giant Belt",
        "accessoir",
        "29",
        "",
        "",
        "4",
        "",
        "",
        "Когда подвергаетесь ближней атаке, ЗАЩ и МЗАЩ увеличиваются в бою на 2%.",
        "When attacked with a melee attack, DEF and MDEF increase by 2% in battle."
    ],
    [
        "Слеза богини",
        "Goddess Tear",
        "accessoir",
        "",
        "",
        "6",
        "",
        "4",
        "",
        "Эффекты исцеления +5%. После завершения действия снимает 1 дебафф с 1 дружественного юнита в радиусе 2 клеток.",
        "Healing effects +5%. After taking action, dispels 1 debuff from 1 nearby friendly unit within 2 blocks (not including this unit)."
    ],
    [
        "Сердце Геи",
        "Heart of Gaia",
        "accessoir",
        "",
        "6",
        "",
        "4",
        "",
        "",
        "Все статы увеличиваются на 1%. Иммунитет к ранящему проклятию (получаемое исцеление превращается в урон) и отмене исцеления (применяемое исцеление превращается в урон).",
        "All stats increase by 1%. Immune to Curse of Wounding (healing received is converted into damage) and Heal Reversal (healing applied is converted into damage)."
    ],
    [
        "Сердце искупления",
        "Heart of Redemption",
        "accessoir",
        "",
        "",
        "6",
        "",
        "4",
        "",
        "Эффекты исцеления +5%. Иммунитет к фиксированному урону.",
        "Healing effects +5%. Immune to fixed damage."
    ],
    [
        "Священный ковчег",
        "Holy Ark",
        "accessoir",
        "29",
        "",
        "",
        "",
        "4",
        "",
        "ОЗ +1,5%. Когда подвергаетесь ближней атаке, отражается 10% урона.",
        "HP +1,5%. When attacked with a melee attack, reflects 10% damage."
    ],
    [
        "Святой грааль",
        "Holy Grail",
        "accessoir",
        "",
        "",
        "6",
        "",
        "4",
        "",
        "ИНТ +1%. При нанесении урона восстанавливает 5% ОЗ остальным дружественным юнитам в радиусе 1 клетки после совершения действия.",
        "INT +1%. When dealing damage, restores 5% HP of other friendly unit 1 block adjacent to you after taking action."
    ],
    [
        "Святое кольцо",
        "Holy Ring",
        "accessoir",
        "",
        "",
        "6",
        "",
        "4",
        "",
        "ИНТ +1,5%. Иммунитет к безмолвию активного умения.",
        "INT +1,5%. Immune to active skill silence."
    ],
    [
        "Кулон заговора",
        "Insidious Pendant",
        "accessoir",
        "",
        "6",
        "",
        "",
        "",
        "3",
        "Все статы увеличиваются на 1%. При вступлении в бой крит увеличивается на 1%.",
        "All stats increase by 1%. When entering battle, crit increases by 1%."
    ],
    [
        "Талисман судьи",
        "Judge Talisman",
        "accessoir",
        "",
        "6",
        "",
        "4",
        "",
        "",
        "АТК +1,5%. В сражениях со святыми АТК увеличивается ещё на 4%.",
        "ATK +1,5%. When battling against Holy units, ATK increases by an extra 4%."
    ],
    [
        "Плюшевый Джаглер",
        "Jugler Plushy",
        "accessoir",
        "29",
        "",
        "6",
        "",
        "",
        "",
        "Эффект исцеления +3%. Если вы применяете навык поддержки на 1 юнита, эффект длится +1 ход.",
        "Heal effect +3%. When you use a single unit assist skill, the effect lasts +1 turn."
    ],
    [
        "Амулет короля",
        "King Amulet",
        "accessoir",
        "29",
        "",
        "",
        "4",
        "",
        "",
        "Если в радиусе 2 клеток есть союзник, ЗАЩ и МЗАЩ в бою увеличиваются на 2%.",
        "When a friendly unit is within 2 blocks, in battle, DEF and MDEF is increase by 2%."
    ],
    [
        "Закон созидания",
        "Law of Creation",
        "accessoir",
        "29",
        "",
        "6",
        "",
        "",
        "",
        "ИНТ +1,5%. При атаке и вступлении в бой, если используемый навык особо эффективен против врага, то герой наносит на 10% больше магического урона.",
        "INT +1,5%. When attacking and entering battle, if the skill used is super effective against the enemy hero, than the hero deals 10% increased magic damage."
    ],
    [
        "Браслет одинокой звезды",
        "Lone Star Armlet",
        "accessoir",
        "29",
        "6",
        "",
        "",
        "",
        "",
        "Если в радиусе 2 клеток нет союзников, АТК и ЗАЩ во время боя повышаются на 2%.",
        "When no friendly units within 2 blocks, ATK and DEF increase by 2% during combat."
    ],
    [
        "Значок повелителя",
        "Overlord Badge",
        "accessoir",
        "29",
        "6",
        "",
        "",
        "",
        "",
        "Все характеристики +1%. Иммунитет к снижению ЗАЩ и МЗАЩ, снижению АТК и ИНТ, снижению мобильности.",
        "All stats +1%. Grants immunity to DEF and MDEF reduction, ATK and INT reduction, mobility reduction."
    ],
    [
        "Сокровище узника",
        "Prisoner's Gear",
        "accessoir",
        "29",
        "6",
        "",
        "",
        "",
        "",
        "АТК +1,5%. В сражении с кавалерией АТК увеличивается дополнительно на 4%.",
        "ATK +1,5%. When battling against Cavalry, increases ATK by an additional 4%."
    ],
    [
        "Эмблема истребителя",
        "Slayer's Emblem",
        "accessoir",
        "29",
        "6",
        "",
        "",
        "",
        "",
        "АТК +1,5%. В боях против асов АТК увеличивается на 4%.",
        "ATK +1,5%. When battling against Fliers, ATK increases by extra 4%."
    ],
    [
        "Ботинки духа",
        "Spirit Boots",
        "accessoir",
        "29",
        "",
        "",
        "4",
        "",
        "",
        "ЗАЩ +1,5%. После атаки можно передвинуться ещё на 2 клетки.",
        "DEF +1,5%. Can move 2 blocks after attacking a target."
    ],
    [
        "Звёздные серьги",
        "Star Earring",
        "accessoir",
        "29",
        "",
        "6",
        "",
        "",
        "",
        "ИНТ +1,5%. В боях против лучников и убийц ЗАЩ увеличивается на 10%.",
        "INT +1,5%. When battling against Assassin and Archer DEF increases by 10%."
    ],
    [
        "Медаль кузнеца",
        "Swordsmith's Medal",
        "accessoir",
        "",
        "",
        "",
        "4",
        "4",
        "",
        "Все статы +1%. Иммунитет к фиксированному урону и эффектам, оглушающим активные навыки.",
        "All stats +1%. Immune to fixed damage and effects that silence active skills."
    ],
    [
        "Лезвие воспоминаний",
        "The Edge of Memories.",
        "accessoir",
        "",
        "6",
        "",
        "4",
        "",
        "",
        "АТК +1,5%. При атаке с умением, наносящим урон, есть 15% шанс снизить перезарядку этого умения на 1-2 хода случайно.",
        "ATK +1,5%. When entering battle with a damage-dealing skill, 15% chance to reduce that skill's cooldown by 1-2 at random."
    ],
    [
        "Ожерелье Тора",
        "Thor's Necklace",
        "accessoir",
        "",
        "6",
        "",
        "4",
        "",
        "",
        "АТК +1%. При инициировании боя может с 25% шансом нанести один раз фиксированный урон врагу после боя (урон - 1хАТК героя).",
        "ATK +1%. When initiating battle, has a 25% chance to deal fixed damage once to the enemy unit after battle. This damage is equal to 1x the hero's attack."
    ],
    [
        "Истинный крест",
        "True Cross",
        "accessoir",
        "29",
        "",
        "6",
        "",
        "",
        "",
        "Эффекты исцеления +3%. В боях против демонов и магов ИНТ, ЗАЩ и МЗАЩ увеличиваются на 10%.",
        "Healing effects +3%. When battling against Demons and Mages, INT, DEF and MDEF increase by 10%."
    ],
    [
        "Сумеречная звезда",
        "Twiight Star",
        "accessoir",
        "",
        "6",
        "6",
        "",
        "",
        "",
        "АТК и ИНТ +1%. Перед инициированием боя наносит фиксированный урон в 0,5хАТК или ИНТ (смотря, что ниже). Если вражеский юнит состоит из смешанных войск, он не получает иммунитет к наносимому в этот раз урону.",
        "ATK and INT +1%. Before initiating battle, deales fixed damage to the enemy 1 time, equal to 0,5x of hero's ATK of INT (whichever is lowest). If the enemy is formed of mixed units, they will not be unvulnerable to damage dealed this time."
    ],
    [
        "Пелена света",
        "Veil of Light",
        "accessoir",
        "29",
        "",
        "",
        "",
        "4",
        "",
        "МЗАЩ +1,5%.Иммунитет к снижению ЗАЩ и МЗАЩ.",
        "MDEF +1,5%. Immune to DEF and MDEF reduction."
    ],
    [
        "Роза Видара",
        "Vidar's Rose",
        "accessoir",
        "",
        "",
        "6",
        "",
        "4",
        "",
        "ИНТ +1,5%. При активном нанесении урона имеет 25% шанс снять с врага 1 бафф.",
        "INT +1,5%. When dealing damage on your turn is 25% chance to dispell 1 buff from the enemy."
    ],
    [
        "Крылатые щитки на голень",
        "Winged Shin Guards",
        "accessoir",
        "",
        "6",
        "",
        "4",
        "",
        "",
        "АТК +1,5%. Когда атакованы, ЗАЩ увеличивается на 2%.",
        "ATK +1,5%. When attacked, DEF increases by 2%."
    ],
    [
        "Крылья скрытого великолепия",
        "Wings of Hidden Splendor",
        "accessoir",
        "29",
        "6",
        "",
        "",
        "",
        "",
        "Все аттрибуты +1%. В конце действия, если герой не нанёс никакого урона, 100% шанс получить мобильность +2. Длится 1 раунд. (Если уже есть другое повышение мобильности, дает Мобильность +3)",
        "All attributes +1%. At the end of the action, if the hero has not dealt any damage, there is a 100% chance to gain +2 mobility. Lasts 1 round. (If there is already another mobility boost, gives Mobility +3)"
    ],
    [
        "Акс2",
        "---",
        "accessoir",
        "",
        "",
        "",
        "4",
        "4",
        "",
        "\"Все аттрибуты +5%. В начале раунда получает \"\"Иммунитет к 1 дебафу. Восстанавливает 20% ОЗ при срабатывании\"\". Не может быть снят\"",
        "\"All attributes +5%. At the beginning of the round, gains \"\"Immunity to 1 debuff. Restores 20% HP when triggered.\"\" Cannot be removed.\""
    ],
    [
        "Броня Энея",
        "Aeneas' Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ЗАЩ +2%, получаемый эффект исцеления +2%.",
        "DEF +2%. Received Heal Effect +2%."
    ],
    [
        "Боевая броня Эола",
        "Aeolus' Battle Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ОЗ и ЗАЩ +1%. Подвергнувшись дальней атаке с 10% шансом снижает весь получаемый вашим юнитом урон в этой битве на 30%.",
        "HP and DEF +1%. When under ranged attack, has a 10% chance to lower damage taken by your unit in this battle by 30%."
    ],
    [
        "Одеяния Альянса",
        "Alliance Robes",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ +2%. ЗАЩ и МЗАЩ героев увеличивается на 3%, если они не состоят из смешанных сил.",
        "HP +2%. Hero DEF and MDEF inrease by 3%, when not composed of mixed force."
    ],
    [
        "Древний доспех",
        "Ancient Plate Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "Защита повышается на 2%. Получаемый фиксированный урон снижается на 2%.",
        "DEF +2%. Fixed damage taken decreased by 2%."
    ],
    [
        "Таинственный боевой доспех",
        "Arcane Battlegarb",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ОЗ и МЗАЩ +1%. При инициировании атаки наносит фиксированный урон врагу после атаки (урон - 0,5хМЗАЩ героя).",
        "HP and MDEF +1%. When attacking, after battle deals fixed damage once to the enemy (Damage - 0,5x Hero's MDEF)."
    ],
    [
        "Костюм штурма",
        "Assault Suit",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ +1%. Когда атакуете, ЗАЩ и МЗАЩ увеличиваются на 2%.",
        "HP +1%. When attacking, increases DEF and MDEF by 2%."
    ],
    [
        "Лазаревая легенда",
        "Azure's Legend",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ +2%. Когда ОЗ выше 50%, ЗАЩ увеличивается на 2%. Когда ОЗ ниже 50%, МЗАЩ увеличивается на 2%.",
        "HP +2%. When unit HP is above 50%, DEF increases by 2%. When unit HP is below 50%, MDEF increases by 2%."
    ],
    [
        "Белая мантия Бальдра",
        "Baldr's White Robe",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "МЗАЩ +2%. Перед вынужденным вступлением в ближний бой с 10% шансом отменяет снижение урона в ближнем бою.",
        "MDEF +2%. Before being forced into battle through melee attack, 10% chance that the unit's damage will not e reduced in melee battle."
    ],
    [
        "Броня родовой магии",
        "Bloodline Magic Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ОЗ и ЗАЩ +1%. Подвергнувшись ближней атаке с 10% шансом снижает весь получаемый вашим юнитом урон в этой битве на 30%.",
        "HP and DEF +1%. When under melee attack, has a 10% chance to lower damage taken by your unit in this battle by 30%."
    ],
    [
        "Углеродная броня",
        "Carbon Fiber Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "Когда ОЗ юнита выше 50%, ЗАЩ и МЗАЩ увеличиваются на 1,5%. Когда ОЗ юнита ниже 50%, АТК и Навык увеличиваются на 1,5%.",
        "When unit HP is about 50%, DEF and MDEF increase by 1,5%. When unit HP is below 50%, ATK and SKILL increase by 1,5%."
    ],
    [
        "Плащ неповиновения",
        "Cloak of Defiance",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "ЗАЩ и МЗАЩ +1%. Перед вступлением в навязанный в результате дальней атаки бой наносит врагу фиксированный урон (Урон - 0,5х МЗАЩ заклинателя).",
        "DEF and MDEF +1%. When attacked with a range attack, deals fixed damage to enemy (damage = 0,5x Hero's MDEF)"
    ],
    [
        "Тёмная мантия",
        "Dark Robe",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ +1%. Когда подвергаетесь дальней атаке, ЗАЩ и МЗАЩ увеличиваются на 3%.",
        "HP +1%. When attacked with a range attack, DEF and MDEF increase by 3%."
    ],
    [
        "Мантия смерти",
        "Death's Robe",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "Крит снижается на 20%. Когда атакованы, с 15% шансом повышает получаемый врагом урон на 20%. Длится 2 хода.",
        "Chance of being criically hit is reduced by 20%. When attacked,15% chance to increase enemy's damage taken by 20%. Lasts 2 turn."
    ],
    [
        "Кожа ящерицы - демона",
        "Demon Lizard Skin",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ +2%. Когда атакованы, с 25% шансом накладывает один мощный дебафф.",
        "HP +2%. When attacked, 25% to deal one random debuff"
    ],
    [
        "Доспехи хранителя",
        "Forbidden Defender's Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ЗАЩ и МЗАЩ +1%. Когда вступает в навязанный бой, может с 10% шансом уменьшить урон, получаемый в этом бою, на 20%.",
        "DEF and MDEF +1%. When forced into battle, has a 10% chance to reduce unit damage taken in this battle by 20%."
    ],
    [
        "Броня пограничного авангарда",
        "Frontier Vangard Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ЗАЩ и МЗАЩ +1%. При обороне ЗАЩ и МЗАЩ увеличиваются еще на 2%.",
        "DEF and MDEF +1%. When guarding, DEF and MDEF increase by a futher 2%."
    ],
    [
        "Крылья Хугина",
        "Fujin's Wing",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ +1%. Будучи атакованным в ближнем бою, юнит получает +3% к ЗАЩ и МЗАЩ.",
        "HP +1%. When melee attacked, DEF and MDEF +3%."
    ],
    [
        "Броня Геи",
        "Gaea's Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "Когда атакованы, ЗАЩ увеличивается на 3%. При ОЗ больше 80% получаемый магический урон снижен на 2%.",
        "When attacked, DEF increases by 3%. When unit's HP is above 80%, Mdamage taken decreases by 2%."
    ],
    [
        "Галактический плащ",
        "Galaxy Cloak",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "МЗАЩ +2%, ОЗ +1%.",
        "MDEF +2%, HP +1%."
    ],
    [
        "Куртка горгульи",
        "Gargoyle Jacket",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ +1%. Когда атакованы, ЗАЩ увеличивается на 3%.",
        "HP +1%. When attacked, DEF increases by 3%."
    ],
    [
        "Решимость гиганта",
        "Giant's Resolve",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ЗАЩ +2%. Шанс получения крита -10%.",
        "DEF +2%. Chance of being critically hit -10%."
    ],
    [
        "Ряса Богини",
        "Goddess Dress",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "ЗАЩ +2%. Получаемый эффект исцеления +2%.",
        "DEF +2%. Received Heal Effect +2%."
    ],
    [
        "Охотничьи угодья",
        "Hunter King's Harness",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ и ЗАЩ +1%. При вступлении в бой, если НАВЫК выше, чем у противника, есть шанс 10% снижения получаемого урона на 20%.",
        "HP and DEF +1%. When entering battle, if the SKILL is higher than the enemy, there is a 10% chance of reducing damage taken by 20%."
    ],
    [
        "Последние обряды",
        "Last Rites",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "ЗАЩ +2%. Когда ОЗ этого юнита равно 100% снижает весь получаемый урон на 40%.",
        "DEF +2%. When HP of this unit is on 100%, lowers all damage taken by 40%."
    ],
    [
        "Зеркальная броня",
        "Mirror Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ОЗ и ЗАЩ +1%. Когда атакованы, наносит врагу фиксированный урон (Урон - 0,5х ЗАЩ заклинателя).",
        "HP and DEF +1%. Before attacked with a melee attack, deals fixed damage to enemy (damage - 0,5x Hero's DEF)"
    ],
    [
        "Жилет Короля обезьян",
        "Monkey King's Vest",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "Когда атакованы, АТК и крит увеличиваются на 3%.",
        "When attacked, ATK and Crit increase by 3%."
    ],
    [
        "Мрачные одеяния",
        "Nebulous Robe",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ +2%. При инициировании боя получаемый отраженный урон снижается на 10%.",
        "HP +2%. When initiating battle, reflect demage taken is reduced by 10%."
    ],
    [
        "Благородная броня",
        "Noble Armor",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ЗАЩ +2%. Уменьшает АоЕ урон на 10%.",
        "DEF +2%. Reduce AoE damage by 10%."
    ],
    [
        "Ритуал замешательства",
        "Ritual of Confusion",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "Получаемый АоЕ урон снижен на 3%, эффекты лечения +2%.",
        "AoE damage taken decreases by 3% and healing effects +2%."
    ],
    [
        "Сияющие латы",
        "Shimmering Battlesuit",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "Получаемый АоЕ урон снижен на 10%. Когда втянуты в бой, с 25% шансом снижает АТК и ИНТ врага на 20%. Длится 1 ход.",
        "AoE damage taken decreases by 10%. When forced into battle, 25% chance to reduce enemy's ATK and INT by 20% before battle. Lasts 1 turn."
    ],
    [
        "Мантия Теннио",
        "Tennyo's Robe",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "ОЗ +2%. Когда атакованы, с 15% шансом снимает с противника 1 бафф и накладывает 1 случайный дебафф.",
        "HP +2%. When attacked, 15% chance to dispel 1 enemy's buff and inflict 1 random debuff to the enemy."
    ],
    [
        "Новое одеяние жнеца",
        "The Reaper's New Clothes",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "Вероятность критического удара уменьшается на 20%. Вступая в навязанный бой, 15% шанс уменьшить наносимый противником урон на 20%. Длится 2 хода.",
        "Chance of being critically hit is redused by 20%. Before forced into battle, 15% chance to reduse enemy's damage dealt by 20%. Lasts 2 turn."
    ],
    [
        "Благословение Тиамат",
        "Tiamaat's Blessing",
        "body",
        "25",
        "",
        "",
        "6",
        "",
        "",
        "ОЗ и МЗАЩ +1%. Юниты получают на 20% меньше магического урона, когда у них Смешанные войска.",
        "HP and MDEF +1%. Unit takes 20% less Magic Damage when in mixed units."
    ],
    [
        "Сумеречный страж",
        "Twiight Guard",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "МЗАЩ +2%. Эффекты исцеления увеличиваются на 2%.",
        "MDEF +2%. Healing effect increased by 2%."
    ],
    [
        "Сумеречная броня",
        "Twilight Armor",
        "body",
        "29",
        "",
        "",
        "5",
        "",
        "",
        "МЗАЩ +1,5%, ЗАЩ +1,5%.",
        "MDEF +1,5%, DEF +1,5%."
    ],
    [
        "Броня2",
        "---",
        "body",
        "34",
        "",
        "",
        "5",
        "",
        "",
        "Если ОЗ юнита выше 50%, ЗАЩ и МЗАЩ +8%. Если ОЗ ниже 50%, сила исцеления и получаемое исцеление +8%.",
        "If the unit's HP is above 50%, DEF and MDEF +8%. If HP is below 50%, healing power and received healing +8%."
    ],
    [
        "Шлем Энея",
        "Aeneas' Helmet",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "ОЗ +2%, ЗАЩ +1%.",
        "HP +2%, DEF +1%."
    ],
    [
        "Шапка штурма",
        "Assault Headgear",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "ОЗ +1%. Когда атакуете, ЗАЩ и МЗАЩ увеличиваются на 2%.",
        "HP +1%. When attacking, increases DEF and MDEF by 2%."
    ],
    [
        "Благословение Коронет",
        "Benediction Coronet",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "ОЗ +2%. После совершения действия дает одному смежному союзному юниту иммунитет к превращению лечения в урон и запрету на баффы на 1 ход.",
        "HP +2%. After taking action, grants 1 adjacent ally 10% increased DEF and immunity to Curse of Wounding (converts healing received into damage) and buff block for 1 turn."
    ],
    [
        "Углеродный Шлем",
        "Carbon Fiber Helm",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "Когда ОЗ юнита выше 50%, ЗАЩ и МЗАЩ увеличиваются на 1,5%. Когда ОЗ юнита ниже 50%, АТК и Навык увеличиваются на 1,5%.",
        "When unit HP is above 50%, DEF and MDEF increase by 1,5%. When unit HP is below 50%, ATK and SKILL increase 1,5%."
    ],
    [
        "Харон",
        "Charon",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "ЗАЩ +2%. В конце хода есть 25% шанс на увеличение всего получаемого урона на 15% у 1 врага в радиусе 3 клеток. Длится 1 ход.",
        "DEF +2%. After taking action has a 25% chance to increase all damage received by 15% for 1 enemy within 3 blocks. Lasts 1 turn."
    ],
    [
        "Шлем правителя",
        "Chief's Helmet",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "ОЗ +2%. После совершения действия дает одному смежному союзному юниту (не себе) дополнительно 10% ЗАЩ и запрещает эффекты снижения ЗАЩ, МЗАЩ и запрета на исцеление на 1 ход.",
        "HP+2%. After taking action grants 1 adjacent ally (not including this unit) 10% extra DEF and negates DEF and MDEF reduction effects and effects that prevent them from being healed for 1 turn."
    ],
    [
        "Тёмная корона",
        "Dark Crown",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "МЗАЩ +2%, ОЗ +1%.",
        "MDEF +2%, HP +1%."
    ],
    [
        "Взгляд демона дракона",
        "Demon Dragon's Gaze",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "ОЗ +1%. Когда герой вынужден вступить в бой под дальней атакой, ЗАЩ +3%.",
        "HP +1%. When forced into battle by a ranged attack, Hero DEF increses by 3%."
    ],
    [
        "Вестник Судного дня",
        "Doomsday Herald",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "МЗАЩ +2%, После совершения действия может с 25% шансом наложить на 1 вражеского юнита в пределах 2 клеток запрет на получение лечения. Длится 1 ход.",
        "MDEF +2%. After taking action has a 25% chance to render 1 enemy unit within 2 blocks unable to receive healing. Lasts 1 turn."
    ],
    [
        "Повелитель разрядов",
        "Electric Headwear",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "ОЗ+2%. После совершения действия, если рядом стоит союзник, наносит на 10% больше урон контратаки и получает иммунитет к перемещению на 1 ход.",
        "HP +2%. After taking action, if another friendly unit is adjacent, then both the hero and 1 adjacent friendly unit deal 10% increased counterattack damage and gain immunity for displacement for 1 turn."
    ],
    [
        "Шляпа с цветком",
        "Flower Boon Bonnet",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "ОЗ +2%. После совершения действия, если ОЗ юнита меньше 50%, исцеляет 20% ОЗ.",
        "HP+2%. After taking action, if this unit HP is below than 50%, heals 20% of HP."
    ],
    [
        "Корона ледяного пламени",
        "Frostfire Crown",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "МЗАЩ +2%. При инициировании боя полученный урон снижается на 2%.",
        "MDEF +2%. When initiating battle, damage taken is reduces by 2%."
    ],
    [
        "Ярость Тюра",
        "Fury of Tyr",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "ЗАЩ +2%. Если после совершения действия вы не нанесли урон, урон навыка повышается на 2%, урон контратаки повышается на 2% на 1 ход.",
        "DEF +2%. After taking action, if you haven't dealt damage, skill damage is increased by 2% and counterattack damage increases by 2% for 1 turn."
    ],
    [
        "Шлем Геи",
        "Gaea's Helmet",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "Когда атакованы, МЗАЩ +3%. При ОЗ выше 80% получаемый физический урон снижен на 2%.",
        "When attacked, MDEF increases by 3%. When unit HP is above 80%, physical damage taken is reduced by 2%."
    ],
    [
        "Сияние мира",
        "Glory of the World",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "ОЗ +2%. Перед тем, как быть втянутым в бой, восстанавливает 10% ОЗ цели, если юнит состоит из смешанного войска. Блокирует смертельные удары, вызванные фиксированным уроном (активируется только 1 раз за бой).",
        "HP +2%. Before being forced into battle, heals 10% of HP if unit is formed of mixed units. Blocks fatal strikes caused by fixed damage (only triggers 1 time per battle)."
    ],
    [
        "Око Ермунганда",
        "Jormungandr's Eye",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "ОЗ и ЗАЩ +1%. После завершения действия есть 25% шанс на снижение наносимого урона на 15% у 1 врага в радиусе 2 клеток. Длится 1 ход.",
        "HP and Def +1%. After taking action, 25% chance to decrease damage dealt by 15% for 1 enemy within 2 blocks. Lasts 1 turn."
    ],
    [
        "Королевская корона",
        "King's Crown",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "ОЗ и МЗАЩ +1%. После завершения действия дает 1 смежному союзному юниту (не себе) 10% дополнительного урона на 1 ход.",
        "HP and MDEF +1%. After taking damage, grants 1 adjacent friendly unit (not including this unit) 10% extra damage for 1 turn)."
    ],
    [
        "Маска Локи",
        "Loki's Mask",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "ОЗ +1%. Когда подвергаетесь ближней атаке, ЗАЩ увеличивается на 3%.",
        "HP +1%. When attacked with a melee attack, DEF increases by 3%."
    ],
    [
        "Перьевая корона Ньорда",
        "Njord's Feathered Crown",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "ОЗ +2%. В битвах против юнитов с меньшим ОЗ ЗАЩ и МЗАЩ увеличиваются на 3%.",
        "HP +2%. When battling unit with les HP, DEF and MDEF increase by 3%."
    ],
    [
        "Боевой шлем Одина",
        "Odin's Battle Helm",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "МЗАЩ +2%. В случае уничтожения врага на этом ходу снимает 1 бафф с 1 врага в радиусе 3 клеток после совершения действия.",
        "MDEF +2%. When eliminating an enemy on this turn, dispels 1 buff from 1 enemy within 3 blocks after taking action."
    ],
    [
        "Дыхание жнеца",
        "Reaper Breath",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "ОЗ +2%. Уничтожив врага на этом ходу, после завершения действия наносит один фиксированный урон по врагам в радиусе 2 клеток (урон - 10% от максимального ОЗ).",
        "HP +2%. When eliminating enemy on this turn, after taking action, deals fixed damage once to enemies within 2 blocks at the end of your next turn (damage = 10% of max HP)."
    ],
    [
        "Шлем Виндлера",
        "Rigel Helm",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "ОЗ +2%. Урон контратаки +3% при защите союзников.",
        "HP +2%. Increases counterattack damage by 3% when guarding allies."
    ],
    [
        "Снежная шапочка",
        "Snow Beanie",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "ОЗ +2%. При нападении и принуждении к битве 25% шанс увеличить ЗАЩ на 20%.",
        "HP +2%. When attacked and forced into battle, 25% to increase DEF by 20%."
    ],
    [
        "Головной убор похитителя душ",
        "Soul Stealer Headdress",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "МЗАЩ +2%. После завершения действия с 25% шансом деактивирует активные навыки 1 врага в радиусе 3 клеток. Длится 1 ход.",
        "MDEF +2%. After taking action, 25% chance to silence active skills of 1 enemy within 3 blocks. Lasts 1 turn."
    ],
    [
        "Завеса звезд",
        "Star crown",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "ОЗ +2%. Если ОЗ юнита >80%, после исцеления другими дружественными войсками, получает 'урон умений увеличен на 2%' и 'АТК +2%', длится 1 раунд.",
        "HP +2%. If a unit's HP >80%, after being healed by other friendly units, receives 'skill damage increased by 2%' and 'ATK +2%', lasts 1 round."
    ],
    [
        "Головной убор Теннио",
        "Tennyo's Headdress",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "ОЗ +2%. После совершения действия с 50% шансом накладывает 1 случайный бафф на 1 союзника в радиусе 2 клеток.",
        "HP +2%. After taking action, 50% chance to grant 1 random buff to 1 friendly unit within 2 blocks (not including this unit)."
    ],
    [
        "Тиара",
        "Tiara",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "Когда у юнита 100% ОЗ, ЗАЩ и МЗАЩ увеличиваются на 3%.",
        "When unit HP is at 100%, MDEF and DEF increase by 3%."
    ],
    [
        "Сумеречный шлем",
        "Twilight Helmet",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "МЗАЩ +1,5%, ЗАЩ +1,5%.",
        "MDEF +1,5%, DEF +1,5%."
    ],
    [
        "Меховые наушники",
        "Utlimate Ear Muffs",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "ОЗ +2%. После совершения действия 1 расположенного рядом союзника получать на 15% меньше урона и дает иммунитет к фиксированному урону. Длится 1 ход.",
        "HP +2%. After taking action makes 1 adjacent ally take 15% less damage and become immune to fixed damage for 1 turn."
    ],
    [
        "Маска вампира",
        "Vampire's Mask",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "ЗАЩ +2%. После совершения действия может с 25% шансом снизить ЗАЩ 1 врага в радиусе 2 клеток на 20%. Длится 1 ход.",
        "DEF +2%. After taking action has a 25% chance to reduce the DEF of 1 enemy within 2 blocks by 20%. Lasts 1 turn."
    ],
    [
        "Крылатый шлем сумерек",
        "Winged Helm of Twilight",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "ОЗ +2%. Перед активным вступлением в бой, добавляет к ЗАЩ или МЗАЩ (смотря какой ниже) 8% аттрибуты который выше.",
        "Before actively entering battle, adds 8% of the higher attribute of DEF or MDEF to lower."
    ],
    [
        "Отголосок ведьмы",
        "Witch's Reminiscence",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "ОЗ +2%. После совершения действия НАВЫК 1 ближайшего союзного юнита увеличивается на 10%. Получает иммунитет к отмене исцеления (получаемое исцеление превращается в урон) и эффектам, запрещающим Повторное действие на 1 ход.",
        "HP +2%. After taking action, increses SKILL of 1 nearby friendly unit by 10%. Grants immunity to heal reversal (healing dealt is converted into damage) and effectsthat stop you from acting again for 1 turn."
    ],
    [
        "Гнев Иерофанта",
        "Wrath of the Hierophant",
        "hat",
        "34",
        "",
        "",
        "",
        "4",
        "",
        "ОЗ +2%. Когда атакован, АТК увеличивается на 1,5%.",
        "HP +2%. When attacked, ATK increases by 1,5%."
    ],
    [
        "Венок Иггдрасиля",
        "Yggdrasil Wreath",
        "hat",
        "21",
        "",
        "",
        "",
        "6",
        "",
        "ОЗ+2%. После совершения действия дает одному союзнику рядом (не себе) 10% дополнительной МЗАЩ, а также иммунитет к оглушению, блокированию баффов и замедлению на 1 ход.",
        "HP +2%. After taking action, grants 1 friendly unit near you (not including this unit) 10% extra MDEF and negates stun, buff block and speed decrease effects for 1 turn."
    ],
    [
        "Шлем2",
        "---",
        "hat",
        "25",
        "",
        "",
        "",
        "5",
        "",
        "\"ОЗ +10%. Если в конце действия в пределах 2 блоков нет врагов, получает \"\"Урон умений увеличивается на 5%\"\" и \"\"АоЕ урон увеличивается на 10%\"\", длится 1 ход.\"",
        "\"HP +10%. If at the end of the action there are no enemies within 2 blocks, receives \"\"Skill damage increased by 5%\"\" and \"\"AoE damage increased by 10%\"\", lasts 1 turn.\""
    ],
    [
        "Меч клятвы",
        "Allegiance Blade",
        "weapon",
        "25",
        "9",
        "",
        "",
        "",
        "",
        "АТК и ЗАЩ +1%. При наличии классового преимущества, АТК и ЗАЩ +1%.",
        "ATK and DEF +1%. If you have a class advantage, ATK and DEF +1%."
    ],
    [
        "Астарот",
        "Astaroth",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "Во время боя с врагами, пораженными дебаффами, ИНТ увеличивается на 3%. Перед атакой, с 15% шансом оглушает врага после боя. Длится 1 ход.",
        "When battling enemies afflicted by debuff, INT increases by 3%. When attacking, 15% chance to stun the enemy after battle. Lasts 1 turn"
    ],
    [
        "Сбалансированный клинок",
        "Balanced Blade",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "ЗАЩ и МЗАЩ +1%. Дальность действия АоЕ - навыков +1. (Не может быть использовано с навыками дальностью 1. Не увеличивает ширину линейных АоЕ навыков).",
        "DEF and MDEF +1%. AoE - skill effective range +1. (Cannot be used on AoE-skills with a range of 1. Does not increase width of linear AoE-skills)."
    ],
    [
        "Соблазнительница Баттори",
        "Bathory, the Seductress",
        "weapon",
        "",
        "8",
        "",
        "",
        "",
        "5",
        "Крит увеличивается на 2%. После нанесения критического удара в бою наносит врагу фиксированный урон 1 раз (урон - 0,5х собственная АТК).",
        "Crit increases by 2%. After landing a critical hit in battle, deals fixed damage once to the enemy (damage = 0,5x own ATK)."
    ],
    [
        "Кровавый меч Хрунтинг",
        "Blood Sword Hrunting",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "АТК +1%. После активного нанесения урона с 50% шансом наносит дополнительный фиксированный урон (урон - 0,5хАТК героя).",
        "ATK +1%. Has 50% chance to deal extra fixed damage after actively dealing damage (Damage = 0,5x Hero's ATK)."
    ],
    [
        "Кровавая мелодия",
        "Bloody Melody",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "АТК +2%, ЗАЩ +1%.",
        "ATK +2%, DEF + 1%."
    ],
    [
        "Синяя луна",
        "Blue Moon",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "ИНТ +2%, МЗАЩ +1%.",
        "INT +2%, MDEF +1%."
    ],
    [
        "Синяя звезда",
        "Blue Star",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "Перед битвой АТК, ЗАЩ и МЗАЩ увеличиваются на 1% за каждую 1 пройденную клетку (до 3%).",
        "ATK, DEF and MDEF increase by 1% for every 1 block moved before battle (up to 3%)."
    ],
    [
        "Костедробящий молот",
        "Bone-Crusher's Hammer",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "АТК +2%. Перед вступлением в инициированный бой сводит на нет все навыки вражеской брони (кроме эффектов от максимального ОЗ). Если цель - герой, не являющийся игроком, то эффект вместо этого снизит ЗАЩ на 15% на 1 ход.",
        "ATK +2%. When initiating battle and before battle, nullifies all enemy armor skill (aside from max HP effects). If the target is a non-player hero, the effect will instead reduce DEF by 15%. Lasts 1 turn."
    ],
    [
        "Разбитая звезда",
        "Broken Star",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "АТК +2%, ЗАЩ +1%.",
        "ATK+2%, DEF+1%."
    ],
    [
        "Копье Разрушителя заряда",
        "Charge Breaker Spear",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "АТК +2%. При вынужденном вступлении в бой, ЗАЩ увеличивается на 2% за каждый перемещенную противником клетку (до 10%).",
        "ATK +2%. When forced into battle, DEF increases by 2% for each cell moved by the enemy (up to 10%)."
    ],
    [
        "Кристальное жало",
        "Crystal Stinger",
        "weapon",
        "",
        "8",
        "",
        "",
        "",
        "4",
        "Крит шанс и крит урон увеличиваются на 2%. Если перед боем ваш Навык выше, чем у врага, в этом бою вы игнорируете 10% ЗАЩ врага.",
        "Crit and Crit damage increased by 2%. If your SKILL is higher then the enemy's before battle, you ignore 10% of enemy's DEF in this battle."
    ],
    [
        "Проклятое копье",
        "Cursed Lance",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "Когда атакуете, ЗАЩ увеличивается на 3%, МЗАЩ увеличивается на 3%. После боя с 25% деактивирует активные навыки врагов, не давая им исцелиться. Длится 1 ход.",
        "When attacking, DEF and MDEF +3%. After battle, 25% chance to silence enemy's active skills and prevent them from being healed. Lasts 1 turn."
    ],
    [
        "Убийца демонов",
        "Demonslayer",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "АТК и Навык +1,5%. При нанесении критического урона снимает с врага 1 бафф и накладывает 1 дебафф.",
        "ATK and SKILL +1,5%. When attack results in a critical, dispels 1 enemy buff and apply 1 debuff."
    ],
    [
        "Дьявольский топор",
        "Devil Axe",
        "weapon",
        "21",
        "10",
        "",
        "",
        "",
        "",
        "ОЗ +1%, АТК +1%. Когда атакуете, наносит врагу фиксированный урон один раз (урон - 0,5хАТК героя) после боя.",
        "HP +1%, ATK +1%. When attacking, after battle deals fixed damage once to the enemy (damage = 0,5x Hero's ATK)."
    ],
    [
        "Драконоборец Грам",
        "Dragonslayer Gram",
        "weapon",
        "25",
        "9",
        "",
        "",
        "",
        "",
        "АТК и ОЗ +1,5%. В битвах против драконов АТК, ЗАЩ и МЗАЩ увеличиваются на 10%.",
        "ATK and HP +1,5%. When battling against dragons, ATK, DEF and MDEF is increase by 10%."
    ],
    [
        "Экстремально магический лук",
        "Extreme Magic Bow",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "АТК +2%. Урон юнита в ближнем бою не снижается.",
        "ATK +2%. Unit's damage in not reduced in melee battles."
    ],
    [
        "Метёлка из перьев",
        "Feather Duster",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "Наносимый урон снижается на 20%. Дальность обычной атаки героя +1.",
        "Reduced damage dealt by 20%. Hero's normal attack range +1."
    ],
    [
        "Морозное лезвие",
        "Frostrend",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "АТК +2%. Когда атакуете, с 25% шансом снижает мобильность врага на 2 клетки после боя. Длится 1 ход после боя.",
        "ATK +2%. When attacking, 25% chance to reduce enemy's mobility by 2 blocks after battle. Lasts 1 turn."
    ],
    [
        "Врата истины",
        "Gate of Truth",
        "weapon",
        "34",
        "",
        "7",
        "",
        "",
        "",
        "Когда атакуете, увеличивает ИНТ, ЗАЩ, и МЗАЩ на 3%.",
        "When attacking, increases iNT, DEF and MDEF by 3%."
    ],
    [
        "Дар вечной жизни",
        "Gift of Eternal Life",
        "weapon",
        "34",
        "",
        "7",
        "",
        "",
        "",
        "ИНТ +1%. После атаки исцеляет дружеского юнита с наименьшим ОЗ (1,5х ИНТ заклинателя).",
        "INT +1%. When attacking,after battle heals friendly unit with the lowest HP (1,5x caster's INT)."
    ],
    [
        "Левая рука богини",
        "Goddess's Left Hand",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "Эффекты исцеления +3%. Когда атакуете, с 50% шансом снижает мобильность врага на 2 клетки после боя. Длится 1 ход.",
        "Healing Effects +3%. When attacking, after battle grants a 50% chance to reduce enemy's mobility by 2 blocks. Lasts 1 turn."
    ],
    [
        "Очищение сердца",
        "Heart Cleance",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "ИНТ +2%. При инициировании боя имеет 50% шанс наложить запрет баффов на 1 ход.",
        "INT +2%. When actively entering battle, has a 50% chance of preventing enemy from receiving buffs for 1 turn."
    ],
    [
        "Лук гидры",
        "Hydra's Bow",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "АТК +2%. Перед атакой с 25% шансом уменьшает наносимый врагом урон на 20%. Длится 1 ход.",
        "ATK +2%. Before attacking, 25% chance to reduce enemy's damage dealt by 20%. Last 1 turn."
    ],
    [
        "Последний рыцарь",
        "Last Knight",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "АТК +2%. Когда атакуете, с 25% шансом снижает АТК и ИНТ врага на 20%. Длится 1 ход.",
        "ATK +2%. When attackng, 25% to reduce enemy's ATK and INT by 20%. Lasts 1 turn."
    ],
    [
        "Жало скрытня",
        "Lurker's Sting",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "Шанс критического удара +2%, ОЗ +1%. Если перемещается меньше 3 блоков, получает +1 дальность действия при использовании навыка физического урона для вступления в бой.",
        "Crit chance +2%, HP +1%. If moving fewer than 3 blocks, gains +1 unit range when using a physical damage skill to enter battle."
    ],
    [
        "Молот Мимира",
        "Mimir's War-axe",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "АТК +2%. Атаковав и убив врага, или потеряв союзника, вы можете снять с себя 1 дебафф и восстановить 10% ОЗ, при этом получая +10% к урону героя в течение 1 хода.",
        "ATK +2%. After attacking and killing an enemy, or whenever the ally dies, dispel 1 debuff from youself and restore 10% HP, while also gaining Hero Damage +10% for 1 turn."
    ],
    [
        "Чудесный посох",
        "Miracle Staff",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "Урон АоЕ навыка увеличивается на 3%. При нанесении урона есть 15% шанс получения врагом дебаффа.",
        "AoE skill damage increases by 3%. When dealing damage, there is 15% chance the enemy will receive a debuff."
    ],
    [
        "Омела",
        "Mistletoe",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "Эффекты исцеления +3%. Когда атакуете, наносимый врагом урон снижается на 10% после боя. Длится 1 ход.",
        "Healing effects +3%. When attacking, after battle enemy's damage dealt decreases by 10%. Lasts 1 turn."
    ],
    [
        "Мьельнир",
        "Mjolnir",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "АТК +2%. Перед атакой с 50% шансом снимает с врага 1 бафф.",
        "ATK +2%. Before attacking, 50% chance to dispel 1 buff from the enemy."
    ],
    [
        "Цветок ночи",
        "Night Bloom",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "ИНТ +2%. Рассеивает 1 дебафф, когда применяет навыки к союзным юнитам.",
        "INT +2%. Dispels 1 debuff whn casting skills on friendly units."
    ],
    [
        "Козодой",
        "Nighthawk",
        "weapon",
        "",
        "8",
        "",
        "",
        "",
        "5",
        "АТК +2%, МЗАЩ +1%.",
        "ATK +2%, MDEF +1%."
    ],
    [
        "Клятва справедливости",
        "Oath of Justice",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "ЗАЩ +1,5%, МЗАЩ +1,5%.",
        "DEF +1,5%, MDEF +1,5%."
    ],
    [
        "Посох Олвера",
        "Olver's Staff",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "Эффекты исцеления +3%. Когда атакуете, после боя дает 25% шанс на увеличение получаемого врагом урона на 10%. Длится 1 ход.",
        "Healing effects +3%. When attacking, after battle grants a 25% chance to increases enemy's damage taken by 10%. Lasts 1 turn."
    ],
    [
        "Блеклый посох",
        "Pale Staff",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "Урон увеличивается на 3% при использовании навыка, поражающего одну цель. После активного вступления в битву с 25% шансом накладывает на врага дебафф Уязвимость. Длится 1 ход.",
        "Damage increases by 3% when casting single-target skills. When actively entering battle, has 25% chance of afflicting the enemy with a random debuff. Lasts for 1 turn."
    ],
    [
        "Миротворец",
        "Peacemaker",
        "weapon",
        "21",
        "10",
        "",
        "",
        "",
        "",
        "АТК +2%. Перед атакой с 25% шансом отключает пассивные навыки врага. Длится 2 хода.",
        "ATK +2%. Before attacking, 25% chance to nullify enemy's passive skills. Lasts 2 turns."
    ],
    [
        "Призмовый разрушитель",
        "Prismatic Destroyer",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "АТК +2%, урон по площади +2%.",
        "ATK +2%, AoE damage +2%."
    ],
    [
        "Чистилище",
        "Purgatory",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "ИНТ +1%. При нанесении урона враг получает фиксированный урон один раз (урон - 1хИНТ героя) в конце следующего хода.",
        "INT +1%. When attacking, at the end of the next turn the enemy takes the fixed damage once (Damage = 1x Hero's INT)."
    ],
    [
        "Скипетр королевы",
        "Queen's Scepter",
        "weapon",
        "34",
        "",
        "7",
        "",
        "",
        "",
        "Когда ОЗ юнита выше 80%, ИНТ увеличивается на 3%.",
        "When unit HP is about 80%, INT increases by 3%."
    ],
    [
        "Рагнарёк",
        "Ragnarok",
        "weapon",
        "21",
        "10",
        "",
        "",
        "",
        "",
        "АТК +2%. Перед атакой с 50% шансом наносит врагу фиксированный урон один раз (урон - 1хАТК героя)",
        "ATK +2%. Before attacking, 50% chance to deal fixed damage once to the enemy (damage = 1x Hero's ATK)."
    ],
    [
        "Красная луна",
        "Red Moon",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "ИНТ +2%, ОЗ +1%.",
        "INT +2%, HP +1%."
    ],
    [
        "Копье сокрушения",
        "Routing Light",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "АТК +2%. Наносимый урон увеличивается на 2% за каждую клетку, пройденную до инициирования боя (до 10%). При прохождении 3 и более клеток враг не сможет применять эффект стража в течение 1 хода после боя.",
        "ATK +2%. Damage dealt is increased by 2% for each block, moved before initiating battle (up to 10%). When moving 3 or more blocks, the enemy's Guard is disabled for 1 turn after battle."
    ],
    [
        "Алый жнец",
        "Scarlet Reaper",
        "weapon",
        "21",
        "10",
        "",
        "",
        "",
        "",
        "АТК +2%, Если перед активным нанесением урона ОЗ врага меньше 100%, то наносимый урон в этот раз повышается на 1%, а после нанесения урона наносит фиксированный урон, равный АТК героя х0,5 1 раз.",
        "ATK +2%. Before actively dealing damage, if the enemy's HP is less then 100%, damage dealt this time is increased by 1%, and after dealing damage, deals fixed damage 1 time equal to Hero's ATKx0,5."
    ],
    [
        "Божественный скипетр",
        "Scepter of Divinity",
        "weapon",
        "25",
        "",
        "9",
        "",
        "",
        "",
        "ОЗ +1%. Когда юнит находится на местности без бонуса к защите и использует дальние навыки для иницирования боя, его дальность увеличивается на 1 (этот эффект перекрывает эффект, который игнорирует снижение ближнего урона)",
        "HP +1%. When on terrain with no defensive bonus and using ranged skills to initiate battle, unit range is increased by 1. (Skills that ignored melee penalty override this effect)."
    ],
    [
        "Страж печати",
        "Seal Guardian",
        "weapon",
        "25",
        "9",
        "",
        "",
        "",
        "",
        "АТК +2%, ЗАЩ +1%.",
        "ATK +2%, DEF + 1%."
    ],
    [
        "Печать бури",
        "Sigil of Storms",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "ЗАЩ +2%. Вступая в ближний бой, есть 50% шанс нанести врагу один раз фиксированный урон, равный 1хЗАЩ героя.",
        "DEF +2%. Before initiating battle with a melee attack, has 50% chance to deal fixed damage once to the enemy equal to 1x Hero's DEF."
    ],
    [
        "Дух печали",
        "Spirit Griever",
        "weapon",
        "",
        "8",
        "",
        "",
        "",
        "5",
        "Когда атакуете, увеличивает крит на 3% и уменьшает получаемый урон на 10%.",
        "When attacking, increases Crit by 3% and reduses damage taken by 10%."
    ],
    [
        "Страж трона",
        "Throne Guardian",
        "weapon",
        "21",
        "10",
        "",
        "",
        "",
        "",
        "АТК +2%, ОЗ +1%.",
        "ATK +2%, HP +1%."
    ],
    [
        "Лук Уллра",
        "Ullr's Bow",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "Физический урон снижен на 20%. Дальность юнита увеличивается на 1.",
        "Physical damage decreases by 20%. Unit range increases by 1."
    ],
    [
        "Рыцарь ветра",
        "Unstoppable Knight",
        "weapon",
        "25",
        "9",
        "",
        "",
        "",
        "",
        "АТК +2%. Когда инициирует бой против врага, имеющего 100% ОЗ, АТК, ЗАЩ и МЗАЩ юнита увеличиваются на 5%.",
        "ATK +2%. When initiating battle against the enemy that has 100% HP, ATK, DEF and MDEF increase by 5%."
    ],
    [
        "Кинжал режущий ветер",
        "Wind Cutter Dagger",
        "weapon",
        "",
        "8",
        "",
        "",
        "",
        "5",
        "АТК +2%. При инициировании боя дает 25% шанс на снижение ЗАЩ врага на 20% после боя. Длится 1 ход.",
        "ATK +2%. When initiating battle, has a 25% chance to reduce the enemy's DEF by 20% after battle. Lasts 1 turn."
    ],
    [
        "Ветвь Иггдрасиля",
        "Yggdrasil Branch",
        "weapon",
        "34",
        "7",
        "",
        "",
        "",
        "",
        "ЗАЩ +2%. В бою игнорирует 3% ЗАЩ врага.",
        "DEF +2%. In battle, ignores 3% of enemy's DEF."
    ],
    [
        "Оружие2",
        "---",
        "weapon",
        "",
        "9",
        "",
        "",
        "",
        "4",
        "\"АТК +10%. Перед вступлением в бой, если ОЗ цели выше 80%, на врага будет наложен дебафф \"\"ЗАЩ -30%\"\" на 1 ход.\"",
        "\"ATK +10%. Before entering battle, if the target's HP is above 80%, the enemy will be afflicted with the \"\"DEF -30%\"\" debuff for 1 turn.\""
    ]
]

function itemView (itemType) {
	var id = document.getElementById('item_data');
	id.innerHTML = '';
	//id.innerHTML = itemDat[111][8];
	var i;
	for (i=1;i<itemDat.length;i++){
		if (itemDat[i][2]==itemType){
			if (itemDat[i][3]!=''){var oz='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">HP: ' + itemDat[i][3] + '</span>'}else{var oz=''};
			if (itemDat[i][4]!=''){var atk='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">ATK: ' + itemDat[i][4] + '</span>'}else{var atk=''};
			if (itemDat[i][5]!=''){var intt='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">INT: ' + itemDat[i][5] + '</span>'}else{var intt=''};
			if (itemDat[i][6]!=''){var def='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">DEF: ' + itemDat[i][6] + '</span>'}else{var def=''};
			if (itemDat[i][7]!=''){var mdef='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">MDEF: ' + itemDat[i][7] + '</span>'}else{var mdef=''};
			if (itemDat[i][8]!=''){var crit='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">SKILL: ' + itemDat[i][8] + '</span>'}else{var crit=''};
			id.innerHTML += '<div style="display:block;width:95%;height:140px;"><div style="display:block;width:150px;float:left;"><img src="images/itemIcons/all/' + itemDat[i][0] + 
			'.png" height="120px" /></div><div style="display:block;width:700px;float:left;"><b style="font-size: 23px;margin-right: 50px;float:left;">' + itemDat[i][1]+ 			'</b>' +
//			'<img src="images/Move_Walk.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][6] + 
//			'</span> <img src="images/Icon_Range.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][7] + 
//			'</span> <img src="images/icon.png" height="25px" />
			'<div style="display: block;float: left;padding-top: 4px;">'  + oz + ' ' + atk + ' ' + intt + ' ' + def + ' ' + mdef + ' ' + crit +
			'</div></div><br><br><div style="white-space: normal;"><span style="font-size:18px;font-style:italic;">' + itemDat[i][10]  + 
			'</div></div>';
		}
	}
}
