// PerspersItemDat.length  -  колл-во всех солдат
// PerspersItemDat[0].length  -  колл-во элементов у солдат
// 0 - имя героя рус, 1 - имя героя англ, 2 - имя рус, 3 - имя англ., 4 - тип вещи, 5 - ОЗ, 6 - атк, 7 - инт, 8 - защ, 9 - мзащ, 10 - навык, 11 - описание рус, 12 - описание англ.

var persItemDat = [
    [
        "HERO NAME (RUS)",
        "HERO NAME (ENG)",
        "NAME (RUS)",
        "NAME (ENG)",
        "TYPE (weapon, body, hat, accessoir)",
        "HP",
        "ATK",
        "INT",
        "DEF",
        "MDEF",
        "SKILL",
        "DESCRIPTION (RUS)",
        "DESCRIPTION (ENG)"
    ],
    [
        "Аданкельмо",
        "Adankelmo",
        "Тайна необъятных просторов",
        "Mystery of the Vast Expanse",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +10%. Когда дружественный отряд заканчивают действие на [двери], он получат «АТК/ИНТ +20%», длится 2 раунда. Все вражеские войска, способ передвижения которых не [полет], проходя через местность в 2 клетках от [двери], потребляют дополнительно 1 очко движения.",
        "HP +10%. When a friendly unit ends on [door], they will receive 'ATK / INT + 20%', lasts 2 rounds. All enemy troops that has non [flying] move, while passing through terrain within 2 tiles of the [door] consume an additional 1 movement point."
    ],
    [
        "Ака",
        "Aka",
        "Прикосновение святого духа",
        "Holy spirit's grace",
        "weapon",
        "",
        "107",
        "107",
        "",
        "",
        "",
        "ATK/ИНТ +10%. После совершения действия призывает [дух волка], который получает 75% текущих статов Аки. (Одновременно может существовать лишь 1 дух волка, и этот эффект можно активировать лишь 1 раз за бой).",
        "ATK/INT +10%. After taking action, summon one [Wolf Soul] adjacent to self. This Wolf Soul will inherit 75% of Aka's stats. (You may only have 1 Wolf Soul at once. This effect can only occur once per battle)"
    ],
    [
        "Альфред",
        "Alfred",
        "Сердце океана",
        "Heart of the ocean",
        "accessoir",
        "",
        "75",
        "",
        "",
        "",
        "37",
        "ATK +8%. Если перед боем вражеский герой не является плавцом, то он считает любую поверхность водой в течении 1 ходов. Если у вашего героя 100% ОЗ, то местность на которой он стоит считается водой. Длится 1 ход. [Активация КД] вы можете считать водой местность, на которой стоите лишь еще раз после 2 ходов.",
        "ATK +8%. Before entering battle, if the enemy hero is not an Aquatic unit, the terrain they are on is treated as Water for 1 turn. If this unit is at 100% HP, the terrain this unit is on is treated as Water. Lasts 1 turn. The effect of making this unit treat terrain as water has a 2 turn cooldown."
    ],
    [
        "Альмеда",
        "Almeda",
        "....",
        "....",
        "weapon",
        "583",
        "",
        "85",
        "",
        "",
        "",
        "ИНТ +10%. После атаки и нанесении урона мобильность противника снижается на 1 клетку, и он не может охранять в течении 1 хода.",
        "INT +10%. After attacking and dealing damage, inflicts 'Movement -1 and cannot guard' for 1 turn."
    ],
    [
        "Альфа",
        "Alpha",
        "Конструкт αEX",
        "Construct αEX",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ & ЗАЩ +5%. Мобильность +1. При атаке физической атакой с [аметистовым щитом] или магической атакой с [аметистовым барьером] герой отражает 60% получаемого урона. Если у отряда нет ни того, ни другого, урон героя увеличивается на 15%.",
        "HP & DEF +5%. Move +1. When this unit has [Amethyst Cover] or [Amethyst Shield] and takes the corresponding type of damage, reflect 60% of damage taken. If this unit has neither, hero's damage dealt +15%."
    ],
    [
        "Алтемюллер",
        "Altemuller",
        "Корона Ригулера",
        "Riguler crown",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ЗАЩ and МЗАЩ +5%. Баффы, которые вы накладываете на себя, длятся на 1 ход дольше.",
        "DEF and MDEF +5%. Buffs cast on self last for 1 more turn."
    ],
    [
        "Алустриэль",
        "Alustriel",
        "Плюмаж ветра",
        "Wind plume",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "МЗАЩ +10%. Когда находится в лесу, в горах и на пастбищах, во время атаки игнорирует режим стража, а после боя восстанавливает 20% ОЗ.",
        "MDEF +10%. When on Forest, Mountain, or Grassland terrain, attacks ignore Guard, and after battle restore HP equal to 20% of damage dealt."
    ],
    [
        "Амадей",
        "Amadeus",
        "Духовное нефритовое копье",
        "Spirit Jade Spear",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "Атака, Защита +5%. За каждый стак [Доспехов священного дерева] урон увеличивается на 5%. Когда ОЗ юнита выше 40%, его нельзя убить одним ударом, вместо этого его ОЗ восстановится на 20%, и он получит 4 стака [Доспеха священного дерева]. (Эффект может срабатывать до 2 раз за бой)",
        "Attack, Defense +5%. For each stack of [Armor of the Sacred Tree] Damage increase by 5%. When a unit's HP is above 40%, it cannot be killed at a hit, instead it will recover 20% HP and gain 4 stacks of [Armor of the Sacred Tree]. (Effect can trigger up to 2 times per battle)"
    ],
    [
        "Анжелика",
        "Angelica",
        "Многофункиональный колпак",
        "Super gadget hat",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "МЗАЩ +10%. После совершения действия восстанавливает 30% ОЗ для призванного союзного юнита с наименьшим ОЗ.",
        "MDEF +10%. After taking action, heals the friendly summoned unit with the lowest remaining HP for 30% of their HP."
    ],
    [
        "Анджелина",
        "Angelina",
        "Цветок на ветру",
        "Flower in the wind",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ЗАЩ +10%. При активации эффектов, позволяющих вам совершить повторное действие, это не защитывается в счетчике ходов всех наложенных на вас баффов. ([Активация КД] эффект можно активировать только 1 раз за 3 хода).",
        "DEF +10%. When triggering an act again, buffs on this unit will not decrease in duration. This effect has a 3 turn cooldown."
    ],
    [
        "Апофеоз",
        "Apotheosis",
        "Глобал - 25.07.2024",
        "Abyssal Revelation",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. При наличии минимум 3 доп. стата от таланта, наложенные [Тёмная магия] и [Магический выбор] невозможно снять. Когда в пределах 3 клеток есть вражеский демон или святой юнит, получает Иммунитет.",
        "HP +10%. If you have at least 3 extra stats from talent, applied [Dark Magic] and [Magic Choice] cannot be removed. When there is an enemy demon or holy unit within 3 cells, gains Immunity."
    ],
    [
        "Архонт Луны",
        "Archon of the Moon",
        "Решимость звездолёта",
        "Starship's resolve",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ & ЗАЩ +5%. При срабатывании «повторное действие», любые положительные эффекты на герое не теряют счетчик ходов. После совершения действия, если этот герой находится в воде и не нанес урона в этом ходу, восстанавливает себе 20% от максимального ОЗ.",
        "HP & DEF +5%. When this unit triggers an act again, buffs on this unit do not decrease in duration. After taking action, if this unit is on water and has not dealt damage, then restore 20% HP."
    ],
    [
        "Арес",
        "Ares",
        "Шлем Блюстителей",
        "Helm of the Vigilantes",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ & ЗАЩ +5%. Когда у героя есть особый эффект «энергия слияния», обычные атаки наносят на 30% больше урона. При инициировании боя герой также получает 1 «Боевое построение».",
        "HP & DEF +5%. If this unit has a special effect from a Fusion Power, then gain damage dealt +30% when using a normal attack, and when actively attacking and entering battle, gain 1 [Sweep Formation]."
    ],
    [
        "Ашемар",
        "Ashemar",
        "Прах Полярной звезды",
        "Ashes of the Pole Star",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Когда у вас есть партнёр по танцам, урон от умений увеличивается на 10%. После того, как вы и ваш партнер по танцу закончите действовать, вы получите другой эффект иммунитета в зависимости от типа танца исполняемого в течении 1 хода: Интимный танец: невосприимчивость к фиксированному урону. Танец рука об руку: иммунитет к безмолвию активного навыка. Кольцевой танец: иммунитет к снижению мобильности.",
        "HP +10%. When this unit has a dance partner, skill damage +10%. When this unit or its dance partner ends action, gain an immunity for 1 turn based on which dance step is used: Closed Position: Immune to Fixed Damage. Handhold: Immune to silence. Promenade: Immune to mobility down."
    ],
    [
        "Автократо",
        "Autokrato",
        "Броня имперской силы",
        "Imperial power armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ & МЗАЩ +5%. Крадёт 1 бафф у врага когда активно наносит урон. Все статы героя (кроме ОЗ) увеличиваются на 2% (максимально 10%) за каждую 1 [провокацию] у каждого врага на поле боя.",
        "DEF & MDEF +5%. When actively dealing damage, steal 1 enemy buff. For every enemy on the map with [Taunt], all stats except HP increase by 2% for this unit (up to 10%)."
    ],
    [
        "Азуса",
        "Azusa",
        "Заколка - Талисман Луны",
        "Moon talisman hairpin",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ and ЗАЩ +5%. Урон навыка увеличивается на 10% на время действия [двойной элементальной защиты]. При получении смертельного урона, если у героя есть [сильный], [мягкий] и [двойная элементальная защита], они поглощаются чтоб блокировать этот урон и восстанавливает 50% ОЗ (этот эффект можно активировать 1 раз за бой).",
        "HP and DEF +5%. When [Duality Ward] is in effect, Skill Damage +10%. If taking fatal damage while [Duality Ward], [Firm], and [Flexible] are in effect, then consume these three effects to restore 50% HP. This effect may only occur once per battle."
    ],
    [
        "Бернхардт",
        "Bernhardt",
        "Доспех повелителя",
        "Overlord's armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ +5%. Дальность таланта героя +1.",
        "HP +5%. Hero Talent Span +1."
    ],
    [
        "Бетти",
        "Betty",
        "Пламенный метеор",
        "Blazing meteor",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. Когда ОЗ снижается, наносимый фиксированный урон повышается максимум на 30%.",
        "HP +10%. Fixed damage dealt increases as HP decreases, up to a maximum of 30%."
    ],
    [
        "Бозел",
        "Bozel",
        "Благословление Хаоса",
        "Blessing of Chaos",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "МЗАЩ +10%. После активного нанесения урона врагу накладывает на него 1 случайный дебафф.",
        "MDEF +10%. After dealing damage to enemies, inflict 1 random debuff."
    ],
    [
        "Бренда",
        "Brenda",
        "Воспоминания луны",
        "Lunar memories",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ and ЗАЩ +5%. Когда активирует эффект повторного действия «образец изящности», снимает с вас 2 дебаффа, повышает наносимый вами урон на 10% и уменьшает получаемый вами урон на 10%. Длится 1 ход.",
        "HP and DEF +5%. When triggering Paragon of Elegance's act again effect, dispels 2 debuffs from self, increase damage dealt by 10% and reduce damage taken by 10%. Lasts 1 turn."
    ],
    [
        "Капитан Джек",
        "Captain Mack",
        "Глобал - 27.06.2024",
        "Black Cat Captain's Hat",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. Игнорирует стоимость навыков. Когда союзники в радиусе действия [Цели путешествия] активно атакуют и наносят урон, они крадут 1 бафф у врага после атаки и применяют 1 случайный бафф к Капитану Маку.",
        "HP +10%. Ignores skill costs. When allies within range of [Route Marker] actively attack and deal damage, they steal 1 buff from the enemy after attacking and apply 1 random buff to Captain Mack."
    ],
    [
        "Каролина",
        "Caroline",
        "Шлем фанатика",
        "Zealot helmet",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ and ЗАЩ +5%. Диапазон эффектов таланта +1 и эффекты снижения подвижности, применённые в последний ход +1. Шанс критического удара героя и наносимый им урон увеличивается на 2% за каждый пройденный блок (до 10%).",
        "HP and DEF +5%. Talent span +1 and the movement down effect has duration +1. For every 1 block moved, this hero's critical hit rate and damage dealt is increased by 2% (up to 10%)."
    ],
    [
        "Шери",
        "Cherie",
        "1UP",
        "1UP",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ЗАЩ и МЗАЩ +5%. Когда атакуете и вступаете в битву, вы не погибаете, если получаете смертельный урон. (Эффект может быть активирован только еще раз после 4 ходов).",
        "DEF and MDEF +5%. When taking fatal damage while attacking and entering battle, this unit will not die, instead restoring 1% HP. This effect has a 4 turn cooldown."
    ],
    [
        "Крис",
        "Chris",
        "Дар Света",
        "Maiden's praise",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ and МЗАЩ +5%. Если этот герой нанес на этом ходу урон, после совершения действия эффект его таланта накладывает 1 дополнительный бафф. После убийства демона получает одно дополнительное действия ([Активация КД] КД этого повторного действия составляет 2 хода).",
        "HP and MDEF +5%. After taking action, if damage was dealt this turn, then Talent will grant 1 extra buff to each target. After defeating a Demon, may act again. This act again effect has a 2 turn cooldown."
    ],
    [
        "Кристиан",
        "Christiane",
        "Шляпа маркиза",
        "Marquis hat",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ЗАЩ and МЗАЩ +5%. Эффект невосприимчивости к смещению. При срабатывании таланта, предотвращающего смерть, при получении смертельного урона, получает [Шепот - Хиганбана] (эффект нельзя суммировать и вы не можете получить другие шепоты, если у вас есть [Шепот – Хиганбана).",
        "DEF and MDEF +5%. Immune to displacement. After activating the revive effect from Talent, gain the [Equinox] effect. You may only have one [Whispers] effect."
    ],
    [
        "Кларетт",
        "Clarett",
        "Шлем Кальсата",
        "Kalxath helmet",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. Когда в радиусе 2 клеток нет союзных юнитов, после совершения действия восстанавливает 15% ОЗ. Когда втянут в бой в ходе ближней атаки, наносимый урон увеличивается на 20% и получаемый урон уменьшается на 20%.",
        "HP +10%. When there are no allies within 2 blocks, heal 15% HP after taking action. When forced into battle by a melee attack, damage dealt +20% and damage taken -20%."
    ],
    [
        "Клотэр",
        "Clotaire",
        "Вечная Клятва Пламени",
        "Eternal oath of the flame",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Когда у любого врага есть эффект 'расколотое пламя', атака и интелект союзников в радиусе 2 клеток вокруг него увеличивается на 10%. После нанесения урону противнику получает эффект 'урон от следующего умения увеличивается на 25%'",
        "Life +10%, When any enemy has [Destroyed Flame Pattern], allies within 2 blocks around it: 'Attack, Intelligence' increased by 10%. After causing skill damage to the enemy, get '25% increase in next skill damage'."
    ],
    [
        "Дихарт",
        "Dieharte",
        "Золотой лев",
        "Golden lion",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "МЗАЩ +10%. В случае уничтожения врага в этом ходу снимает 1 бафф с одного врага в радиусе 3 клеток после завершения действия.",
        "MDEF +10%. When eliminating an enemy on this turn, stuns 1 enemy within 3 blocks for 1 turn after taking action."
    ],
    [
        "Эгберт",
        "Egbert",
        "Одеяние огнепоклонника",
        "Garb of firewalking",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ & ЗАЩ +5%. Подвергшись атаке и получив урон вы получаете также дальность навыка +1 и диапазон +1 в течении 1 хода.",
        "HP & DEF +5%. After taking damage from being attacked, gain 'Skill range +1 and Span +1' for 1 turn."
    ],
    [
        "Элисса",
        "Elisse",
        "",
        "Key of the Eternal Night",
        "accessoir",
        "",
        "75",
        "",
        "43",
        "",
        "",
        "АТК +8%. Если в радиусе 3 клеток есть [Ключ защиты], наносимый урон увеличивается на 20%. При активной атаке и вступлении в бой, если враг находится на [Ключе защиты], он будет оглушен перед боем.",
        "ATK +8%. If there is a [Guardian Key] within 3 blocks, the damage dealt is increased by 20%. When actively attacking and entering battle, if the enemy is on the [Guardian Key], he will be stunned before the battle."
    ],
    [
        "Эльма",
        "Elma",
        "Религиозные обряды",
        "Devotional rites",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Исцеляющий эффект [Святой свечи] увеличен на 20%. Когда на него действует особый эффект фракционного усиления, примененное [Зеркало священного света] нельзя рассеять.",
        "HP +10% [Holy Candle] healing effect increased by 20%. When it has the special effect of faction buff, the applied [Mirror of Holy Light] cannot be dispelled."
    ],
    [
        "Элвин",
        "Elwin",
        "Странствующий рыцарь",
        "Errant knight",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "ATK +10%. При нанесении урона с помощью навыка с 30% шансом снижает КД на 5.",
        "ATK +10%. When dealing skill damage, 30% chance to decrease cooldown by 5."
    ],
    [
        "Эмерик",
        "Emerick",
        "Предусмотрительность",
        "Farsight",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. После завершения действия все враги в радиусе 2 клеток получают случайный дебафф.",
        "HP +10%. After taking action, inflict 1 random debuff on all enemies within 2 blocks."
    ],
    [
        "Эмилия",
        "Emilia",
        "Славное наследие",
        "Glorious legacy",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "ЗАЩ & МЗАЩ +5%. Когда втянуты в бой, получаемый героем физический урон снижается на 10%. Если у вас есть эффект [святая гвардия] или [продвинутая святая гвардия], герой может контратаковать в ответ на дальние атаки.",
        "DEF & MDEF +5%. When forced into battle, unit physical damage taken -10%. If this unit is under the effect of [Holy Guard] or [Divine Sanctuary], then the Hero may counter ranged attacks."
    ],
    [
        "Император Ловина",
        "Emperor Lovina",
        "Управление границей",
        "Ruling the frontier",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "ОЗ and ATK +5%. Когда этот герой имеет особый эффект «энергия слияния», он получает +1 дальность умения при использовании АОЕ-навыков. После того как союзный отряд развернут, он наносит 10% урон в течении 2 ходов. После развертывании эффекты повышения мобильности таланта длятся 1 ход.",
        "HP and ATK +5%. When this unit has a special effect from a Fusion Power, AoE skill span +1. After deploying allies, grant those allies 'Damage Dealt +10%'. Lasts 2 turns. After deploying, movement gained from talent has its duration increased by 1"
    ],
    [
        "Эпсилон",
        "Epsilon",
        "Меч уничтожения",
        "Annihilation blade",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "ATK +10%. Этот герой игнорирует недостатки класса. Когда погибает юнит, снимает с себя 1 дебафф, восстанавливает 30% ОЗ и получает [щит альхазарда]: следующий получаемый этим героем урон снижается на 80%. Когда срок его действия истекает, [щит альхазарда] можно будет получить снова только через 1 ход.",
        "ATK +10%. This unit ignores class effects. When a unit dies, dispel 1 debuff from self, restore 30% HP and gain [Demon Sword's Ward]: 'Damage taken from the next attack reduced by 80%'. [Demon Sword's Ward] has a 1 turn cooldown."
    ],
    [
        "Злой Бог Крюгер",
        "Evil God Kreuger",
        "Лицо обмана",
        "The Fool's other side",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Когда герой погибает, превращает 2 баффа в случайные дебаффы всем врагам в радиусе 5 клеток.",
        "HP +10%. When this hero dies, enemies within 5 blocks have 2 of their buffs replaced with random debuffs."
    ],
    [
        "Феракуа",
        "Feraquea",
        "Шлем кошмарных снов",
        "Nightmare casque",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +5%. При сражении с противником над которым у вас есть классовое преимущество, АТК увеличивается на дополнительные 10%.",
        "HP +5%. When battling units which you have an advantage over, ATK +20%."
    ],
    [
        "Флоренция",
        "Florentia",
        "Жемчужина империи",
        "Gem of the empire",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ & МЗАЩ +5%. Получаемый солдатами урон снижается на 10%. Когда начинается бой или погибает союзник герой получает 1 эффект [военной стратегии].",
        "HP & MDEF +5%. Soldier damage taken -10%. At the start of a battle and when an ally dies, gain 1 [Battle Strategy]."
    ],
    [
        "Фрейя",
        "Freya",
        "Терновый венец",
        "Crown of thorns",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "МЗАЩ +10%. Перед тем как быть втянутым в бой, наносит врагу фиксированный урон, равный 2х МЗАЩ героя.",
        "MDEF +10%. Before being forced into battle, deals fixed damage to the enemy equal to Hero's MDEF x2."
    ],
    [
        "Герольд и Лайла",
        "Gerold & Layla",
        "Хранитель единства",
        "Heart guardian",
        "weapon",
        "",
        "107",
        "107",
        "",
        "",
        "",
        "ATK & ИНТ +10%. Дальность обычной атаки +1. После инициирования боя исцеляет союзного юнита с наименьшим ОЗ (1х от (АТК+ИНТ) героя). При использовании эффекта «повторное действия» число ходов для наложенных баффов сохраняется.",
        "ATK & INT +10%. Hero's normal attack range +1. After actively attacking in battle, restore HP to the ally with the lowest HP equal to Hero's ATK+INT x1. When using act again effects, buffs on this unit will not decrease in duration."
    ],
    [
        "Девушка в Доспехах",
        "Girl in the Shell",
        "Исходное ядро",
        "Source core",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. В конце действия, если в этом раунде не был нанесен урон, получает усиленное обучение: Интеллект +5%, при использовании умений дальность войск +1 (нельзя снять, снимается после инициировании боя и нанесения урона).",
        "At the end of the action, if no damage is dealt this turn, gain Reinforcement Learning: + 5% Intelligence, + 1 Range when skill is used (Cannot dispell, deal damage once and remove)."
    ],
    [
        "Гизаров",
        "Gizarof",
        "Скипетр разрушения",
        "Scepter of destruction",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ & ОЗ +5%. Если после активного использования навыка один из призванных Гизаровым «конструктов» находится на поле боя, 1 раз проводится случайное «Обновление конструкта».",
        "INT & HP +5%. After using a skill, if Gizarof has a 'Construct', 1 'Renovation' is added."
    ],
    [
        "Гренье",
        "Grenier",
        "Корона снов",
        "Crown of dreams",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "МЗАЩ +5%. Когда у вас есть 7 и более баффов, урон контратаки повышается на 50%.",
        "MDEF +5%. When you have at least 7 buffs, counter damage +50%."
    ],
    [
        "Греншиль",
        "Grenshiel",
        "",
        "Pride of the Frozen Winter",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. Если сражается с отрядом, мобильность которого ниже, противник не может атаковать первым. При активной атаке навыком и входе в бой, если у противника есть эффект снижения мобильности, перезарядка этого навыка будет уменьшена на 4 хода. (Триггер перезарядки: может сработать снова только через 2 хода)",
        "HP +10%. If fighting with a unit whose mobility is lower, the enemy cannot attack first. When actively attacking with a skill and entering battle, if the enemy has a mobility reduction effect, the cooldown of this skill will be reduced by 4 turns. (Cooldown trigger: can only be trigged again after 2 turns)"
    ],
    [
        "Ганн",
        "Gunn",
        "---",
        "Pilgrim's Robe",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ и ЗАЩ +5%. Каждый раз когда эффект [Месть одинокого волка] снимается, собственное исцеление уменьшается на 5%. [Мощь Лунного Волка] дает дополнительный эффект: В конце хода может выбрать снять эффект [Мощь Лунного Волка] и получить [Месть одинокого волка]. Перезарядка этого триггера 1 ход.",
        "HP and DEF +5%. Each time [Lone Wolf's Revenge] is removed, your own healing is reduced by 5%. [Luna Wolf Strength] provides an additional effect: At the end of the turn, can choose to remove the effect of [Luna Wolf Strength] and gain [Lone Wolf's Revenge]. The cooldown of this trigger is 1 turn.."
    ],
    [
        "Густав",
        "Gustaf",
        "Далёкое эхо",
        "Distant echo",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Когда у этого героя есть умение на перезарядке, урон увеличивается на 10%. Перед вступлением в бой при атаке дальней атакой наносит противнику фиксированный урон равный 1х ИНТ.",
        "HP +10%. When this unit has skills on cooldown, hero damage dealt +10% and before being forced into battle by a ranged attack, deal 1x This Unit's INT as fixed damage."
    ],
    [
        "Хейн",
        "Hein",
        "Ну и ну, принцесса?",
        "My, my, my princess?",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +5%. Бафф таланта героя складывается на +1. Получает эффект энергии слияния Альянса Принцесс.",
        "HP +5%. Hero talent buff stacks +1. May receive Princess Alliance Fusion Power effect."
    ],
    [
        "Хелена",
        "Helena",
        "Латы из лунных клисталлов",
        "Mooncrystal armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ & ЗАЩ +5%. После совершения действия накладывает особый эффект [непоколебимые кристаллы] на клетки в диапазоне 1 кольца на 1 ход. Когда на союзной местности [непоколебимые кристаллы], получаемый героем урон уменьшается на 15%. А также восстанавливает 30% ОЗ после того как был атакован и получил урон.",
        "HP & DEF +5%. After taking action, create [Crystal Radiance] within 1 ring of self. When on allied [Crystal Radiance], damage taken-15%, and after being attacked and taking damage, restore 30% HP."
    ],
    [
        "Хильда",
        "Hilda",
        "Багровая броня",
        "Scarlet armor",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ & ЗАЩ +5%. Экипированные навыки игнорируют ограничение стоимости. При входе в ближний бой, перед боем отключает навыки оружия противника (кроме эффектов макс ОЗ). Когда цель не является героем игрока, эффект меняется на 25% эффект снижения атаки и интелекта. Длится 1 ход.",
        "HP & DEF +5%. Ignore skill cost limit. When entering melee battle, cause the enemy to be afflicted with 'Weapon Skill Disabled (Excluding Max HP effects)'. If the enemy is an NPC, this effect is instead 'ATK/INT -25%'. Lasts 1 turn."
    ],
    [
        "Хофманн",
        "Hofmann",
        "Слава и увядание",
        "Glory and Decay",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ +5%. При использование Щитом умение обозначения зоны он получает Комманду: 'Когда другие нелетающие союзники проходят через зону щита они дополнительно получают шанс убрать 1 клетку снижения мобильности'. Сам щит получает способность 'Вступает в бой вместо союзников в радиусе 3 клеток'.",
        "DEF +5%. When using the Shield zone designation skill, it receives Command: “When other non-flying allies pass through the shield zone, they additionally gain a chance to remove 1 cell of mobility reduction.” The shield itself gains the ability “Enter battle instead of allies within a radius of 3 cells.”"
    ],
    [
        "Илюсия",
        "Ilucia",
        "Воспоминание о любви",
        "Midsummer memory",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "ЗАЩ & МЗАЩ +5%. Перед вынужденым вступление в бой накладывает на себя «приливную волну». Длится 1 ход. В воде принимает на себя все атаки направленные на союзных юнитов в радиусе 1 кольца.",
        "DEF & MDEF +5%. Before being forced into battle, give 'Tidal Surge' effect to self. Lasts 1 turn. When in water, takes all attacks for allies within 1 ring."
    ],
    [
        "Имельда",
        "Imelda",
        "Великолепный красный",
        "Gorgeous red",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "МЗАЩ +10%. После завершения действия дарует 4 союзникам в пределах 2 клеток иммунитет к фиксированому урону. Длится 1 ход.",
        "MDEF +10%. After taking action, 4 allies within 2 blocks gain 'Immune to Fixed Damage'. Lasts 1 turn."
    ],
    [
        "Железный Воитель",
        "Ironblood Commander",
        "Фуражка маршала",
        "Marshal's cap",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Каждый раз, когда талант используется, бафф будет длиться +1 раунд.",
        "Life +10% Every time the array skill is used in battle, the buff of the skill will last rounds +1."
    ],
    [
        "Джо и Конни",
        "Joa & Connie",
        "Визуальный терминал Y-типа",
        "Y- type Visual Terminal",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. Когда Джоа находится в пределах 3 блоков, урон от атаки Конни увеличивается на 15%. Когда Джоа использует помехи канала, он так же может дополнительно получить: «[Команда] Вражеские войска в пределах 2 клеток вокруг него не могут быть охраняемы, когда их атакует Конни », длится 2 раунда.",
        "HP +10%. When Joa is within 3 blocks, Connie's attack damage is increased by 15%. When Joa uses channel jamming, she can additionally gain: '[Command] Enemy troops within 2 tiles cannot be defended when attacked by Connie', lasts 2 rounds."
    ],
    [
        "Джаглер",
        "Jugler",
        "Дар Джаглера",
        "Jugler's gift",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +5%. После боя восстанавливает ОЗ героя на 10% и игнорирует стоимость навыков.",
        "HP +5%. After battle, restore 10% HP. Ignore skill cost limit."
    ],
	[
        "Джесс",
        "Jayce",
        "Глобал - 12.12.2024",
        "Global - 12.12.2024",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. В конце действия, если за ход был нанесён урон, время восстановления навыка с самым низким оставшимся временем восстановления будет снижено на 1. За каждый союзный [Чародейский след] этот юнит игнорирует 5% МЗАЩ противника (до 20%).",
        "HP +10%. At the end of the action, if damage was dealt during the turn, the cooldown of the skill with the lowest remaining cooldown will be reduced by 1. For each allied [Arcane Mark], this unit ignores 5% of the enemy's MDEF (up to 20%)."
    ],
    [
        "Джулиан",
        "Julian",
        "Молчание палача",
        "Executioner's silence",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. Если на поле боя есть враг с ОЗ меньше 100%, дальность юнита +1 при использовании навыков. После атаки есть 20% шанс получить повторный ход. (Этот эффект может сработать снова после 2 раундов",
        "HP +10%. If there are enemy units whose HP is lower than 100%, the range of the unit will be +1 when using skills. After atacking, there is a 20% chance to act again. [Trigger Cooldown] This effect can only be triggered again after 2 rounds."
    ],
    [
        "Кагуя",
        "Kaguya",
        "Умалет лазурной капли",
        "Azure drop amulet",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. В начале боя получает случайным образом 2 [свинью], [оленя] или [бабочку]. Эффект «диапазон героя +2», получаемый при использовании [скрытой карты], нельзя рассеять. Шанс критического удара героя увеличивается на 1% за каждую 1 [свинью], [оленя] или [бабочку], использованных в этой битве (до 10%).",
        "HP +10%. At the start of a map, gain 2 random [Ino], [Shika], or [Cho]. The 'Unit Range +2' from [Sleeved Card] cannot be dispelled. For every 1 [Ino], [Shika], or [Cho] consumed, Hero critical hit rate +1% (up to 10%)."
    ],
    [
        "Кертес",
        "Kertesz",
        "Шляпа призыва души",
        "Soul-calling hat",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Восстанавливает 20% ОЗ после вступления в бой, когда враг атакует [печать души]. При убийстве двойника с портрета, наносимый урон увеличивается на 10%, а получаемый урон уменьшается на 10%.",
        "HP +10%. After being attacked by enemy with [Soul Seal], restore 20% HP. When defeating an enemy, the resulting Painted Puppet will have 'Damage Dealt +10%' and 'Damage Taken -10%'."
    ],
    [
        "Король Красной Луны",
        "King of the Red Moon",
        "Роба лунного затмения",
        "Lunar eclipse robe",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +10%. Наносимый фиксированный урон и эффект исцеления увеличивается на 20%. «Тёмная сторона луны» увеличивает диапазон баффа на 1.",
        "HP +10%. Fixed damage dealt and received heal effects +20%. Command range of 'Dark Side of the Moon' +1."
    ],
    [
        "Кирикадзе",
        "Kirikaze",
        "Бамбуковая шляпа",
        "Bamboo hat",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ЗАЩ & МЗАЩ +5%. Когда у героя 100% ОЗ, получает +30% к НАВЫКУ",
        "DEF & MDEF +5%. When unit is at 100% HP, +30% SKILL."
    ],
    [
        "Рыцарь Тайн",
        "Knight of Mystery",
        "Клятва защитника",
        "Guardian oath",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ +10%. Когда состоит из смешанного войска, на героя не действует штрафы за мобильность на местности. Перед атакой и нанесением урона герой наносит фиксированный урон, равный 0.5х МЗАЩ 1 раз.",
        "INT +10%. When this unit is Mixed Forces, its movement type is considered Terrain Master. Before actively dealing damage, deal 1 instance of fixed damage equal to 0.5x Hero's MDEF."
    ],
    [
        "Ламбда",
        "Lambda",
        "Расцвет Мирового древа",
        "Yggdrasil blossom",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "ИНТ +5%. При использовании навыка за каждую пораженную цель время КД навыка с вероятностью 10% снижается на 5, шанс может увеличиваться до 50%.",
        "INT +5%. When you use a skill, for each target damaged, 10% chance to reduce that skill's cooldown by 5, up to 50% chance."
    ],
    [
        "Лана",
        "Lana",
        "Черная невеста",
        "Black bride",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +5%. Перед атакой накладывает один случайный мощный дебафф на атаковавшего юнита.",
        "HP +5%. Before entering battle, inflicts one random powerful debuff on the opponent."
    ],
    [
        "Ланс",
        "Lance",
        "Корона Кальсата",
        "Crown of Kalxath",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +5%. Когда этот герой сформирован из смешанных войск, урон повышается дополнительно на 10%.",
        "HP +5%. When this unit is mixed forces, damage dealt +20%."
    ],
    [
        "Лэндиус",
        "Landius",
        "Воспоминания Защитника",
        "Defender's memories",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "ATK +10%. Когда втянуты в бой, если в радиусе 2 клеток есть союзники, за каждую 1 клетку расстояния от врага получаемый героем урон уменьшается на 5%, до 15%.",
        "ATK +10%. When forced into battle, if there are any allies within 2 blocks of this unit, then for every block between this unit and the attacker, this unit takes 5% less damage, up to 15%."
    ],
    [
        "Ленфорд",
        "Lanford",
        "Второй шлем Лэнфорда",
        "Lanford's second election",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ЗАЩ +10%. Дальность таланта героя +1.",
        "DEF +10%. Hero's Talent Span +1."
    ],
    [
        "Ледин",
        "Ledin",
        "Испытание веры",
        "Trial of faith",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "ЗАЩ & МЗАЩ +5%. После уничтожения врага блокирует 1 смертельный удар и восстанавливает ОЗ героя до прежнего значения. В этом статусе можно активировать только 1 возрождение. Длится 1 ход. ([активация КД] эффект можно активировать только 1 раз за 3 хода).",
        "DEF & MDEF +5%. When this unit defeats an enemy, gain 'Prevent one instance of fatal damage, instead returning to the amount of HP this unit was at before that instance of damage. This may only occur once during this buff.' Lasts 1 turn. This effect has a 2 turn cooldown."
    ],
    [
        "Лео Бек",
        "Leo Beck",
        "Успех подземного мира",
        "Usekh of the Underworld",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Навязанный контракт не может быть расторгнут. После того, как Темное пламя наносит урон, перезарядка сокращается в зависимости от количества задетых врагов (максимальное снижение — 3 раунда).",
        "Life +10%. The imposed [Contract] cannot be dispelled. [Death Flame Corrosion] reduces the cooling time after causing damage, and the reduced value is the number of enemies hit by [Devil Flame Corrosion] (maximum reduction of 3 rounds)."
    ],
    [
        "Леон",
        "Leon",
        "Броня синего дракона",
        "Blue dragon carapace",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ +10%. Когда получаете урон, местность больше не влияет на мобильность. Длится 1 ход.",
        "DEF +10%. After taking damage, gain 'Movement is not affected by terrain'. Lasts 1 turn."
    ],
    [
        "Левин",
        "Lewin",
        "Корона древних королей",
        "Ancient crown",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ЗАЩ +10%. Если в радиусе 2 клеток есть дружественный юнит, герой наносит на 10% больше урона. Может получать преимущество от эффекта енергии слияния [Легион Света].",
        "DEF +10%. When there are allies within 2 blocks, hero damage dealt +10%. May receive 'Legion of Glory' fusion powers."
    ],
    [
        "Лиана",
        "Liana",
        "Безупречная дань уважения",
        "Flawless tribute",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +10%. Когда используется Дополнительный ход, также накладывает на цель АТК/ИНТ + 20%. Длится 2 раунда. Призванный небесный лучник имеет повышенные статы и умение «Молитва».",
        "HP +10%. When using [Act Again], also grant 'ATK/INT +20%'. Lasts 2 turns. Summoned Sky Archer has increased stats and has the skill [Prayer]."
    ],
    [
        "Ликорис",
        "Licorice",
        "Корона повелительницы",
        "Young monarch",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. При использовании «повторного действия» число ходов для наложенных баффов сохраняется. Когда имеете эффект «энергия слияния», после совершения действия на этом ходу КД ваших навыков уменьшается на 1, если вы не нанесли урон.",
        "HP +10%. This unit's buffs do not decrease in duration when using act again effects. If this unit has a special effect from a Fusion Power, then when ending action without dealing damage, all skills get CD-1."
    ],
    [
        "Лиффани",
        "Liffany",
        "Крылья феи",
        "Fairy wings",
        "accessoir",
        "",
        "",
        "75",
        "",
        "43",
        "",
        "ИНТ +5%. После атаки позволяет переместиться еще на 2 клетки.",
        "INT +5%. After attacking, can move 2 blocks."
    ],
    [
        "Аватар Света",
        "Light of Genesis",
        "Надпись возрождения",
        "Inscription of rebirth",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%.Максимальное количество суммирований [величественный свет] для талантов героя увеличивается на +1. При срабатывании повторного действия любые положительные эффекты на герое не теряют счетчик ходов.",
        "HP +10%. [Majestic Light] max stacks +1. When triggering act agains, buffs on this unit will not decrease in duration."
    ],
    [
        "Светоносец",
        "Lightbringer",
        "Эмбер Уотч",
        "Ember Watch",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. За каждый 1 слой [Зеркального света] урон, наносимый войсками, увеличивается на 2%. В конце действия, если у вас есть 5 слоев [Зеркального света], вы можете восстановить ОЗ союзника с наименьшим количеством ОЗ, на 2,5х от ИНТ.",
        "HP +10%. For every 1 layer of [Mirror Light], the damage dealt by troops is increased by 2%. At the end of the action, if you have 5 layers of [Mirror Light], you can recover the HP of the ally with the lowest HP by 2.5x INT."
    ],
    [
        "Листелл",
        "Listell",
        "Рогатый шлем демона",
        "Horned helm of the demon",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. Если у героя более 80% ОЗ, ЗАЩ и МЗАЩ увеличивается на 10%. После нанесении урона врагам заставляет их нанести на 20% меньше магического урона в течении 2 ходов.",
        "HP +10%. When this unit's HP is at least 80%, DEF and MDEF +10%. After dealing damage to an enemy, inflict 'Magic Damage Dealt -20%'. Lasts 2 turns."
    ],
    [
        "Лиза",
        "Liza",
        "Лидер Блуждающих Духов",
        "Leader of the wandering spirits",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. При выборе формы снимает с себя 1 отрицательный эффект и получает 1 случайный положительный эффект.",
        "HP +10%. Each time this unit changes form, remove 1 debuff and gain 1 random buff."
    ],
    [
        "Лостхэм",
        "Lostham",
        "Гладиатор песков",
        "Gladiator of the sands",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ и ЗАЩ +5%. При срабатывании пассивного эффекта разгневанного гладиатора вероятность критического удара увеличивается на 10% на 1 раунд. Если находится в пустыне, также может активировать пассивный эффект разгневанного гладиатора.",
        "When Rage Gladiator passive effect is triggered, Critical Strike Chance is increased by 10% for 1 turn. If you are in the desert, you can also trigger the passive effect of Rage Gladiator"
    ],
    [
        "Лукреция",
        "Lucretia",
        "Корона искупления",
        "Coronet of redempton",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. [Мистический голем] после выполнения действия рассеивает 1 дебафф у призывателя и применяет 1 случайный эффект иммунитета на 1 ход. [Мистический голем] при активной атаке атакует раньше врага. Когда призыватель умирает, наносимый урон увеличивается на 30%.",
        "HP +10%. After the [Arcane Golem] takes action, the summoner is dispelled of 1 debuff and gains 1 random immunity. Lasts 1 turn. When [Arcane Golem] attacks, it will strike first, and if the summoner is dead, damage dealt +30%."
    ],
    [
        "Люгнер",
        "Lugner",
        "Корона верующего",
        "Crown of the Beliver",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Когда союзник погибает - победивший его враг получает 4 стака [Грех]. Когда у врага есть 4 и более стаков [Грех], урон, наносимый в бою со святыми, уменьшается на 15%.",
        "HP+10%. When an ally dies, the damage source gains 4 layers of [Sin]. When enemy has 4 or more layers of [Sin], damage agains [Saint] decreased by 15%"
    ],
    [
        "Луна",
        "Luna",
        "Корона разящего ветра",
        "Windstriker crown",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ & МЗАЩ +5%. Дальность эффекта команды всех ваших талантов и навыков увеличивается на 1. После совершения действия накладывает «наносимый урон увеличивается на 15%» на 2 союзников в радиусе 1 клетки. Длится 1 ход.",
        "HP & MDEF +5%. Command range from talent and skills +1. After taking action, grants 2 allies within 1 block 'Damage Dealt+15%'. Lasts 1 turn."
    ],
    [
        "Майя",
        "Maiya",
        "Суперметла",
        "Dust buster",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ +10%. Тип передвижения героя изменен на [полёт]. АОЕ-навыки могут убирать вражеские эффекты местности с пораженных клеток. После совершения действия рассеивает со всех союзных юнитов в радиусе 2 клеток 1 дебафф.",
        "INT +10%. Unit movement type is considered [Flying]. AoE skills from this unit can clear enemy terrain effects. After taking action, dispel 1 debuff from allies within 2 spaces."
    ],
    [
        "Мариандель",
        "Mariandel",
        "Улыбка Святого Дерева",
        "Smile of the Holy Tree",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. При получении [энергия маны] от срабатывающего таланта 50% шанс получить 1 дополнительную [энергия маны].",
        "HP +10%. When Talent generates [Mana], have 50% chance to generate 1 additional [Mana]."
    ],
    [
        "Мариэль",
        "Mariel",
        "Карающий цеп",
        "Holy flail",
        "weapon",
        "583",
        "85",
        "",
        "",
        "",
        "",
        "ATK +10%. Если у героя есть «предписание», после использования навыка КД этого навыка уменьшается на 1. Если у героя нет «предписания», наносимый урон увеличивается на 10%. ([Активация КД] Снижение КД этого эффекта составляет 2 хода).",
        "ATK +10%. When this unit has [Commandment], then after using a skill, CD-1 on that skill. When this unit does not have [Commandment], Hero Damage Dealt +10%. The cooldown reduction effect has a 2-turn cooldown."
    ],
    [
        "Метью",
        "Matthew",
        "Сплоченность",
        "Kizuna band",
        "accessoir",
        "509",
        "75",
        "",
        "",
        "",
        "",
        "Если в радиусе 2 клеток есть союзник, АТК, ЗАЩ, МЗАЩ увеличивается на 10%.",
        "When an ally is within 2 blocks, ATK, DEF, and MDEF +10%."
    ],
    [
        "Маклейн",
        "McClein",
        "Основной метанабор",
        "Core metaset",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +5%, ЗАЩ +5%. При проходе по местности с дружественным эффектом [Рывок] расход движения такой же, как при проходе по воде. При активной атаке и убийстве врага восстанавливает 20% ОЗ.",
        "HP +5%, DEF +5%. When walking through terrain with the [Dash] friendly effect, the movement cost is the same as when walking through water. When actively attacking and killing an enemy, restores 20% of HP."
    ],
    [
        "Мелания",
        "Melania",
        "Призыватель силы",
        "Strength summoner",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "Эффект исцеления +15%. Этот юнит получает [комманду]: все союзные юниты в радиусе 1 клетки получают иммунитет к [ранящему проклятию] и эффектам, не позволяющим исцеляться.",
        "Heal Effect +15%. The unit gains [Command]: 'Allies within 1 block are immune to 'Curse of Wounding' and 'Cannot be Healed'.'"
    ],
    [
        "Мишель",
        "Michel",
        "Волшебное научное оружие",
        "Magic science arms",
        "weapon",
        "364",
        "118",
        "",
        "",
        "",
        "",
        "ATK +10%. После нанесения урона противнику есть 50% шанс применить 1 суммирование [жгучее пламя] и получает «при использовании прямолинейных умений дальность умения +1 на 1ход. Нельзя рассеять».",
        "ATK +10%. After dealing damage to an enemy, 50% chance to inflict 1 stack of [Burning Flame], and this unit gains 'Line skill range +1. Lasts 1 turn. Cannot be dispelled.'"
    ],
    [
        "Мю",
        "Mu",
        "Цветочный венок",
        "Blooming ring",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. После совершения действия получает эффект, который заставляет всех юнитов в радиусе 3 клеток считать любую местность «пастбищем» в течении 1 хода. ([Активация КД] Эффект можно активировать только еще раз после 3 ходов).",
        "HP +10%. After taking action, gain buff: 'Units within 3 blocks have all terrain considered as 'Grasslands''. Lasts 1 turn. This effect has a 3 turn cooldown."
    ],
    [
        "Нарм",
        "Narm",
        "Звезда валькирии",
        "Valkyrie pulsar",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "МЗАЩ +10%. Талант героя (активация КД) уменьшается на 1 ход.",
        "MDEF +10%. Hero Talent Cooldown -1."
    ],
    [
        "Неемия",
        "Nemia",
        "---",
        "---",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ОЗ +10%. Дальность действия [Таинственное океанское течение] +1. Не удаляет свой эффект местности, когда становится на него. Когда другие союзники в пределах 2 клеток становятся на [Таинственное океанское течение] они получают [Поездка на волне]",
        "HP +10%. Range of [Mysterious Ocean Current] +1. Does not remove its terrain effect when standing on it. When other allies within 2 tiles stand on [Mysterious Ocean Current] they gain [Ride the Wave]."
    ],
    [
        "Ноэми",
        "Noemi",
        "Мыслительная шляпа",
        "Thinking cap",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. После совершения действия юниты с [магической одеждой] рассеивают с себя 1 дебафф и восстаналивают 5% ОЗ. После использования [Одеяния стратега], этот навык может получить эффект 1 дополнительный раз.",
        "HP +10%. All units with Magic Garments will have 1 debuff dispelled at the end of their turn and restore 5% HP. When using Strategist's Garb, gain 1 extra charge."
    ],
    [
        "Нимфа",
        "Nymph",
        "Баллада о далёком берегу",
        "",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ +10%; При применении [Пузыря фантазий] время восстановления всех навыков сокращается на 1 ход. Если у вас есть [Серенада] в начале раунда, вы получите дополнительный уровень стака таланта.",
        "INT +10%. When using [Fantasy Bubble], the cooldown of all skills is reduced by 1 turn. If you have [Serenade] at the beginning of the round, you will gain an additional level of talent stack."
    ],
    [
        "Оборо",
        "Oboro",
        "Эфирный Фантазм",
        "Aether phantasm",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. Когда используется [Элементальное накопление], если этот герой имеет эффект энергии слияния, получает 1 дополнительный стак накопления. Когда атакует и вступает в бой, получаемый урон и отраженный урон -30%.",
        "HP +10%. When using [Focus Elements]. if this unit has a special effect from a Fusion Power, then gain 1 extra stack of Dracomorph. When attacking and entering battle, damage taken and reflect damage taken -30%."
    ],
    [
        "Оливиер",
        "Oliver",
        "Урок по созданию героя",
        "Handicraft hero lesson",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ & МЗАЩ +5%. В случае нанесения критического удара накладывает на врага 1 мощный дебафф и крадёт 1 бафф.",
        "HP & MDEF +5%. Upon landing a critical hit, inflict 1 debuff and steal 1 buff."
    ],
    [
        "Омега",
        "Omega",
        "Атма-граха",
        "Atma-graha",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. Убийство врага с помощью активного навыка уменьшает КД этого навыка на 2 хода. После совершения действия получает «НАВЫК +20%» и мобильность +2 на 1 ход.",
        "HP +10%. After using a skill to defeat an enemy, CD-2 for that skill and gain 'Skill +20%' and 'Movement +2' for 1 turn."
    ],
	[
        "Патриция",
        "Patricia",
        "Глобал - 14.11.2024",
        "Global - 14.11.2024",
        "weapon",
        "437",
        "",
        "107",
        "",
        "",
        "",
        "ИНТ +10%. Продолжительность действия [Сжигающая душу чума] +1. После того как активно атакует врага, 100% шанс наложить еще 1 стак [Сжигающая душу чума].",
        "INT +10%. Duration of [Soulburning Plague] +1. After actively attacking an enemy, there is a 100% chance to inflict 1 more stack of [Soulburning Plague]."
    ],
    [
        "Патцир",
        "Patsyr",
        "Коллдовская вуаль",
        "Veiled enchantress",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ & МЗАЩ +5%. +1 к мобильности, когда у врагов есть герой, не являющейся женщиной. После совершения действия 1 случайный герой, не являющейся женщиной, в радиусе 3 клеток получает эффект [утомлённый].",
        "HP & MDEF +5%. If the enemy has a non-female hero, movement+1. After taking action, inflict [Fatigue] on one random non-female hero within 3 blocks."
    ],
    [
        "Полиал",
        "Polyal",
        "Глобал - 29.02.2024",
        "Whispers of the Ancestral Spirit",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ЗАЩ +10%. Когда у вас есть умение в перезарядке, наносимый урон +10%. При применении [перемещения] на враге получает ауру: 'Все враги в радиусе 2 блоков получают на 30% меньше лечения'. Действует 1 раунд.",
        "DEF +10%. When you have a skill on cooldown, damage dealt +10%. When doing [displacement] on an enemy, gains the aura: 'All enemies within 2 blocks receive 30% less healing.' for 1 round."
    ],
    [
        "Преция",
        "Precia",
        "Глобал - 25.04.2024",
        "Edge of the Seasons",
        "weapon",
        "364",
        "118",
        "",
        "",
        "",
        "",
        "АТК +10%. [Поток времени] дополнительно снижает КД на 1. [Хроно-брейк] больше не имеет КД. Наносимый урон увеличивается на 5% за каждый навык, который находится не в перезарядке.",
        "ATK +10%. [Time Flux] additionally reduces all triggers CD by 1. [Chrono Break] no longer has CD. Damage dealt increases by 5% for each skill that is not on cooldown."
    ],
    [
        "Рэйчел",
        "Rachel",
        "Защитный рунный костюм",
        "Protective rune suit",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +5%. Перед вынужденным вступлением в ближний бой, наносит врагу фиксированный урон 1 раз. Урон = 1х ИНТ героя.",
        "HP +5%. When forced into battle by a melee attack, deals fixed damage to the enemy 1 time equal to 1x Hero's INT."
    ],
    [
        "Рейнфорс",
        "Rainforce",
        "Сердце Красной Луны",
        "Heart of the Red Moon",
        "accessoir",
        "",
        "75",
        "",
        "",
        "",
        "37",
        "ATK +5%, Мобильность +1. Когда у вас есть минимум 4 эффекта [неземной силы], всегда можете проходить сквозь врагов во время движения. Когда у вас есть 7 эффектов [неземной силы], после нанесения урона накладывает на вражеского юнита мощный дебафф.",
        "ATK +5%, Movement +1. When this unit has 4 or more stacks of [Otherworldly Force], then it may ignore enemy unit obstruction. When this unit has 7 stacks of [Otherworldly Force], then inflict 1 random debuff on enemies after dealing damage."
    ],
    [
        "Рената",
        "Renata",
        "Драконья корона",
        "Dragonspeak crown",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ & МЗАЩ +5%. Дебафф, накладываемый на врагов, длится еще 1 ход. [Помощь] при каждой активации вашего таланта получает эффект [наездник ветра] и иммунитет к эффектам снижения атаки и интеллекта и эффектам, заглушающим активные навыки. Длится 2 хода. Может получать преимущество от эффекта энергии слияния [метеоритный удар].",
        "HP & MDEF +5%. Duration of debuffs inflicted on enemies +1. Any time this unit's Talent is triggered, gain [Windride] and immunities to ATK/INT decreases and silence. Lasts 2 turns. This unit may receive [Meteor Strike] Fusion Power effects."
    ],
    [
        "Рикки",
        "Ricky",
        "Настоящий герой",
        "A real hero",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ and ЗАЩ +5%. Вступая в бой с вражескими юнитами в оборонительном направлении, герой наносит на 10% больше урона. Если на поле боя есть Шельфаниэль, обе стороны наносят на 5% больше урона от умений.",
        "HP and DEF +5%. When battling enemies in this unit's defense direction, Hero Damage Dealt +10%. If there is an allied unit named 'Shelfaniel' on the map, both units gain Skill Damage +5%."
    ],
    [
        "Роланд",
        "Roland",
        "23.05.2024",
        "Clandestine Dawn",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +10%.  При переключении формы, количество ходов баффов не уменьшается. Если у юнита есть [Грань проницательности] и за ход не был нанесен урон, в конце хода получает 'Мобильность +2', длится 1 раунд. Если у юнита есть [Карающий свет], может передвинуться на 2 клетки после атаки.",
        "HP +10%. When switching forms, the number of buffs does not decrease. If a unit has [Edge of Insight] and no damage was dealt during the turn, at the end of the turn gains 'Mobility +2', lasts 1 round. If a unit has [Punishing Light], it can move 2 tiles after an attack."
    ],
    [
        "Розалия",
        "Rozalia",
        "Лезвие Света",
        "Light blade",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "ATK +10%. Когда герой находится в пределах радиуса действия «меча защиты», местность не влияет на мобильность, а шанс получения крит.урона уменьшается на 20%.",
        "ATK +10%. When this unit is in the range of [Sword of Protection], movement is not limited by terrain, and chance of bring critically hit -20%."
    ],
    [
        "Розенцель",
        "Rozenciel",
        "Сверкающая чистая вуаль",
        "Sparkling clear gauze",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. За каждый слой кристаллического барьера, который у вас есть, лечебный эффект увеличивается на 3%. Когда герой умирает, восстанавливает жизнь другим союзникам в пределах 2 клеток на 2х ИНТ.",
        "HP +10%. For each layer of Crystall Barrier you have, the healing effect is increased by 3%. When a hero dies, restores HP to other allies within 2 tiles for 2x INT."
    ],
    [
        "Отшельник",
        "Sage of the Trees",
        "Старая повязка",
        "Ancient belt",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Дальность обычной атаки +1. После инициирования боя накладывает «слепящий свет» на цель и цели в радиусе 1 блока. Длится 1 ход.",
        "HP +10%. Unit's normal attack range+1. After actively attacking in battle, create [Dazzling Light] terrain on the tile the target is on, as well as tiles within 1 block. Lasts 1 turn."
    ],
    [
        "Сагани",
        "Sagny",
        "Снежные Ритуальные Одеяния",
        "Snow Ritual Robes",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +10%. Снежную сову можно переместить +1 дополнительный раз. Когда в радиусе 6 клеток от Сагани есть снежная сова, при получении фатального урона не умирает (1 раз за бой)",
        "HP +10%. After releasing [Cold Sharp Eyes], you can choose to move the 'Snowy Owl' +1 times. When there is a 'Snowy Owl' released by itself within 6 tiles, it cannot be fatally hit (it can be triggered once per battle at most)."
    ],
    [
        "Дева ковчега",
        "Saint of the Ark",
        "Корона рассвета",
        "Crown of dawn",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Когда в радиусе 1 кольца есть 2 и более других союзных юнитов [конвергенция света] больше не наносит урон союзникам, а получаемые лечебные эффекты усиливаются на 8%.",
        "HP +10%. When there are at least 2 allies within 1 ring, Darklight Synthesis will not deal damage to allies, and recieved healing effects +8%."
    ],
	[
        "Серафина",
        "Seraphina",
        "Глобал - 06.03.2025",
        "Global - 06.03.2025",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ +10%. При прохождении сквозь врагов, накладывает на них 1 дебафф; при использовании умения накладывает 1 мощный дебафф на врагов, которым умение нанесло урон (включая фиксированный урон).",
        "HP +10%. When passing through enemies, applies 1 debuff to them; when using a skill, applies 1 powerful debuff to enemies that were damaged by the skill (including fixed damage)."
    ],
    [
        "Селина",
        "Serene",
        "Рассветный страж",
        "Dawnguard",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ +10%. Все союзные юниты, у которых менее 80% ОЗ, в радиусе 3 клеток считаются «павшими солдатами».",
        "DEF +10%. Allies within 3 blocks with under 80% HP are considered as having no soldiers."
    ],
    [
        "Шельфаниэль",
        "Shelfaniel",
        "Корона Каконсиса",
        "Caconsis's crown",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "МЗАЩ +10%. После совершения действия есть 30% шанс получить +1 к дальности навыков и +1 к диапазону. Длится 1 ход.",
        "MDEF +10%. 30% chance after taking action to gain 'Skill range +1, skill span +1'. Lasts 1 turn."
    ],
    [
        "Шилинка",
        "Shilinka",
        "Маска с перьями",
        "Plumed mask",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ЗАЩ +10%. При инициировании боя наносимый урон увеличивается на 12%. Баффы, которые вы накладываете на себя, длятся на 1 ход дольше. Когда имеете статут «дрёма», ваши активные баффы не теряют свой счетчик ходов.",
        "DEF +10%. When actively attacking and entering battle, damage dealt +12%. Buffs given to self have duration +1. When in Slumber status, buffs on this unit will not decrease in duration."
    ],
    [
        "Сигма",
        "Sigma",
        "Предельная точность",
        "Precision scope",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +5%. После совершения действия может с 25% шансом повысить свою АТК на 20%. Длится 4 хода.",
        "HP +5%. After taking action, 25% to gain 'ATK +20%'. Lasts 4 turns."
    ],
    [
        "Серебряный Волк",
        "Silver Wolf",
        "Маска благочестия",
        "Mask of righteousness",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "МЗАЩ +5%. При инициировании боя вы можете атаковать первым, если у вас в 2 раза больше баффов, чем у противника.",
        "MDEF +5%. When initiating battle, if you have at least twice as many buffs as the enemy, you can attack first."
    ],
    [
        "Сисси Уайт",
        "Sissi White",
        "Деловая хватка",
        "Business mind",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. В начале хода с 50% шансом получает эффект [монета войны] 2 раза. В случае неудачи шанс увеличивается на 50%. После получения шанс сбрасывается до 50%.",
        "HP +10%. At the start of a turn, have a 50% chance to gain 2 [War Tokens]. If this does not occur, then the next turn increase this chance by 50%. Afterwards, the chance returns to 50%."
    ],
    [
        "Соня",
        "Sonya",
        "Темный рассвет",
        "Dark dawn",
        "weapon",
        "",
        "107",
        "107",
        "",
        "",
        "",
        "ATK & ИНТ +10%. Перед началом ближней атаки наносит фиксированный урон врагу 1 раз. Урон = 2х ИНТ героя. После активной атаки в дальнем бою наносит фиксированный урон врагу 1 раз. Урон = 2х АТК героя.",
        "ATK & INT +10%. Before melee attacking and entering battle, deal fixed damage once equal to Hero's INT x2. After ranged attacking and entering battle, deal fixed damage once equal to Hero's ATK x2."
    ],
    [
        "София",
        "Sophia",
        "Потерянный свет",
        "Lost light",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +5%. Применяя навыки на союзных юнитов, дополнительно накладывает: АТК и ИНТ повышается на 15%, а МЗАЩ повышается на 20%. Длится 2 хода.",
        "HP +5%. When casting skills on allies, also grant: 'ATK, INT +15%' and 'MDEF +20%'. Lasts 2 turns."
    ],
    [
        "Сюзетт",
        "Suzette",
        "Судья Света",
        "Glorious adjudicator",
        "weapon",
        "",
        "107",
        "",
        "",
        "",
        "43",
        "ATK +10%. Может получать преимущества от эффекта «энергии слияния» [Легиона Света]. Навыки с АОЕ-уроном становятся одиночными, шанс крита героя увеличивается на 3% за каждую 1 клетку расстояния до цели (до 15%).",
        "ATK +10%. May receive 'Legion of Glory' Fusion Power effects. AoE skills now target tiles. The further this unit is from its targets, the greater the critical hit rate, giving +3% critical hit rate per block (up to 15%)."
    ],
    [
        "Меч Света и Тьмы",
        "Sword of Light and Shadow",
        "Глобал - 29.02.2024",
        "Intertwined Wishes",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ и ЗАЩ +5%. Когда сражается с врагом у которого есть [сопротивление смертельнмоу урону], АТК и ЗАЩ войск увеличиваются на 10%. После получения смертельного урона и срабатывании таланта, на клетке героя появится [осколок души]. (Перезарядка того эффекта 3 хода).",
        "HP and DEF +5%. When fighting an enemy who has [lethal damage resistance], ATK and DEF increases by 10%. After receiving fatal damage and triggering the talent, a [soul fragment] will appear on the hero’s cell. (Recharge of that effect 3 turns)."
    ],
	[
        "Табрес",
        "Tabres",
        "Глобал - 09.01.2025",
        "Global - 09.01.2025",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. Когда враг атакует союзника и наносит ему урон, этот враг получает 1 слой [Тёмных перьев]. При использования навыка для инициирования боя, время восстановления этого навыка уменьшается на 1 ход за каждый слой [Тёмных перьев] у врага.",
        "HP +10%. When an enemy attacks and damages an ally, that enemy gains 1 layer of [Shadow Feathers]. When using a skill to initiate combat, the cooldown time of this skill is reduced by 1 turn for each layer of [Shadow Feathers] the enemy has."
    ],
    [
        "Таталия",
        "Tatalia",
        "Наказание зла",
        "Vigilante's Visage",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ, ЗАЩ +5%. Когда сражается с врагом и в радиусе 3 клеток от него есть враг с [восприятием зла], наносимый урон увеличивается на 10%. После того как Темное пожирание (3С) убьёт врага, в конце действия получает 'Когда ОЗ 70% и выше, персонажа нельзя выбрать целью атаки или умения'. Действует 1 раунд",
        "HP DEF +5%. When fighting with enemies within 3 tiles of the enemy unit with [Evil Thought Perception], the damage dealt is increased by 10%. After using [Evil Thought Devour] (3С) to kill the enemy, at the end of the action, you will get 'When the unit's HP is above 70%, it cannot be targeted by the enemy's normal attack and skills', which lasts for 1 round."
    ],
    [
        "Теон",
        "Theon",
        "Капюшон тайной мощи",
        "Cowl of furtive might",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%. После восстановления вращающегося лезвия получаемый урон будет уменьшен на 20%, длится 1 раунд. В конце действия вращающееся лезвие будет сгенерировано в случайном месте врага в пределах 10 клеток. (Перезарядка 2 раунда. В ПВП режиме диапазон генерации увеличивается до всего поля).",
        "Life +10%. After recovering the whirling blade, the received damage is reduced by 20%, which lasts for 1 round. At the end of the action, a [Whirling Blade] will be generated randomly at the position of an enemy within 10 tiles. ([Trigger cooldown] This effect can only be triggered again after an interval of 2 rounds. In the competitive mode, the generation range is increased to the whole field)"
    ],
    [
        "Тиарис",
        "Tiaris",
        "Надежды девушки",
        "A girl's hopes",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. При использовании умения на одиночную цель союзника, он также получает эффект: наносит на 30% больше урона и получает только половину урона в бою. Длится 1 ход.",
        "HP +10%. After using single target skills on allies, also grant 'When attacking and entering battle, damage dealt +30%, and damage taken is reduced by half.' Lasts 1 turn."
    ],
    [
        "Тормил",
        "Tourmilque",
        "Глобал 25.04.2024",
        "Silent Confession",
        "body",
        "364",
        "",
        "",
        "65",
        "",
        "",
        "ОЗ +10%. В начале хода, преобразовывает 1 стак [Перцептивный] или [Рациональный] (смотря что ниже) в другой. Чем меньше разница в стаках [Перцептивный] и [Рациональный], тем больше увеличивается наносимый героем урон (до 10% при равных стаках).",
        "HP +10%. At the start of the turn, converts 1 stack of [Perceptual] or [Rational] (whichever is lower) into another. The smaller the difference in the [Perceptive] and [Rational] stacks, the more the damage dealt by the hero increases (up to 10% for equal stacks)."
    ],
    [
        "Това",
        "Towa",
        "Очки духовного зрения",
        "Spirit vision goggles",
        "hat",
        "583",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ & ЗАЩ +5%. Когда у этого героя есть особый эффект «сила синтеза», урон, наносимый при атаке и вступлении в бой увеличивается на 10%. Если у врага нет «силы синтеза», его АТК и ИНТ уменьшается на 15% перед битвой. Длится 1 ход.",
        "HP & DEF +5%. When this unit has a special effect from a Fusion Power, when attacking and entering battle increase damage dealt by 10%. If at the same time the target does not have a special effect from a Fusion Power, before battle inflict 'ATK/INT -15%'. Lasts 1 turn."
    ],
    [
        "Трансцендентный",
        "Transcender",
        "Обруч бесконечности",
        "Endless loop",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Когда герой инициирует бой, наносимый урон увеличивается на 15%. Получает эффект [созидание и разрушение] в начале битвы. Когда используется «поворот судьбы», этот юнит крадёт у цели 3 дополнительных баффа.",
        "HP +10%. When this hero attacks in battle, damage dealt +15%. Before entering battle, gain 1 stack of [Force of Annihilation]. When using Reversal of Fate, steal 3 buffs from the target."
    ],
    [
        "Цубамэ",
        "Tsubame",
        "Собиратель звёзд",
        "Shadow star cowl",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ+10%. Наносимый урон увеличивается на 10%. Получаемый АОЕ-урон снижается на 10%. Когда у этого героя имеется эффект «скрытая тень» крит урон увеличивается на 15%. После совершения действия получает эффект [гонка]: мобильность +1. Может накладываться 2 раза. Длится 2 хода.",
        "HP +10%. Damage dealt +10%, AoE damage taken -10%. When this unit has [Hide], critical hit rate +15%, and after taking action, gain [Haste]: 'Movement +1. Can be stacked up to 2 times.' Lasts 2 turns."
    ],
	[
        "Тирантир",
        "Tyrantel",
        "Глобал - 06.02.2024",
        "Global - 06.02.2024",
        "hat",
        "483",
        "",
        "",
        "",
        "48",
        "",
        "ОЗ +10%. Рассеивает 1 бафф с врага перед сражением если на нём есть [Печать превосходства] и восстанавливает 30% ОЗ от нанесённого урона после битвы. Если враг с [Печать превосходства] умрет, получает 'Может выбрать дополнительную цель при следующем использовании [Печать превосходства]', не может быть заимунено и снято.",
        "HP +10%. Dispels 1 buff from the enemy before the battle if enemy has [Seal of Superiority] and restores 30% of HP from the damage dealt after the battle. If an enemy with [Seal of Superiority] dies, gains 'Can choose an additional target the next time you use [Seal of Superiority]', cannot be immunized and removed."
    ],
    [
        "Варгас",
        "Vargas",
        "Слава великого дракона",
        "Great dragon's glory",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ +10%. Если у вас есть эффект [мощный удар], вы можете контратаковать в ответ на дальние атаки в радиусе 2 клеток.",
        "DEF +10%. If this character is under the effect of [Power Stab], then may counterattack a ranged attack from 2 range."
    ],
    [
        "Варна",
        "Varna",
        "Крылатый шлем",
        "Wingstriker helmet",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "МЗАЩ +10%. При использовании наыков с АОЕ-уроном эффективная дальность увеличивается на 1. [Активация КД] когда наносите урон с помощью АОЕ-навыка, активируется КД этого эффекта. Этот эффект активируется повторно через 4 хода.",
        "MDEF +10%. When using AoE damage skills, span +1. This effect has a cooldown of 4 turns."
    ],
    [
        "Винсент",
        "Vincent",
        "Крылья войны",
        "Wings of war",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "За каждую 1 пройденную клетку шанс крита увеличивается на 1% (до 3%). Когда атакует и наносит крит.удар, рассеивает с врага 1 бафф.",
        "For every 1 block moved, critical hit rate +5% (up to 15%). After actively dealing critical damage, dispel 1 buff from the enemy."
    ],
    [
        "Вираш",
        "Virash",
        "Молниеносные латы",
        "Blitz bulwark",
        "body",
        "437",
        "",
        "",
        "65",
        "",
        "",
        "ЗАЩ +10%. Когда герой активирует эффект, предотвращающий смертельный урон, накладывается 1 случайный бафф.",
        "DEF +10%. When hero triggers an effect that prevents fatal damage, gain 1 random buff."
    ],
    [
        "Странствующий Дуэлянт",
        "Wandering Dualist",
        "Одеяние дуэлянта",
        "Duelist's garb",
        "body",
        "509",
        "",
        "",
        "59",
        "",
        "",
        "ЗАЩ +10%. В начале боя герой получает на 30% меньше урона. Если у цели есть [цепи возмездия], получаемый урон уменьшается еще на 20%.",
        "DEF +10%. When attacking and entering battle, unit damage taken -30%. If the target has [Chain of Vengeance], damage taken is further reduced by 20%."
    ],
    [
        "Ютем",
        "Wehttam",
        "Повелитель Демонов",
        "Demon overlord",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +10%, При входе в бой против цели у которой есть эффект 'отчаяние' урон увеличивается на 10%. При использовании умения перезарядка -1.",
        "Life +10%, When entering the battle, if the target has [Despair], the damage dealt by the hero will be increased by 10%, and if a skill is used, the cooldown time of the skill will be -1."
    ],
    [
        "Вернер",
        "Werner",
        "Плащ Ветрохода",
        "Windwalker's cloak",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ЗАЩ +10%. Получает [ударную стойку] в начале битвы. В [ударной стойке], если герой не двигался перел активной атакой он получает [ударную стойку] после битвы.",
        "DEF +10%. At the start of a map, gain [Strike Stance]. When in [Strike Stance], if no blocks were moved before attacking, after battle gain [Strike Stance]."
    ],
    [
        "Вернер Дайм",
        "Werner Dime",
        "Механизированный меч",
        "Blade of mobile mayhem",
        "weapon",
        "437",
        "107",
        "",
        "",
        "",
        "",
        "ATK +10%. При инициировании боя герой игнорирует 1% защиты врага за каждую пройденную клетку.",
        "ATK +10%. Before attacking and entering battle, for every block moved ignore 1% of enemy's DEF."
    ],
    [
        "Вилер",
        "Wiler",
        "Звёздный адмирал",
        "Starsea admiral",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +10%. Когда у героя не более 50% ОЗ получает иммунитет к фиксированному урону. После использования навыка может с 50% шансом уменьшить его КД на 2 хода.",
        "HP +10%. When the hero is equal to or below 50% HP, he is immune to fixed damage. After using a skill, 50% chance to lower that skill's cooldown by 2."
    ],
    [
        "Юная Джессика",
        "Young Jessica",
        "Провидец",
        "Scryer",
        "hat",
        "364",
        "",
        "",
        "",
        "65",
        "",
        "ОЗ +5%. Если этот герой не наносил урон и не двигался на этом ходу он может действовать снова. [активация КД] КД эффекта «повторное действие» составляет 4 хода.",
        "HP +5%. After taking action, if this unit has not moved or dealt damage this turn, then may act again. This effect has a 4 turn cooldown."
    ],
    [
        "Юлия",
        "Yulia",
        "Вуаль богини",
        "Diva's veil",
        "body",
        "583",
        "",
        "",
        "54",
        "",
        "",
        "ОЗ +10%. Когда активируется талант героя и спасает от смерти при получении смертельного урона, он получает следующий эффект на 1 ход: перед вступлением в бой наносит врагу фиксированный урон, равный 2х от ИНТ заклинателя, и восстанавливает ОЗ в размере 2х от ИНТ заклинателя.",
        "HP +10%. When the hero activates the revive effect in her talent, gain 'Before entering battle, deals fixed damage equal to 2x INT and heal self for 2x INT.' Lasts 1 turn."
    ],
    [
        "Зерида",
        "Zerida",
        "Теплые воспоминания",
        "Scarlet embrace",
        "hat",
        "437",
        "",
        "",
        "",
        "59",
        "",
        "ОЗ +5%. После совершения действия, если в радиусе 2 клеток нет союзных юнитов, восстанавливает 20% ОЗ и снимает 1 дебафф.",
        "HP +5%. After taking action, if no friendly units are within 2 blocks, restore 20% HP and dispel 1 debuff."
    ]
]

function persItemView (itemType) {
	console.log('kjljk');
	var id = document.getElementById('item_data');
	id.innerHTML = '';
	//id.innerHTML = persItemDat[111][8];
	var i;
	for (i=1;i<persItemDat.length;i++){
		if (persItemDat[i][4]==itemType){
			if (persItemDat[i][5]!=''){var oz='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">HP: ' + persItemDat[i][5] + '</span>'}else{var oz=''};
			if (persItemDat[i][6]!=''){var atk='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">ATK: ' + persItemDat[i][6] + '</span>'}else{var atk=''};
			if (persItemDat[i][7]!=''){var intt='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">INT: ' + persItemDat[i][7] + '</span>'}else{var intt=''};
			if (persItemDat[i][8]!=''){var def='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">DEF: ' + persItemDat[i][8] + '</span>'}else{var def=''};
			if (persItemDat[i][9]!=''){var mdef='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">MDEF: ' + persItemDat[i][9] + '</span>'}else{var mdef=''};
			if (persItemDat[i][10]!=''){var crit='<img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:10px;">SKILL: ' + persItemDat[i][10] + '</span>'}else{var crit=''};
			if (persItemDat[i][0]=='Ашемар'){descr ='<span style="font-size:16px;font-style:italic;">'}else{descr ='<span style="font-size:18px;font-style:italic;">'};
			hreff = ('hero_en.html?name='+ persItemDat[i][0]).replace(/ /g,"%20");
			id.innerHTML += '<div style="display:block;width:95%;height:145px;"><div style="display:block;width:150px;float:left;position:relative;"><img style="position:absolute;" src="images/itemIcons/all/' + persItemDat[i][0] + 
			'.png" height="120px" /><a href="'+hreff+'"><img style="position:absolute;top:65px;right:-10px;" title="' + persItemDat[i][1] + '" src="images/head_circle/' + persItemDat[i][0] + '.png" height="70px" /></a></div><div style="display:block;width:700px;float:left;margin-left:164px;"><b style="font-size: 23px;margin-right: 50px;float:left;">' + persItemDat[i][3]+ 			'</b>' +
//			'<img src="images/Move_Walk.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][6] + 
//			'</span> <img src="images/Icon_Range.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][7] + 
//			'</span> <img src="images/icon.png" height="25px" />
			'<div style="display: block;float: left;padding-top: 4px;">'  + oz + ' ' + atk + ' ' + intt + ' ' + def + ' ' + mdef + ' ' + crit +
			'</div></div><br><br><div style="white-space: normal;margin-left:164px;">' + descr + persItemDat[i][12]  + 
			'</div></div>';
		}
	}
}
