// soldDat.length  -  колл-во всех солдат
// soldDat[0].length  -  колл-во элементов у солдат
// 0 - имя рус, 1 - имя англ., 2 - ОЗ, 3 - атк, 4 - защ, 5 - мзащ, 6 - мобильность, 7 - дальность, 8 - описание рус, 9 - описание англ., 10 - класс войска, 11 - герои, 12 - тип передвижения
var soldDat = [
    [
        "NAME RUS",
        "NAME ENG",
        "HP",
        "ATK",
        "DEF",
        "MDEF",
        "MOBILITY",
        "RANGE",
        "DESC RUS",
        "DESC ENG",
        "CLASS",
        "HEROES",
        "Move type (ходьба, полет, пловец, всадник, парение)"
    ],
	[
        "Колдун SP",
        "Wizard SP",
        "36",
        "40",
        "22",
        "22",
        "3",
        "2",
        "Весь физический урон, нанесённый обычными атаками, рассматривается как магический урон. При активной атаке и вступлении в бой, АТК солдат +45%, а урон контратаки дальнего боя снижается на 25%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Колдун.jpg'>(Условия&nbsp;SP)</a>",
        "All physical damage dealt by normal attacks is treated as magic damage. When actively attacking and entering combat, soldier's ATK +45%, and ranged counterattack damage is reduced by 25%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Wizard.jpg'>(SP&nbsp;terms)</a>",
        "mage",
        "Альмеда,Джессика,Хейн,Эгберт,Лиффани,София,Бозел,Лана,Лиана,Герольд и Лайла,Шельфаниэль,Рене,Вилер,Гизаров,Ламбда,Айрис,Анжелика,Курама,Юная Джессика,Ака,Дидлит,Майя,Ликорис,Алтина,Ноэми,Отшельник,Флоренция,Айнз,Мелания,Аватар Света,Злой Бог Крюгер,Лукреция,Мю,Кертес,Дева Ковчега,Густав,Аданкельмо,Лео Бек,Сагани,Тормил,Джесс,Селика,Вирелия,Эния,Алия,Илия,Сафрин,Хумбаба,Линн,Ранка,Саллун,Кумо",
        "ходьба"
    ],
	[
        "Паучий эльф-демон SP",
        "Spider Demon Elf SP",
        "43",
        "43",
        "22",
        "22",
        "5",
        "2",
        "Весь физический урон, нанесённый обычными атаками, рассматривается как магический урон. При активной атаке игнорирует 20% МЗАЩ врага и игнорирует недостаток класса. Перед боем накладывает на врага мобильность -3 на 1 ход. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Паучий эльф-демон.jpg'>(Условия&nbsp;SP)</a>",
        "All physical damage dealt by normal attacks is treated as magic damage. When active atack,ignores 20% of enemy's MDEF and ignores class disadvantage. Applies -3 mobility to enemy for 1 turn before combat. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Spider Demon Elf.jpg'>(SP&nbsp;terms)</a>",
        "demon",
        "Эгберт,Соня,Герольд и Лайла,Ака,Ноэми,Айнз,Кертес,Дева Ковчега,Лео Бек,Феракуа,Злой Бог Крюгер,Патцир,Пробужденная,Юске,Ланделл,Силрна,Хумбаба,Непокорная небесам,Бозена",
        "ходьба"
    ],
	[
        "Святой рыцарь SP",
        "Holy Knight SP",
        "38",
        "34",
        "22",
        "26",
        "5",
        "2",
        "Весь физический урон, нанесённый обычными атаками, рассматривается как магический урон. Сила исцеления героя +15%. Юнит не тратит очки мобильности при движении сквозь союзников. В конце действия восстанавливает 30% ОЗ союзников сквозь которых прошел в этот ход. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Святой рыцарь.jpg'>(Условия&nbsp;SP)</a>",
        "All physical damage dealt by normal attacks is treated as magic damage. Hero's healing power is increased by 15%. Unit does not spend mobility points  when moving through allies. At the end of the action, restores 30% of HP of allies it passed through this turn. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Holy Knight.jpg'>(SP&nbsp;terms)</a>",
        "holy",
        "Имельда,Тиарис,Герольд и Лайла,Айрис,Альмеда,Люгнер,Ашемар,Эльма,Сисси Уайт,Селика,Эния",
        "парение"
    ],
	[
        "Служанка в маске SP",
        "Masked Maid SP",
        "43",
        "43",
        "23",
        "23",
        "3",
        "1",
        "АТК, ЗАЩ И МЗАЩ +15%. При сражении с врагом у которого процент ОЗ равный или ниже вашего этот эффект удваивается. Перед вступлением в бой наносит противнику фиксированный урон равный 5% от текущего ОЗ (если у противника смешанные силы, этот фиксированный урон игнорирует имунитет). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Служанка в маске.jpg'>(Условия&nbsp;SP)</a>",
        "ATK, DEF AND MDEF +15%. When fighting an enemy whose HP is equal to or lower than yours, this effect is doubled. Before entering combat, deals a fixed damage to the enemy equal to 5% of current HP (if the enemy has mixed forces, this fixed damage ignores immunity). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Masked Maid.jpg'>(SP&nbsp;terms)</a>",
        "sword",
        "Левин,Ледин,Элвин,Оливиер,Кларетт,Юлия,Кадзума,Арес,Майя,Рё,Мишель,Рикки,Элейн,Соня Бланш,Гаури,Капитан Джек,Эйшин,Тиана,Мари Роуз,Серафина,Лостхэм,Бетти,Леонхарт,Фрейя,Лея,Эльза,Рапьер,Сибель,Первобытная Зерида",
        "ходьба"
    ],
	[
        "Солдат-драконианец SP",
        "Dragon Trooper SP",
        "45",
        "45",
        "23",
        "22",
        "5",
        "1",
        "При наличии эффекта увеличения мобильности, получаемый урон -20%. АТК солдат увеличивается на 10% за каждую пройденную клетку до атаки (до 30%). При перемещении более 3 клеток за ход, получает +2 к мобильности в конце действия или перед вступлением в бой. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Солдат-драконианец.jpg'>(Условия&nbsp;SP)</a>",
        "If there is a mobility increase effect, damage taken is -20%. Soldiers ATK is increased by 10% for each tile passed before the attack (up to 30%). When moving more than 3 tiles per turn, gets +2 to mobility at the end of the action or before entering combat. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Dragon Trooper.jpg'>(SP&nbsp;terms)</a>",
        "fly",
        "Кит,Ланс,Алтемюллер,Шери,Ашрам,Рената,Шалтир,Ватару,Това,Оборо,Странствующий Дуэлянт,Эксела,Изольда,Макишима Агито,Тирантир,Ниотэнгу,Драконоборец,Хелена,Апофеоз,Рыцарь Тайн,Табрес,Зион,Лукман,Элвис,Нацу,Шарик,Лила,Д-мен,Банши,Реига",
        "полет"
    ],
	[
        "Танцующая в тумане SP",
        "Mist Dancer SP",
        "40",
        "43",
        "22",
        "26",
        "3",
        "1",
        "Шанс критического удара +45%. АТК +15% при сражении с героями не являющимися женщинами.Накладывает перед атакой 1 случайный дебафф. При активации критического удара, накладывает на врага еще 1 случайный дебафф после атаки. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Танцующая в тумане.jpg'>(Условия&nbsp;SP)</a>",
        "Critical Hit Chance +45%. ATK +15% when fighting non-female heroes.Applies 1 random debuff before attack. When a critical hit is activated, applies another 1 random debuff to the enemy after the attack. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Mist Dancer.jpg'>(SP&nbsp;terms)</a>",
        "assasin",
        "Альмеда,Серебряный Волк,Феракуа,Шери,Зерида,Джошуа,Оливиер,Анжелика,Пиротесс,Цубамэ,Химико,Патцир,Каюра,Сельвария,Теон,Кирика,Таталия,Серафина,Тиана,Нож Марк и Ниндзя Гиндзу,Касуми,Макира,Глаз обмана,Шарик,Миюки",
        "ходьба"
    ],
	[
        "Темный эльф-снайпер SP",
        "Dark Elf Sniper SP",
        "35",
        "43",
        "20",
        "26",
        "3",
        "2",
        "При входе в бой АТК и ЗАЩ увеличиваются на 30%. Когда у солдат 100% ОЗ, ЗАЩ противника перед боем снижается на 25%, блится 1 раунд. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Темный эльф-снайпер.jpg'>(Условия&nbsp;SP)</a>",
        "When entering battle, ATK and DEF increase by 30%. When soldiers have 100% HP, the enemy's DEF before battle is reduced by 25%, lasts 1 round. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Dark Elf Sniper.jpg'>(SP&nbsp;terms)</a>",
        "bow",
        "Метью,Серебряный Волк,Феракуа,Кирикадзе,Варна,Соня,Лиффани,Эгберт,Имельда,Бозел,Лана,Зерида,Герольд и Лайла,Джошуа,Рэйчел,Сигма,Ламбда,Анжелика,Алустриэль,Омега,Хией,Юная Джессика,Пиротесс,Айнз,Аватар Света,Патцир,Каюра,Лукреция,Сюзетт,Кертес,Дева Ковчега,Густав,Лиза,Сельвария,Алисия,Исара,Ашемар,Лостхэм,Джулиан,Маклейн,Аданкельмо,Девушка в Доспехах,Лео Бек,Теон,Джо и Конни,Агнес,Пробужденная,Кирика,Нимфа,Таталия,Зелгадис,Неемия,Вирелия,Тиана,Птица с поломанным крылом,Ланделл,Силрна,Макира,Тадж,Муллин,Бозена",
        "ходьба"
    ],
	[
        "Эльфийский метатель копья SP",
        "Elven Spear Thrower SP",
        "46",
        "43",
        "24",
        "22",
        "3",
        "1",
        "АТК увеличивается на 30%. Когда атакован дальним боем и вступает в бой, может контратаковать, а получаемый урон снижается на 20%. Если находится в «лесах», «горах» и «лугах», юнит будет атаковать раньше врага. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Эльфийский метатель копья.jpg'>(Условия&nbsp;SP)</a>",
        "ATK increases by 30%. When attacked with a ranged attack and enters battle, can counterattack and damage taken is reduced by 20%. If is in “forests”, “mountains” and “grasslands”, the unit will attack before the enemy. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Elven Spear Thrower.jpg'>(SP&nbsp;terms)</a>",
        "lance",
        "Лана,Лэндиус,Алустриэль,Эмилия,Ака,Дидлит,Отшельник,Флоренция,Мю,Вернер,Мариандель,Кагуя,Ван,Соня Бланш,Алканфель,Хильда,Оборо,Гренье,Альфа,Хофманн",
        "ходьба"
    ],
	[
        "Левиафан SP",
        "Leviathan SP",
        "43",
        "40",
        "24",
        "19",
        "3",
        "2",
        "При активной атаке и вступлении в бой АТК увеличивается на 45%. В воде вероятность критического удара увеличивается на 40%, не подвержен снижению урона в ближнем бою. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Левиафан.jpg'>(Условия&nbsp;SP)</a>",
        "When actively attacking and entering battle, ATK increases by 45%. In water, the chance of a critical hit increases by 40% and damage in melee battle doesn't reduce. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Leviathan.jpg'>(SP&nbsp;terms)</a>",
        "water",
        "Диос,Феракуа,Шельфаниэль,Гизаров,Сигма,Омега,Хией,Оливер,Пиротесс,Ликорис,Девушка в Доспехах,Пробужденная,Маклейн,Анджелина,Лестер,Джаглер,Вираш,Силрна,Глаз обмана",
        "пловец"
    ],
	[
        "Орк-берсерк SP",
        "Orc Berserker SP",
        "45",
        "43",
        "22",
        "17",
        "3",
        "1",
        "АТК солдат увеличиваются на 30%. При атаке в ближнем бою, АТК солдат в бою дополнительно увеличивается на 15%. После боя наносит дополнительный урон, равный 15% от максимального ОЗ противника. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Орк-берсерк.jpg'>(Условия&nbsp;SP)</a>",
        "Soldier ATK increase by 30%. When attacking in melee combat, soldiers ATK in battle is additionally increase by 15%. After battle deals additional damage equal to 15% of the enemy's maximum HP. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Orc Berserker.jpg'>(SP&nbsp;terms)</a>",
        "sword",
        "Метью,Варгас,Эмерик,Джаглер,Гизаров,Юске,Тогуро,Бетти,Эмилия,Ашрам,Рената,Айнз,Альфа,Ютем,Апофеоз,Имир,Зион,Ганн,Элвис,Сибель",
        "ходьба"
    ],
	[
        "Епископ SP",
        "Bishop SP",
        "37",
        "34",
        "22",
        "28",
        "3",
        "2",
        "Весь физический урон, нанесённый обычными атаками, рассматривается как магический урон. Сила исцеления героя +15%. Когда ОЗ солдат выше 80%, ЗАЩ и МЗАЩ союзников в радиусе 2 клеток увеличивается на 10%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Епископ.jpg'>(Условия&nbsp;SP)</a>",
        "All physical damage dealt by normal attacks is treated as magic damage. The hero's healing efficiency increases by 15%. When soldier's HP above 80%, DEF and MDEF of allies within a radius of 2 tiles increas by 10%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Bishop.jpg'>(SP&nbsp;terms)</a>",
        "holy",
        "Альмеда,Анна,Крис,София,Хейн,Имельда,Лана,Лиана,Тиарис,Шельфаниэль,Рэйчел,Вилер,Ламбда,Айрис,Юная Джессика,Ликорис,Ноэми,Флоренция,Мелания,Розенцель,Аватар Света,Сисси Уайт,Каюра,Лукреция,Мю,Мариандель,Эльма,Кагуя,Ашемар,Аданкельмо,Люгнер,Агнес,Сагани,Тормил,Джесс,Селика,Яркий призыватель,Эния,Алия,Илия,Макира,Линн,Ранка",
        "ходьба"
    ],
	[
        "Королевская кавалерия SP",
        "Royal Cavalry SP",
        "45",
        "45",
        "24",
        "19",
        "5",
        "1",
        "Чем выше ОЗ солдат, тем меньше физического урона они получают, максимум до 45%. Когда ОЗ солдат выше 70%, их АТК и МЗАЩ увеличиваются на 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Королевская кавалерия.jpg'>(Условия&nbsp;SP)</a>",
        "The higher a soldier's HP, the less physical damage they receive, up to 45%. When soldier's HP is above 70%, ATK and MDEF increase by 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Royal Cavalry.jpg'>(SP&nbsp;terms)</a>",
        "cavalry",
        "Летисия,Лэйд,Эмерик,Леон,Леонхарт,Лэндиус,Хелена,Хильда,Вернер Дайм,Автократо,Каролина,Андриола,Тирантир,Кристиан,Розалия,Ленфорд,Зион,Лея,Шарик",
        "всадник"
    ],
	[
        "Лучник адского пламени SP",
        "Hellfire Archer SP",
        "43",
        "42",
        "20",
        "19",
        "3",
        "2",
        "Воскрешение: после боя восстанавливает 30% потерянного ОЗ. АТК солдат +30%. При вступлении в бой, после боя наносит цели фиксированный урон равный 10% от урона, нанесённого в этом бою. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Лучник адского пламени.jpg'>(Условия&nbsp;SP)</a>",
        "Resurrection: after battle restores 30% of lost HP. Soldier's ATK +30%. When entering battle, after battle, deals fixed damage to the target equal to 10% of the damage dealt in this battle. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Hellfire Archer.jpg'>(SP&nbsp;terms)</a>",
        "demon",
        "Анна,Эгберт,Феракуа,Бозел,Лана,Зерида,Рене,Гизаров,Омега,Курама,Хией,Пиротесс,Айнз,Злой Бог Крюгер,Патцир,Ликорис,Кертес,Густав,Джулиан,Девушка в Доспехах,Лео Бек,Пробужденная,Таталия,Лина,Алканфель,Нож Марк и Ниндзя Гиндзу,Ланделл,Силрна,Глаз обмана,Хумбаба,Бозена",
        "ходьба"
    ],
	[
        "Безликий SP",
        "The Faceless SP",
        "39",
        "45",
        "20",
        "22",
        "3",
        "2",
        "АТК и шанс критического удара +15%. Перед вступлением в бой накладывает на врага повышенный шанс получить критический удар на 15% и повышение получаемого критического урона на 10%. Если вокруг цели в радиусе 1 клетки нет других врагов эти эффекты удваиваются. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Безликий.jpg'>(Условия&nbsp;SP)</a>",
        "ATK and Critical Hit Chance +15%. Before entering combat, applied on enemy a 15% increased chance to receive a critical hit and a 10% increase in critical damage received. If there are no other enemies within 1 tile of the target, these effects are doubled. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/The Faceless.jpg'>(SP&nbsp;terms)</a>",
        "assasin",
        "Рохга,Серебряный Волк,Феракуа,Дихарт,Пиротесс,Шилинка,Цубамэ,Каюра,Вернер,Сельвария,Лостхэм,Джулиан,Таталия,Серафина,Тиана,Нож Марк и Ниндзя Гиндзу,Кирикадзе,Зерида,Омега,Птица с поломанным крылом,Джошуа,Глаз обмана,Лила,Миюки",
        "ходьба"
    ],
	[
        "Маг - ядовитая летучая мышь SP",
        "Poison Bat Mage SP",
        "40",
        "42",
        "18",
        "23",
        "5",
        "2",
        "Обычные атаки, наносящие урон, считаются магическими атаками. При вступлении в бой АТК увеличивается на 40%. Перед боем есть 100% шанс наложить на врага 1 случайный дебафф и 'Ранящее проклятие' (полученное лечение будет преобразовано в урон равный 20% от лечения). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Маг - ядовитая летучая мышь.jpg'>(Условия&nbsp;SP)</a>",
        "Normal attacks that deal damage are considered as magic attacks. When entering combat, ATK increases by 40%. Before combat, there is a 100% chance to applied 1 random debuff and 'Wounding Curse' on the enemy (received healing will be converted to damage equal to 20% of the healing). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Poison Bat Mage.jpg'>(SP&nbsp;terms)</a>",
        "mage",
        "Эгберт,Феракуа,Бозел,Лана,Рене,Алтина,Айнз,Патцир,Трансцендентный,Кертес,Дева Ковчега,Густав,Девушка в Доспехах,Лео Бек,Пробужденная,Лина,Алканфель,Сафрин,Ланделл,Силрна,Альмеда,Кагуя,Зелгадис,Лукреция,Патриция,Глаз обмана,Хумбаба,Бозена",
        "полет"
    ],
    [
        "Темный центурион SP",
        "Dark Centurion SP",
        "48",
        "40",
        "28",
        "18",
        "3",
        "1",
        "Перед вступлением в навязанный бой наносит врагу фиксированный урон, равный 2.5х от ЗАЩ. Во время боя, если процент ОЗ героя выше чем процент ОЗ врага, ЗАЩ и МЗАЩ солдат увеличивается на 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Темный центурион.jpg'>(Условия&nbsp;SP)</a>",
        "Before entering a forced battle, deals a fixed damage to the enemy equal to 2.5x DEF. During the battle, if the hero's HP is higher than the enemy's HP, the soldier's DEF and MDEF increase by 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Dark Centurion.jpg'>(SP&nbsp;terms)</a>",
        "lance",
        "Кит,Элвин,Алтемюллер,Леонхарт,Рене,Селина,Бетти,Густав,Оборо,Лукман,Фрейя,Полиал,Альфа,Лэндиус,Арианход,Бьянка",
        "ходьба"
    ],
	[
        "Киборг-сосуд SP",
        "Cyborg Vessel SP",
        "42",
        "43",
        "23",
        "19",
        "3",
        "1",
        "При активной атаке дальнего боя солдаты будут атаковать вместе с героем, при этом урон увеличивается на 30%. Во время боя юнит игнорирует снижение урона в ближнем бою, а АТК и ЗАЩ солдат увеличиваются на 15%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Киборг-сосуд.jpg'>(Условия&nbsp;SP)</a>",
        "When active ranged attack, soldiers will attack with the hero and damage is increased by 30%. During combat unit ignores melee damage reduction and the soldiers' ATK and DEF are increased by 15%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Cyborg Vessel.jpg'>(SP&nbsp;terms)</a>",
        "sword",
        "Гизаров,Сигма,Рейнфорс,Шилинка,Эпсилон,Вернер,Маклейн,Абишай,Железный Воитель,Клотэр,Кирикадзе,Джулиан,Лина",
        "ходьба"
    ],
	[
        "Экзорцист SP",
        "Exorcist SP",
        "40",
        "40",
        "22",
        "20",
        "3",
        "1",
        "ЗАЩ солдат +30%. При сражении с демонами, АТК увеличивается на 30%. При активной атаке и входе в бой, если ЗАЩ врага больше или равна МЗАЩ, в этом бою наносится магический урон. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Экзорцист.jpg'>(Условия&nbsp;SP)</a>",
        "Soldier DEF +30%. When fighting demons, ATK increases by 30%. When actively attacking and entering battle, if the enemy's DEF is greater than or equal to MDEF, magic damage is dealt in this battle. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Exorcist.jpg'>(SP&nbsp;terms)</a>",
        "holy",
        "Крис,София,Фрейя,Ледин,Лиана,Эстель,Клозе,Селина,Сакура,Анжелика,Юлия,Юске,Рейнфорс,Эмилия,Вираш,Майя,Арианход,Розалия,Отшельник,Флоренция,Мелания,Клотэр,Мариэль,Король Красной Луны,Рё,Эльма,Железный Воитель,Азуса,Синпати,Светоносец,Полиал,Элисса,Роланд,Преция,Имир,Яркий призыватель,Сафрин,Сангер,Рейга,Саллун,Шурато",
        "ходьба"
    ],
    [
        "Рыцарь-тамплиер SP",
        "Templar Knight SP",
        "43",
        "43",
        "23",
        "26",
        "5",
        "1",
        "При сражении с врагом, МЗАЩ солдат +45%, АТК и ЗАЩ солдат +20% в бою. Если враг 'демон', АТК и ЗАЩ дополнительно увеличиваются на 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Рыцарь-тамплиер.jpg'>(Условия&nbsp;SP)</a>",
        "When fighting an enemy soldier's MDEF +45%, ATK and DEF +20% in battle. If the enemy is a 'demon', ATK and DEF are additionally increased by 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Templar Knight.jpg'>(SP&nbsp;terms)</a>",
        "cavalry",
        "Альмеда,Скотт,Аарон,Фрейя,Лиана,Тиарис,Лэндиус,Сумире,Юлия,Альфред,Дидлит,Арианход,Розалия,Хильда,Кристиан,Железный Воитель,Азуса,Синпати,Светоносец,Греншиль,Элейн,Амадей,Элисса,Преция,Эйшин,Хофманн,Зион,Император Ловина,Герольд и Лайла,Ленфорд,Тирантир,Лея,Хранитель волн,Шурато",
        "всадник"
    ],
	[
        "Святой пегас SP",
        "Holy Pegasus SP",
        "43",
        "45",
        "23",
        "24",
        "5",
        "1",
        "При активной атаке и вступлении в бой АТК солдат увеличивается на 30%, а получаемый урон снижается на 50%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Святой пегас.jpg'>(Условия&nbsp;SP)</a>",
        "When actively attacking and entering battle, soldier's ATK increases by 30% and damage taken decreases by 50%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Holy Pegasus.jpg'>(SP&nbsp;terms)</a>",
        "fly",
        "Кит,Ланс,Нарм,Луна,Рэйчел,Кларетт,Алустриэль,Рыцарь Тайн,Алтина,Розалия,Хелена,Розенцель,Това,Король Красной Луны,Азуса,Оборо,Каролина,Гинтоки,Греншиль,Соня Бланш,Эйшин,Хофманн,Изольда,Табрес,Лукман,Лея",
        "полет"
    ],
	[
        "Рейнджер вихря SP",
        "Bolt Ranger SP",
        "40",
        "41",
        "22",
        "22",
        "5",
        "2",
        "Когда ОЗ солдат выше 50%, АТК и ЗАЩ солдат увеличиваются на 20%. Когда подвергается атаке и втянут в бой, получаемый урон снижается на 50% и игнорирует уменьшение урона в ближнем бою. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Рейнджер вихря.jpg'>(Условия&nbsp;SP)</a>",
        "When soldier's HP is above 50%, soldier's ATK and DEF are increased by 20%. When forced into battle, damage taken is reduced by 50% and ignores melee damage reduction. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Bolt Ranger.jpg'>(SP&nbsp;terms)</a>",
        "bow",
        "Гренье,Диос,Нарм,Луна,Тиарис,Айрис,Омега,Рыцарь Тайн,Ашемар,Суверен ледяной бездны,Джулиан,Дихарт,Теон,Таталия,Тиана,Шарик",
        "парение"
    ],
    [
        "Колдунья SP",
        "Sorceress SP",
        "37",
        "42",
        "17",
        "28",
        "5",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Чем выше ОЗ солдат, тем выше их АТК и МЗАЩ (до 45%). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Колдунья.jpg'>(Условия&nbsp;SP)</a>",
        "Physical damage dealt by normal attacks is considered magical damage. The higher the HP of the soldiers, the higher their ATK and MDEF (up to 45%). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Sorceress.jpg'>(SP&nbsp;terms)</a>",
        "mage",
        "Джессика,Феракуа,Лиффани,Бозел,Лана,Тиарис,Герольд и Лайла,Рене,Оливиер,Рэйчел,Ламбда,Айрис,Курама,Юная Джессика,Рыцарь Тайн,Ликорис,Алтина,Ноэми,Розенцель,Аватар Света,Химико,Злой Бог Крюгер,Патцир,Сисси Уайт,Каюра,Лукреция,Мю,Трансцендентный,Мариандель,Кертес,Дева Ковчега,Густав,Кагуя,Ашемар,Аданкельмо,Девушка в Доспехах,Лео Бек,Люгнер,Джо и Конни,Агнес,Пробужденная,Сагани,Кирика,Нимфа,Тормил,Роланд,Лина,Зелгадис,Неемия,Джесс,Алканфель,Суверен ледяной бездны,Селика,Вирелия,Яркий призыватель,Эния,Алия,Илия,Сафрин,Птица с поломанным крылом,Ланделл,Силрна,Макира,Глаз обмана,Люси,Хумбаба,Непокорная небесам,Райза,Клаудия,Линн,Ранка,Кумо,Бозена",
        "полет"
    ],
	[
        "Королевский страж SP",
        "Royal Protector SP",
        "43",
        "43",
        "22",
        "25",
        "3",
        "1",
        "АТК солдат увеличивается на 15%. Про получении атаки АТК солдат увеличивается еще на 15%, солдаты могут контратаковать, а получаемый магический урон уменьшается на 30%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Королевский страж.jpg'>(Условия&nbsp;SP)</a>",
        "Soldiers' ATK increases by 15%. When receiving an attack, soldiers' ATK increases by another 15%, soldiers can counterattack and magic damage received is reduced by 30%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Royal Protector.jpg'>(SP&nbsp;terms)</a>",
        "sword",
        "Крис,Фрейя,Кларетт,Альбедо,Розенцель,Рё,Кристиан,Мишель,Синпати,Светоносец,Элейн,Лина,Капитан Джек,Эйшин,Хофманн,Тиана,Норнорин,Лея,Юлия,Железный Воитель,Серафина,Мари Роуз,Соня Бланш,Рапьер",
        "ходьба"
    ],
	[
        "Фанатик SP",
        "Zealot SP",
        "42",
        "42",
        "22",
        "22",
        "3",
        "1",
        "За каждый бафф, АТК, ЗАЩ и МЗАЩ солдат увеличивается на 15% (до 45%). В конце действия восстанавливается 20% ОЗ солдат. Если есть дебафф, восстанавливается 40% ОЗ и снимается 1 дебафф. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Фанатик.jpg'>(Условия&nbsp;SP)</a>",
        "For each buff the soldier's ATK, DEF, and MDEF increases by 15% (up to 45%). At the end of the action 20% of the soldier's HP is restored. If there is a debuff 40% of HP is restored and 1 debuff is removed. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Zealot.jpg'>(SP&nbsp;terms)</a>",
        "holy",
        "Крис,София,Ледин,Эстель,Клозе,Вилер,Селина,Ламбда,Сакура,Юлия,Юске,Эмилия,Майя,Арианход,Отшельник,Клотэр,Мариэль,Король Красной Луны,Рё,Железный Воитель,Азуса,Синпати,Светоносец,Полиал,Роланд,Имир,Сафрин,Элисса,Фрейя,Преция,Розалия,Сангер,Рейга,Саллун,Шурато",
        "ходьба"
    ],
	[
        "Темный алхимик SP",
        "Dark Alchemist SP",
        "43",
        "42",
        "20",
        "20",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. После окончания действия восстанавливает 30% ОЗ солдат. Когда у солдат более 80% ОЗ, их АТК увеличивается на 30%. При использовании дальних навыков для входа в бой, дальность увеличивается на 1 и солдаты также будут атаковать в бою. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Темный алхимик.jpg'>(Условия&nbsp;SP)</a>",
        "Physical damage dealt by normal attacks is considered as magic damage. After the end of the action, restores 30% of the soldiers' HP. When the soldiers' HP is over 80%, their ATK increases by 30%. When using long-range skills to enter combat, the range increases by 1 and the soldiers will also attack in battle. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Dark Alchemist.jpg'>(SP&nbsp;terms)</a>",
        "mage",
        "Крис,Лана,Герольд и Лайла,Рэйчел,Курама,Майя,Дева Ковчега,Сагани,Зелгадис,Селика,Лина,Юная Джессика,Девушка в Доспехах,Силрна,Кагуя,Райза,Клаудия,Бозена",
        "полет"
    ],
	[
        "Бандит SP",
        "Bandit SP",
        "40",
        "43",
        "20",
        "22",
        "3",
        "2",
        "Шанс критического удара солдат увеличен на 30%, АТК солдат увеличена на 25%. Отряд игнорирует снижение урона в ближней бою. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Бандит.jpg'>(Условия&nbsp;SP)</a>",
        "Soldier critical hit chance increased by 30%, soldier ATK  increased by 25%. Unit ignores melee damage reduction. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Bandit.jpg'>(SP&nbsp;terms)</a>",
        "assasin",
        "Метью,Рохга,Серебряный Волк,Феракуа,Кирикадзе,Шери,Дихарт,Зерида,Джошуа,Омега,Курама,Хией,Рейнфорс,Оливер,Шилинка,Цубамэ,Химико,Тома,Сюзетт,Вернер,Лиза,Сельвария,Алисия,Лостхэм,Джулиан,Маклейн,Теон,Кирика,Таталия,Нож Марк и Ниндзя Гиндзу,Птица с поломанным крылом,Лила,Тадж",
        "ходьба"
    ],
	[
        "Призрак тумана SP",
        "Mist Spirit SP",
        "42",
        "40",
        "23",
        "24",
        "5",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. При входе в бой АТК солдат +30%. Если ОЗ солдат выше 70%, получаемый ими физический урон уменьшается на 20%. Юнит игнорирует недостаток класса. После боя солдаты восстанавливают 45% потерянных ОЗ. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Призрак тумана.jpg'>(Условия&nbsp;SP)</a>",
        "Physical damage dealt by normal attacks is considered magical damage. When entering combat the soldier's ATK is increased by 30%. If the soldiers' HP is above 70% the physical damage they receive is reduced by 20%. The unit ignores class disadvantage. After combat soldiers recover 45% of their lost HP. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Mist Spirit.jpg'>(SP&nbsp;terms)</a>",
        "demon",
        "Эгберт,Соня,Феракуа,Бозел,Герольд и Лайла,Рене,Курама,Айнз,Патцир,Трансцендентный,Дева Ковчега,Густав,Лео Бек,Пробужденная,Таталия,Лина,Алканфель,Глаз обмана,Ликорис,Ланделл,Кертес,Хией,Гизаров,Непокорная небесам",
        "полет"
    ],
	[
        "Страж-энт SP",
        "Treant Guard SP",
        "45",
        "43",
        "25",
        "20",
        "3",
        "1",
        "Получаемое солдатами исцеление увеличивается на 30%, кроме того они получают Щит в размере 35% от полученого исцеления (максимум до 40% от макс. ОЗ). Если ОЗ солдат выше 80%, их АТК, ЗАЩ и МЗАЩ увеличивается на 45%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Страж-энт.jpg'>(Условия&nbsp;SP)</a>",
        "Soldiers receive 30% more healing and gain a Shield equal to 35% of the healing received (up to 40% of Max HP). If Soldiers' HP is above 80%, their ATK, DEF, and MDEF are increased by 45%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Treant Guard.jpg'>(SP&nbsp;terms)</a>",
        "lance",
        "Листелл,Лэндиус,Эмилия,Ака,Отшельник,Мю,Мариандель,Азуса,Кагуя,Кагура,Светоносец,Полиал,Амадей,Сафрин,Кристиан,Юлия,Тиана,Варгас,Синпати,Ора",
        "ходьба"
    ],
	[
        "Жрец океана SP",
        "Ocean Priest SP",
        "44",
        "39",
        "23",
        "26",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Когда активно атакует, МЗАЩ солдат увеличивается на 20%. Этот эффект удваивается когда юнит находится в воде и на атаки не влияет уменьшение урона в ближнем бою. При активной атаке, если юнит или противник находится в воде, восстанавливает 30% ОЗ солдат перед боем. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Жрец океана.jpg'>(Условия&nbsp;SP)</a>",
        "Physical damage dealt by normal attacks is considered magic damage. When actively attacking, the soldier's MDEF is increased by 20%. This effect is doubled when the unit is in water and attacks are not affected by melee damage reduction. When actively attacking, if the unit or enemy is in water, restores 30% of the soldier's HP before the battle. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Ocean Priest.jpg'>(SP&nbsp;terms)</a>",
        "water",
        "Лестер,Пьер,Джаглер,Анджелина,Альфред,Илюсия,Ликорис,Архонт Луны,Маклейн,Девушка в Доспехах,Люгнер,Нимфа,Норнорин,Капитан Джек,Неемия,Вираш",
        "пловец"
    ],
	[
        "Эльф-мастер SP",
        "Elf Master SP",
        "39",
        "42",
        "21",
        "23",
        "3",
        "2",
        "АТК и ЗАЩ увеличиваются на 30% в [Лесных] и [Горных] местностях. При активной атаке и вступлении в бой, если юнит находится на защитной местности, наносимый солдатами урон увеличивается на 5% за каждую клетку расстояния до противника (до 15%). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Эльф-мастер.jpg'>(Условия&nbsp;SP)</a>",
        "ATK and DEF increase by 30% in [Forest] and [Mountain] terrain. When actively attacking and entering combat, if the unit is in defensive terrain, the damage dealt by soldiers increases by 5% for each tile of distance to the enemy (up to 15%). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Elf Master.jpg'>(SP&nbsp;terms)</a>",
        "bow",
        "Метью,Альмеда,Джессика,Рохга,Нарм,Крис,Хейн,София,Лиффани,Серебряный Волк,Шери,Лиана,Луна,Шельфаниэль,Оливиер,Вилер,Сигма,Ламбда,Сумире,Курама,Рейнфорс,Юная Джессика,Оливер,Дидлит,Майя,Шилинка,Алтина,Ноэми,Отшельник,Флоренция,Цубамэ,Мелания,Розенцель,Аватар Света,Химико,Тома,Мю,Сюзетт,Трансцендентный,Вернер,Мариандель,Эльма,Лиза,Сельвария,Алисия,Кагуя,Ашемар,Теон,Люгнер,Агнес,Кирика,Тормил,Роланд,Лина,Неемия,Джесс,Селика,Вирелия,Яркий призыватель,Нож Марк и Ниндзя Гиндзу,Эния,Алия,Илия,Сафрин,Птица с поломанным крылом,Касуми,Люси,Шарик,Райза,Клаудия,Линн,Миюки,Кумо",
        "ходьба"
    ],
	[
        "Берсерк SP",
        "Berserker SP",
        "44",
        "43",
        "22",
        "21",
        "3",
        "1",
        "Шанс критического удара увеличивается на 30%, АТК увеличивается на 15%. Если при активной атаке и вступлении в бой в радиусе 1 клетки нет союзников, АТК дополнительно повышается на 15%, а шанс критического удара на 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Берсерк.jpg'>(Условия&nbsp;SP)</a>",
        "Critical Hit Chance increases by 30% and ATK by 15%. If there are no allies within 1 tile of you when you actively attack and enter combat, ATK is additionally increased by 15% and Critical Hit Chance by 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Berserker.jpg'>(SP&nbsp;terms)</a>",
        "sword",
        "Лестер,Кирикадзе,Леон,Анджелина,Ленфорд,Эстель,Кларетт,Рейнфорс,Вираш,Бренда,Парн,Арес,Рин,Клотэр,Сибараку,Автократо,Эпсилон,Альфа,Император Ловина,Сельвария,Оборо,Странствующий Дуэлянт,Гинтоки,Кагура,Синпати,Гаури,Капитан Джек,Капитан Коммандо и Гений-малыш,Абишай,Эльза,Шем,Меч Света и Тьмы,Зион,Элвин,Мари Роуз,Сангер,Рейга,Аши,Банши,Гай",
        "ходьба"
    ],
	[
        "Небесный страж SP",
        "Heavensguard SP",
        "41",
        "43",
        "23",
        "22",
        "5",
        "1",
        "АТК и ЗАЩ солдат увеличивается на 15% с каждой пройденной до атаки клеткой (до 45%). Если расстояние, пройденное перед вступлением в бой 3 и больше, то после боя время восстановление навыка с самым большим временем восстановление снижается на 1. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Небесный страж.jpg'>(Условия&nbsp;SP)</a>",
        "A soldier's ATK and DEF increase by 15% for every tile moved before attacking (up to 45%). If the distance moved before entering combat is 3 or more, the post-combat cooldown for the skill with the longest cooldown is reduced by 1. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Heavensguard.jpg'>(SP&nbsp;terms)</a>",
        "cavalry",
        "Летисия,Ланс,Соня,Луна,Дихарт,Ленфорд,Сакура,Кларетт,Юлия,Рыцарь Тайн,Оливер,Арес,Розалия,Ватару,Азуса,Каролина,Кагура,Синпати,Эксела,Элисса,Андриола,Элвис,Хелена,Император Ловина,Парн,Первобытная Зерида",
        "парение"
    ],
	[
        "Драгун SP",
        "Dragoon SP",
        "45",
        "44",
        "24",
        "21",
        "5",
        "1",
        "АТК и ЗАЩ +25%. При активной атаке и вступлении в бой, если мобильность врага не выше чем у юнита, получаемый урон уменьшается на 15%, а АТК увеличивается на 15%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Драгун.jpg'>(Условия&nbsp;SP)</a>",
        "ATK and DEF +25%. When actively attacking and entering combat, if the enemy's mobility is not higher than the unit's, damage taken is reduced by 15% and ATK is increased by 15%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Dragoon.jpg'>(SP&nbsp;terms)</a>",
        "cavalry",
        "Элвин,Шери,Дихарт,Анджелина,Селина,Алустриэль,Тогуро,Бетти,Бренда,Оливер,Ашрам,Парн,Ватару,Това,Исара,Странствующий Дуэлянт,Амадей,Эксела,Изольда,Суверен ледяной бездны,Эльза,Сибель,Тирантир,Кагура,Андриола,Вернер Дайм,Хелена,Непокорная небесам",
        "всадник"
    ],
	[
        "Рыцарь на механическом драконе SP",
        "Mechanical Dragon Knight SP",
        "44",
        "45",
        "24",
        "22",
        "5",
        "1",
        "АТК и ЗАЩ +25%. Когда втянут в бой, получаемый физический урон уменьшается на 25%. Если в пределах 1 клетки нет других союзников, АТК и ЗАЩ солдат увеличиваются еще на 15%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Рыцарь на механическом драконе.jpg'>(Условия&nbsp;SP)</a>",
        "ATK and DEF +25%. When forced into combat, physical damage taken is reduced by 25%. If there are no other allies within 1 tile, the soldier's ATK and DEF are increased by an additional 15%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Mechanical Dragon Knight.jpg'>(SP&nbsp;terms)</a>",
        "fly",
        "Метью,Ланс,Эмерик,Варна,Алтемюллер,Луна,Анджелина,Ленфорд,Бренда,Ашрам,Парн,Рената,Това,Император Ловина,Исара,Странствующий Дуэлянт,Греншиль,Джо и Конни,Элисса,Гаури,Суверен ледяной бездны,Тирантир,Зион,Капитан Коммандо и Гений-малыш,Ниотэнгу,Лукман,Лея,Нацу,Бьянка,Леон,Табрес,Каролина,Джаглер,Винсент,Хранитель волн",
        "полет"
    ],
    [
        "Амазонка-чемпион SP",
        "Amazon Champion SP",
        "43",
        "45",
        "22",
        "22",
        "3",
        "1",
        "АТК +30%. При активной атаке и вступлении в бой, снижает ЗАЩ и МЗАЩ противника на 30% перед боем. При сражении с врагами, у которых проуент ОЗ не ниже чем у юнита, АТК и ЗАЩ солдат дополнительно увеличиваются на 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Амазонка-чемпион.jpg'>(Условия&nbsp;SP)</a>",
        "ATK +30%. When actively attacking and entering combat reduces the enemy's DEF and MDEF by 30% before combat. When fighting enemies with HP equal to or greater than the unit's the soldier's ATK and DEF are additionally increased by 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Amazon Champion.jpg'>(SP&nbsp;terms)</a>",
        "lance",
        "Гренье,Левин,Крис,Ледин,Ленфорд,Эстель,Селина,Сумире,Юлия,Вираш,Бренда,Арианход,Флоренция,Шалтир,Мариэль,Сибараку,Това,Король Красной Луны,Каюра,Мю,Кристиан,Вернер,Железный Воитель,Азуса,Оборо,Рикки,Кагура,Соня Бланш,Эксела,Преция,Тиана,Норнорин,Абишай,Лукман,Фрейя,Хильда,Лэндиус,Рената,Странствующий Дуэлянт,Сангер,Муллин,Первобытная Зерида,Аши,Банши",
        "ходьба"
    ],
    [
        "Летучая мышь-вампир SP",
        "Vampire Bat SP",
        "45",
        "45",
        "24",
        "22",
        "5",
        "1",
        "Когда ОЗ солдат не ниже 80%, их АТК и ЗАЩ увеличиваются на 25%. После боя солдаты восстанавливают ОЗ равное 45% от нанесённого в бою урона. После получения лечения урон солдат увеличивается на 20% на 1 ход. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Летучая мышь-вампир.jpg'>(Условия&nbsp;SP)</a>",
        "When soldiers' HP is at least 80% their ATK and DEF are increased by 25%. After battle soldiers recover HP equal to 45% of the damage dealt during the battle. After receiving healing soldiers' damage is increased by 20% for 1 turn. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Vampire Bat.jpg'>(SP&nbsp;terms)</a>",
        "fly",
        "Метью,Соня,Варна,Леон,Алтемюллер,Джаглер,Герольд и Лайла,Листелл,Тогуро,Ака,Ашрам,Ликорис,Рената,Шалтир,Винсент,Эпсилон,Трансцендентный,Ютем,Меч Света и Тьмы,Апофеоз,Ганн,Драконоборец,Сибель,Непокорная небесам,Оборо,Элвис,Ланс,Тирантир,Кагура,Первобытная Зерида,Лейд,Банши",
        "полет"
    ],
    [
        "Галантный дуэлянт SP",
        "Gallant Duelist SP",
        "45",
        "43",
        "25",
        "20",
        "4",
        "1",
        "При активном вступлении в бой, АТК и шанс критического удара солдат повышаются на 30%. Если солдаты в ступают в бой с ОЗ не ниже 80%, получаемый ими физ. урон снижается на 25% ,а шанс получить крит. удар у вражеских войск повышается на 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Галантный дуэлянт.jpg'>(Условия&nbsp;SP)</a>",
        "When actively enter in combat, soldiers' ATK and critical strike chance are increased by 30%. If soldiers enter combat with HP at least 80%, physical damage they receive is reduced by 25%, and enemy troops' chance to get a critical hit is increased by 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Gallant Duelist.jpg'>(SP&nbsp;terms)</a>",
        "sword",
        "Кирикадзе,Леон,Элвин,Ленфорд,Сакура,Юлия,Кадзума,Бренда,Парн,Ватару,Меч Света и Тьмы,Греншиль,Ван,Элейн,Соня Бланш,Роланд,Гаури,Капитан Джек,Эйшин,Шо Фукамачи,Табрес,Зион,Абишай,Элвис,Эльза,Нацу,Изольда,Норнорин,Мари Роуз,Бетти,Альбедо,Первобытная Зерида,Саллун,Банши",
        "ходьба"
    ],
	[
        "Рыцарь-грифон SP",
        "Griffin Knight SP",
        "43",
        "45",
        "22",
        "23",
        "5",
        "1",
        "АТК и ЗАЩ +30%. Когда ОЗ солдат выше 80%, наносимый урон по нелетающим юнитам увеличивается на 20% при активной атаке. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Рыцарь-грифон.jpg'>(Условия&nbsp;SP)</a>",
        "ATK and DEF +30%. When soldiers' HP is above 80%, damage dealt to non-flying units increases by 20% during an active attack. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Griffin Knight.jpg'>(SP&nbsp;terms)</a>",
        "fly",
        "Метью,Скотт,Лэйд,Кит,Ланс,Эмерик,Варна,Шери,Алтемюллер,Луна,Дихарт,Анджелина,Ленфорд,Кларетт,Парн,Рин,Розалия,Ватару,Сибараку,Винсент,Това,Король Красной Луны,Кристиан,Император Ловина,Исара,Оборо,Странствующий Дуэлянт,Кагура,Греншиль,Джо и Конни,Элейн,Амадей,Эксела,Элисса,Преция,Гаури,Андриола,Изольда,Шо Фукамачи,Суверен ледяной бездны,Табрес,Тирантир,Зион,Капитан Коммандо и Гений-малыш,Драконоборец,Ниотэнгу,Лея,Нацу,Рапьер,Шарик,Бьянка,Эйшин,Леон,Хелена,Тогуро,Ашрам,Лила,Тадж,Д-мен,Хранитель волн,Реига",
        "полет"
    ],
    [
        "Горец-воин SP",
        "Highland Warrior SP",
        "47",
        "43",
        "23",
        "21",
        "3",
        "1",
        "Наносимый солдатами урон увеличивается на 20%, а получаемый урон снижается на 15%. Когда ОЗ солдат выше 80%, эти эффекты удваиваются и враг не будет атаковать раньше.  <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Горец-воин.jpg'>(Условия&nbsp;SP)</a>",
        "Soldiers' damage is increased by 20% and damage taken is reduced by 15%. When soldiers' HP is above 80% these effects are doubled and preventing the enemy from attacking early. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Highland Warrior.jpg'>(SP&nbsp;terms)</a>",
        "sword",
        "Метью,Крис,Лиана,Клозе,Леонхарт,Вилер,Бетти,Альфред,Бренда,Парн,Илюсия,Рин,Хелена,Мариэль,Король Красной Луны,Рё,Кристиан,Эльма,Железный Воитель,Гаури,Тиана,Мари Роуз,Хильда,Светоносец,Лэндиус,Саллун,Шурато",
        "ходьба"
    ],
    [
        "Конный лучник эльфов SP",
        "Elven Cavarly Archer SP",
        "40",
        "43",
        "20",
        "25",
        "5",
        "2",
        "АТК солдат +20%. При сражении в 'лесу', 'горах' и 'пастбищах' или против врагов, которые находятся на данных местностях, АТК и наносимый урон увеличиваются еще на 20%, получаемый маг. урон снижается на 30% и юнит не подвержен снижению урона в ближнем бою. При сражении с врагом, который находится на данных местностях юнит также считается находящимся на местности с 20% увеличением ЗАЩ. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Конный лучник эльфов.jpg'>(Условия&nbsp;SP)</a>",
        "Soldiers' ATK +20%. When fighting in 'Forests', 'Mountains' and 'Plains' or against enemies located in these areas ATK and damage dealt are increased by an additional 20%, magic damage taken is reduced by 30% and the unit is not subject to melee damage reduction. When fighting an enemy located in these areas the unit is also considered to be in terrain with a 20% increase to DEF. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Elven Cavarly Archer.jpg'>(SP&nbsp;terms)</a>",
        "bow",
        "Гренье,Диос,Луна,Дихарт,Сумире,Алустриэль,Оливер,Пиротесс,Мю,Джо и Конни,Птица с поломанным крылом,Сафрин,Ланделл,Тиана,Глаз обмана,Муллин,Бозена",
        "всадник"
    ],
	[
        "Темный страж SP",
        "Dark Guard SP",
        "53",
        "40",
        "23",
        "22",
        "3",
        "1",
        "АТК, ЗАЩ и МЗАЩ увеличиваются на 20%. После вступления в бой восстанавливают 30% потеряных ОЗ и наносит противнику фиксированный урон равный 25% от текущего ОЗ. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Темный страж.jpg'>(Условия&nbsp;SP)</a>",
        "Soldiers' ATK, DEF and MDEF are increased by 20%. After entering combat restores 30% of lost HP and deals a fixed damage to the enemy equal to 25% of the current HP. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Dark Guard.jpg'>(SP&nbsp;terms)</a>",
        "sword",
        "Фрейя,Варна,Бернхардт,Леонхарт,Лэндиус,Сакура,Рин,Клотэр,Автократо,Альфа,Бренда,Абишай,Мари Роуз,Норнорин,Ганн,Муллин",
        "ходьба"
    ],
	[
        "Шиноби SP",
        "Shinobi SP",
        "39",
        "45",
        "20",
        "20",
        "3",
        "2",
        "Шанс критического удара и критический урон увеличивается на 30%. Перед боем наносит противнику фиксированный урон равный 30% от текущего ОЗ солдат. Этот эффект срабатывает повторно после боя, если был нанесён критический урон. Если в радиусе 2 клеток от юнита есть союзник, местность под юнитом считается местностью с увеличение ЗАЩ на 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Шиноби.jpg'>(Условия&nbsp;SP)</a>",
        "Critical hit chance and critical damage are increased by 30%. Before combat deals fixed damage to the enemy equal to 30% of the soldier's current HP. This effect is triggered again after combat if critical damage is inflicted. If there is an ally within 2 blocks of the unit the terrain beneath the unit is treated as terrain with a 20% DEF bonus. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Shinobi.jpg'>(SP&nbsp;terms)</a>",
        "assasin",
        "Метью,Рохга,Дихарт,Джошуа,Сигма,Омега,Хией,Пиротесс,Цубамэ,Тома,Сюзетт,Лостхэм,Джулиан,Джо и Конни,Птица с поломанным крылом,Серафина,Таталия,Каюра,Муллин,Миюки",
        "ходьба"
    ],
    [
        "Адский пес SP",
        "Hell Hound SP",
        "42",
        "45",
        "21",
        "20",
        "5",
        "1",
        "АТК и ЗАЩ +20%. Перед активным нанесением урона, все враги в радиусе 2 клеток получают эффект 'получаемый урон +20%'. Если враг не находится на защитной местности, то перед этим 2 его случайные характеристики (кроме ОЗ) уменьшаются на 15% на 2 хода. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Адский пес.jpg'>(Условия&nbsp;SP)</a>",
        "ATK and DEF +20%. Before actively dealing damage all enemies within a 2-tile radius gain the 'damage taken +20%' effect. If an enemy is not in defensive terrain, then beforehand, two random stats (except HP) are reduced by 15% for 2 turns. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Hell Hound.jpg'>(SP&nbsp;terms)</a>",
        "cavalry",
        "Метью,Соня,Джаглер,Илюсия,Альбедо,Винсент,Ютем,Апофеоз,Макишима Агито,Ора,Император Ловина,Амадей,Леон,Сибель,Шарик,Д-мен,Аши",
        "всадник"
    ],
	[
        "Эльф прилива SP",
        "Tidal Elf SP",
        "43",
        "39",
        "24",
        "22",
        "3",
        "1",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Солдаты получают на 25% меньше физического урона, а их АТК увеличивается на 15%. Если юнит находится в воде, этот эффект удваивается перед вступлением в бой. В ином случае 100% вероятность что местность, на которой находится юнит будет считаться 'водой'. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Эльф прилива.jpg'>(Условия&nbsp;SP)</a>",
        "Physical damage dealt by normal attacks is treated as magical damage. Soldiers take 25% less physical damage and their ATK is increased by 15%. If the unit is in water, this effect is doubled before entering combat. Otherwise, there is a 100% chance that the terrain the unit is on will be treated as 'water.' <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Tidal Elf.jpg'>(SP&nbsp;terms)</a>",
        "water",
        "Лестер,Левин,Шельфаниэль,Илюсия,Ликорис,Лукреция,Девушка в Доспехах,Нимфа,Неемия,Капитан Джек,Люгнер,Архонт Луны,Норнорин,Пробужденная,Хранитель волн",
        "полет"
    ],
    [
        "Солдат фаланги SP",
        "Hoplite SP",
        "43",
        "44",
        "23",
        "19",
        "3",
        "1",
        "АТК и ЗАЩ солдат +20%. Когда у солдат 100% ОЗ или при активной атаке юнит игнорирует недостатки классов. Чем выше ОЗ солдат, тем выше их АТК и наносимый урон, максимум до +30%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Солдат фаланги.jpg'>(Условия&nbsp;SP)</a>",
        "Soldier ATK and DEF +20%. When soldiers have 100% HP or are actively attacking, the unit ignores class disadvantages. The higher the soldiers' HP, the higher their ATK and damage, up to a maximum of +30%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Hoplite.jpg'>(SP&nbsp;terms)</a>",
        "lance",
        "Варгас,Эмерик,Бернхардт,Алтемюллер,Шалтир,Хильда,Това,Король Красной Луны,Рё,Лостхэм,Странствующий Дуэлянт,Гинтоки,Эксела,Преция,Гаури,Тиана,Шем,Абишай,Лукман,Сангер,Ледин,Полиал,Светоносец,Джаглер,Аши,Банши",
        "ходьба"
    ],
	[
        "Горгулья SP",
        "Gargoyle SP",
        "43",
        "45",
        "23",
        "23",
        "5",
        "1",
        "АТК и ЗАЩ солдат +20%. Когда ОЗ солдат выше 50%, их АТК и наносимый урон увеличиваются на 15%. Когда ОЗ солдат меньше 50%, они не могут атаковать, но их ЗАЩ увеличивается на 20%, а получаемый урон снижается на 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Горгулья.jpg'>(Условия&nbsp;SP)</a>",
        "Soldiers' ATK and DEF +20%. When soldiers' HP is above 50% their ATK and damage dealt are increased by 15%. When soldiers' HP is below 50% they cannot attack but their DEF is increased by 20% and damage taken is reduced by 20%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Gargoyle.jpg'>(SP&nbsp;terms)</a>",
        "fly",
        "Скотт,Лэйд,Эмерик,Варна,Алтемюллер,Джаглер,Листелл,Алустриэль,Тогуро,Бренда,Ашрам,Рената,Алтина,Шалтир,Эпсилон,Трансцендентный,Ютем,Меч Света и Тьмы,Макишима Агито,Ганн,Драконоборец,Мари Роуз,Элвис,Бренда,Амадей,Андриола,Винсент,Апофеоз",
        "полет"
    ],
    [
        "Боевой монах SP",
        "Fighting Monk SP",
        "42",
        "41",
        "22",
        "23",
        "3",
        "2",
        "Эффекты исцеления героя увеличиваются на 15%, а ЗАЩ солдат на 25%. При получении атаки, юнит не подвержен снижению урона в ближнем бою, а солдаты восстанавливают 25% ОЗ после боя. Если юнит не является смешанным, АТК солдат увеличивается на 30%, а в начале хода, если у юнита 100% ОЗ, он получает эффект 'Иммунитет к следующему дебаффу (не может быть снято)'. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Боевой монах.jpg'>(Условия&nbsp;SP)</a>",
        "The hero's healing effects are increased by 15% and the soldier's DEF by 25%. When forced in combat, the unit is immune to melee damage reduction and soldiers recover 25% of their HP after combat. If the unit is not a mixed unit, the soldier's ATK is increased by 30% and at the start of the turn, if the unit has 100% HP, it gains the 'Immunity to next debuff (cannot be removed)' effect. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Fighting Monk.jpg'>(SP&nbsp;terms)</a>",
        "holy",
        "Альмеда,Анна,София,Имельда,Лана,Лиана,Рэйчел,Вилер,Юная Джессика,Майя,Отшельник,Флоренция,Мелания,Розенцель,Сисси Уайт,Мю,Мариандель,Эльма,Азуса,Аданкельмо,Светоносец,Сагани,Тормил,Джесс,Яркий призыватель,Алия,Селика,Крис,Люгнер,Тиарис,Каюра,Кумо",
        "ходьба"
    ],
	[
        "Расплавленный колдун SP",
        "Fire Witch SP",
        "45",
        "42",
        "18",
        "22",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками считается магическим уроном. АТК солдат увеличивается на 30%. При активной атаке, перед боем снимается 10% ОЗ солдат и наносится 150% от этого значения в виде фиксированного урона врагу и накладывает на него 1 дебафф. После боя восстанавливает ОЗ солдат на 30% от нанесённого урона. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Расплавленный колдун.jpg'>(Условия&nbsp;SP)</a>",
        "Physical damage dealt by normal attacks is treated as magical damage. Soldiers' ATK is increased by 30%. Active attacks remove 10% of soldiers' HP before combat dealing 150% of that amount as fixed damage to the enemy and applying a debuff. After combat soldiers' HP is restored by 30% of the damage dealt. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Fire Witch.jpg'>(SP&nbsp;terms)</a>",
        "mage",
        "Лана,Хейн,Эгберт,Имельда,Гизаров,Рене,Злой Бог Крюгер,Лукреция,Ликорис,Патцир,Дева Ковчега,Девушка в Доспехах,Лео Бек,Патриция,Кертес,Силрна,Райза,Тормил,Ланделл,Феракуа,Саллун,Бозена",
        "ходьба"
    ],
    [
        "Охотник на демонов SP",
        "Demon Hunter SP",
        "38",
        "41",
        "20",
        "20",
        "5",
        "2",
        "Перед активным вступлением в бой 100% шанс снизить мобильность врага на 2 и ЗАЩ на 20% на 1 ход. Урон противникам со сниженной мобильностью увеличивается на 30%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Охотник на демонов.jpg'>(Условия&nbsp;SP)</a>",
        "Before actively engaging in combat, 100% chance to reduce enemy mobility by 2 and DEF by 20% for 1 turn. Damage dealt to enemies with reduced mobility is increased by 30%. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Demon Hunter.jpg'>(SP&nbsp;terms)</a>",
        "bow",
        "Диос,Летисия,Нарм,Серебряный Волк,Варна,Имельда,Соня,Дихарт,Тиарис,Айрис,Алустриэль,Оливер,Цубамэ,Тома,Исара,Джо и Конни,Суверен ледяной бездны,Феракуа,Неемия,Серафина,Нож Марк и Ниндзя Гиндзу,Глаз обмана",
        "всадник"
    ],
	[
        "Костяной дино SP",
        "Bone Dino SP",
        "41",
        "45",
        "22",
        "19",
        "5",
        "1",
        "АТК солдат +25%. Когда ОЗ солдат выше 80%, их атака дополнительно увеличивается на 20%. При получения дополнительного действия, солдаты получают [костяную броню]: 'блокирует урон равный 25% от макс ОЗ солдат и увеличивает ЗАЩ на 20%'. Нельзя снять. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Костяной дино.jpg'>(Условия&nbsp;SP)</a>",
        "Soldier ATK +25%. When soldiers' HP is above 80%, their attack is additionally increased by 20%. When receiving an additional action, soldiers gain [Bone Armor]: 'Blocks damage equal to 25% of soldiers' max HP and increases DEF by 20%.' Cannot be removed. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Bone Dino.jpg'>(SP&nbsp;terms)</a>",
        "cavalry",
        "Метью,Соня,Леон,Джаглер,Герольд и Лайла,Листелл,Сакура,Алустриэль,Тогуро,Ака,Ашрам,Хелена,Вернер Дайм,Каролина,Странствующий Дуэлянт,Кагура,Амадей,Эксела,Апофеоз,Андриола,Макишима Агито,Ганн,Элвис,Непокорная небесам,Ора,Д-мен,Аши,Лэйд,Ван,Бернхардт,Сибель,Меч Света и Тьмы,Банши,Гай,Реига",
        "всадник"
    ],
    [
        "Копейщик авангарда SP",
        "Vanguard Lancer SP",
        "46",
        "40",
        "23",
        "20",
        "3",
        "1",
        "Когда ОЗ солдат ниже 80%, их АТК и ЗАЩ увеличиваются на 45%. При вступлении в бой, если ОЗ юнита меньше чем у врага, игнорируется вражеский [щит] (если нет щита, урон солдат увеличивается на 20%), а после боя восстанавливается 30% от потеряного ОЗ. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Копейщик авангарда.jpg'>(Условия&nbsp;SP)</a>",
        "When the soldiers' HP falls below 80%, their ATK and DEF increase by 45%. When entering combat, if the unit's HP is lower than the enemy's, the enemy's [Shield] is ignored (or, if there is no shield, soldier damage increases by 20%), and 30% of lost HP is restored after the battle. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Vanguard Lancer.jpg'>(SP&nbsp;terms)</a>",
        "lance",
        "Варгас,Эмерик,Ланс,Элвин,Алтемюллер,Ленфорд,Леонхарт,Лэндиус,Кадзума,Эмилия,Вираш,Арианход,Отшельник,Шалтир,Клотэр,Мариэль,Рё,Архонт Луны,Кагуя,Лостхэм,Кристиан,Хильда,Ледин,Бьянка,Сибараку",
        "ходьба"
    ],
    [
        "Маг Святой Стражи SP",
        "Holy Guard Mage SP",
        "48",
        "38",
        "25",
        "25",
        "3",
        "1",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Когда юнит подвергается атаке и получает урон снимает с противника 1 бафф, а также увеличивает ЗАЩ и МЗАЩ на 30%. Если тип героя - святой, АТК увеличивется на 30% и герой получает 'имунитет к следующему дебафу, вместо этого отражает его', который нельзя снять. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Маг Святой Стражи.jpg'>(Условия&nbsp;SP)</a>",
        "Physical damage dealt by normal attacks counts as magic damage. When the unit is attacked and takes damage, it removes one buff from the opponent and increases its own DEF and MDEF by 30%. If the hero is of the Holy type, ATK increases by 30% and the hero gains an unremovable effect: 'Immunity to the next debuff; instead, reflect it. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Holy Guard Mage.jpg'>(SP&nbsp;terms)</a>",
        "holy",
        "Альмеда,Анна,Крис,Фрейя,Ледин,Клозе,Селина,Ламбда,Эмилия,Арианход,Мариэль,Мариандель,Азуса,Светоносец,Люгнер,Агнес,Преция,Сафрин,Юлия,Рейга,Сангер,Железный Воитель,Синпати,Шурато",
        "ходьба"
    ],
    [
        "Небесный лучник SP",
        "Sky Archer SP",
        "38",
        "43",
        "17",
        "23",
        "3",
        "2",
        "Режим передвижения юнита меняется на 'полет'. Находясь в небе юнит считается находящимся на местности с ЗАЩ +20%. При активной атаке и вступлении в бой АТК увеличивается на 30%. Если режим передвижения противника не 'полет' или он не находится в небе, солдаты игнорируют 10% его ЗАЩ и с шансом 100% на противника накладывается дебафф 'невозможно использовать пассивные навыки'. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Небесный лучник.jpg'>(Условия&nbsp;SP)</a>",
        "The unit's movement mode changes to 'flight'. While in the air, the unit is treated as occupying terrain that grants +20% DEF. When initiating an attackand entering combat ATK increases by 30%. If the enemy's movement mode is not 'flight' or they are not in the air, the soldiers ignore 10% of the enemy's DEF and apply a 'Passive Skills Disabled' debuff with a 100% chance. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Sky Archer.jpg'>(SP&nbsp;terms)</a>",
        "bow",
        "Альмеда,Рохга,Нарм,Варна,Лиффани,Шельфаниэль,Оливиер,Сумире,Шилинка,Алтина,Флоренция,Мелания,Розенцель,Химико,Патцир,Тома,Мю,Трансцендентный,Мариандель,Ашемар,Вирелия,Эния,Сафрин,Птица с поломанным крылом,Люси,Клаудия,Ранка,Миюки,Кирика,Макира,Омега,Тормил,Эльма,Бозена",
        "полет"
    ],
    [
        "Страж-пехотинец SP",
        "Guardian Infantry SP",
        "53",
        "40",
        "23",
        "23",
        "3",
        "1",
        "Чем выше ОЗ солдат, тем выше их АТК и ЗАЩ (до 45%). При сражении с врагом, чьи ОЗ не ниже чем у юнита, солдаты восстанавливают 20% от макс. ОЗ перед боем и получают на 15% меньше физ. урона. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Страж-пехотинец.jpg'>(Условия&nbsp;SP)</a>",
        "The higher the soldiers' HP - the higher their ATK and DEF (up to 45%). When battling an enemy whose HP is equal to or greater than the unit's, the soldiers restore 20% of their max HP before combat and take 15% less physical damage. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Guardian Infantry.jpg'>(SP&nbsp;terms)</a>",
        "sword",
        "Фрейя,Варгас,Лиффани,Эгберт,Леон,Бернхардт,Элвин,Ленфорд,Джошуа,Леонхарт,Лэндиус,Кадзума,Бетти,Хелена,Альбедо,Клотэр,Вернер Дайм,Ватару,Това,Кристиан,Архонт Луны,Рикки,Светоносец,Полиал,Греншиль,Роланд,Лина,Зелгадис,Андриола,Хофманн,Изольда,Шо Фукамачи,Тирантир,Имир,Капитан Коммандо и Гений-малыш,Норнорин,Нацу,Бьянка,Рапьер,Меч Света и Тьмы,Ван,Ганн,Хильда",
        "ходьба"
    ],
    [
        "Чудище-лобстер SP",
        "Lobster Behemoth SP",
        "45",
        "37",
        "26",
        "19",
        "3",
        "1",
        "Когда ОЗ солдат выше 70%, ЗАЩ увеличивается на 25%. Находясь в воде солдаты получают на 50% меньше урона и когда ОЗ солдат выше 70%, юнит не умирает при получении смертельного урона, вместо этого снимает 1 дебафф и восстанавливает 30% ОЗ (1 раз за бой). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Чудище-лобстер.jpg'>(Условия&nbsp;SP)</a>",
        "When the soldiers' HP is above 70% their DEF increases by 25%. While in water, the soldiers take 50% less damage; additionally if their HP is above 70%, the unit survives a fatal blow, instead removing one debuff and restoring 30% HP (once per battle). <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Lobster Behemoth.jpg'>(SP&nbsp;terms)</a>",
        "water",
        "Лестер,Пьер,Джаглер,Анджелина,Гизаров,Хией,Капитан Джек,Драконоборец,Хранитель волн,Маклейн,Глаз Обмана,Пробужденная,Алканфель,Нимфа",
        "пловец"
    ],
    [
        "Кристальный чародей SP",
        "Crystal Warlock SP",
        "45",
        "37",
        "22",
        "21",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. В конце хода восстанавливает 30% ОЗ солдат. Когда втянут в бой в результате физической атаки снимает с врага 1 бафф и юнит отражает 30% полученного урона. Когда втянут в бой в результате магической атаки солдаты получают на 15% меньше урона. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Кристальный чародей.jpg'>(Условия&nbsp;SP)</a>",
        "Physical damage dealt by normal attacks counts as magic damage. At the end of the turn the soldiers restore 30% of their HP. When engaged in combat initiated by a physical attack the unit removes 1 buff from the enemy and reflects 30% of the damage received. When engaged in combat initiated by a magic attack the soldiers take 15% less damage. <a style='color:#d8c2a9;' target='blank' href='images/soldIcons/SP/Crystal Warlock.jpg'>(SP&nbsp;terms)</a>",
        "mage",
        "Джессика,Бозел,Рэйчел,Анжелика,Дидлит,Ликорис,Отшельник,Злой Бог Крюгер,Патцир,Трансцендентный,Мариандель,Кертес,Дева Ковчега,Густав,Аданкельмо,Девушка в Доспехах,Пробужденная,Лина,Неемия,Джесс,Алканфель,Селика,Вирелия,Алия,Ланделл,Люси,Райза,Ранка,Макира,Хумбаба,Сафрин,Агнес,Яркий Призыватель",
        "ходьба"
    ]
]

function soldView (soldClas) {
	var sd = document.getElementById('sold_data');
	sd.innerHTML = '';
	//sd.innerHTML = soldDat[111][8];
	var i;
	for (i=1;i<soldDat.length;i++){
		if (soldDat[i][10]==soldClas){
			NA = new String(soldDat[i][1]);  //имя солдата по англ. без пробелов для функции показа героев
			heroes = soldDat[i][11].split(",");
			if (heroes[0]!=""){
				h2 = "";
				for (j=0;j<heroes.length;j++){
					hreff = ('hero_en.html?name='+ heroes[j]).replace(/ /g,"%20");
					h2 += '<a href="'+hreff+'"><img style="margin-right:2px;margin-bottom:2px;" height="50px" src="images/head/' + heroes[j] + '.png" title="' + heroes[j] + '"></a>';
				}
			} else {h2 = "";}
			sd.innerHTML += '<div style="display:block;width:95%;height:160px;margin-bottom:0px;"><div style="display:block;width:130px;float:left;"><img src="images/soldIcons/all/' + soldDat[i][0] + 
			'.png" height="150px" /></div><div style="display:block;width:700px;float:left;"><b style="font-size: 23px;margin-right: 50px;vertical-align:super;">' + soldDat[i][1]+ 
			'</b> <img src="images/'+soldDat[i][12]+'.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][6] + 
			'</span> <img src="images/Icon_Range.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][7] + 
			'</span> <img id="sold_hero_click" onclick=iconHeroOpen("' + NA.replace(/ /g,"") + '") src="images/icon.png" height="25px" /><span style="vertical-align:super;font-size:small;">(click to see heroes)</span></div><br><br><div><img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:30px;">HP: ' + soldDat[i][2]  + 
			'</span><img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:30px;">ATK: ' + soldDat[i][3]  + 
			'</span><img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:30px;">DEF: ' + soldDat[i][4]  + 
			'</span><img src="images/sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:30px;">MDEF: ' + soldDat[i][5]  + 
			'</span></div><div style="white-space: normal;"><span style="font-size:18px;font-style:italic;">' + soldDat[i][9]  + 
			'</div></div><div class="hero_face ' + NA.replace(/ /g,"")  + '">' + h2 + '</div>';
		}
	}
}

function iconHeroOpen(hero){
	tempOpen = document.getElementsByClassName(hero);
	if (tempOpen[0]){
		if (tempOpen[0].classList.contains('hero_face')){

			tempOpen[0].className = tempOpen[0].className.replace("hero_face", "hero_face_open")
		} else if (tempOpen[0].classList.contains('hero_face_open')){

			tempOpen[0].className = tempOpen[0].className.replace("hero_face_open", "hero_face")
		}
	}
}


