// soldDat.length  -  колл-во всех солдат
// soldDat[0].length  -  колл-во элементов у солдат
// 0 - имя рус, 1 - имя англ., 2 - ОЗ, 3 - атк, 4 - защ, 5 - мзащ, 6 - мобильность, 7 - дальность, 8 - описание рус, 9 - описание англ.
var soldDat = [
    [
        "NAME RUS",
        "NAME ENG",
        "HP",
        "ATK",
        "DEF",
        "MDEF",
        "MOBILITY",
        "RANGE",
        "DESC RUS",
        "DESC ENG",
        "CLASS"
    ],
    [
        "Пехота",
        "Infantry",
        "28",
        "26",
        "15",
        "12",
        "3",
        "1",
        "Базовый юнит",
        "Basic Infantry",
        "sword"
    ],
    [
        "Элитная пехота",
        "Elite Infantry",
        "34",
        "31",
        "18",
        "14",
        "3",
        "1",
        "При инициировании боя получаемый урон снижается на 20%",
        "When attacking and entering battle, damage taken reduces by 20%",
        "sword"
    ],
    [
        "Орк",
        "Orc",
        "34",
        "31",
        "17",
        "13",
        "3",
        "1",
        "При инициировании боя АТК увеличивается на 20%",
        "When attacking and entering battle, ATK increases by 20%",
        "sword"
    ],
    [
        "Воин",
        "Warrior",
        "31",
        "34",
        "17",
        "14",
        "3",
        "1",
        "При инициировании боя шанс критического удара увеличивается на 20%",
        "When attacking and entering battle, critical hit rate increases by 20%",
        "sword"
    ],
    [
        "Служанка",
        "Maid",
        "28",
        "31",
        "18",
        "18",
        "3",
        "1",
        "Когда ОЗ солдат выше 80%, АТК увеличивается на 20%",
        "When soldier HP is above 80%, ATL increases by 20%",
        "sword"
    ],
    [
        "Тяжелая пехота",
        "Heavy Infantry",
        "43",
        "40",
        "23",
        "19",
        "3",
        "1",
        "При инициировании боя АТК солдат увеличивается на 30%. Когда атакованы, ЗАЩ солдат увеличивается на 30%",
        "When attacking and entering battle, soldier's ATK increases by 30%. When forced into battle, soldier's DEF increases by 30%",
        "sword"
    ],
    [
        "Страж-пехотинец",
        "Guardian Infantry",
        "53",
        "37",
        "23",
        "19",
        "3",
        "1",
        "Когда атакованы и ОЗ солдат выше 80%, ЗАЩ солдат увеличивается на 45%",
        "When  attacked and soldier HP is above 80%, soldier's DEF increases by 45%",
        "sword"
    ],
    [
        "Горец-воин",
        "Highland Warrior",
        "43",
        "40",
        "22",
        "20",
        "3",
        "1",
        "АТК увеличивается на 15% и получаемый урон уменьшается на 15%",
        "ATK increases by 15% and damage received decreases by 15%.",
        "sword"
    ],
    [
        "Орк-берсерк",
        "Orc Berserker",
        "43",
        "40",
        "22",
        "17",
        "3",
        "1",
        "Когда ОЗ солдат выше 80%, АТК увеличивается на 45%",
        "When soldier's HP above 80%, ATK increases by 45%.",
        "sword"
    ],
    [
        "Циклоп",
        "Cyclope",
        "48",
        "43",
        "20",
        "19",
        "3",
        "1",
        "Когда атакуете врагов с меньшим процентом ОЗ, чем у этого юнита, АТК и ЗАЩ увеличиваются на 30% после вступления в бой",
        "When attacking enemies with lower HP%, ATK and DEF increases by 30%.",
        "sword"
    ],
    [
        "Темный страж",
        "Dark Guard",
        "53",
        "37",
        "23",
        "19",
        "3",
        "1",
        "При инициировании боя, после боя наносит врагу урон, равный 15% от макс. ОЗ. Восстанавливает ОЗ солдат на 30%",
        "When attacking, after battle, deals damage equal to 15% of max HP of the enemy, Restores 30% of soldier's HP.",
        "sword"
    ],
    [
        "Берсерк",
        "Berserker",
        "40",
        "43",
        "22",
        "19",
        "3",
        "1",
        "Шанс критического удара увеличивается на 30%, АТК увеличивается на 15%",
        "Critical hit rate increases by 30%. ATK increases by 15%.",
        "sword"
    ],
    [
        "Служанка в маске",
        "Masked Maid",
        "36",
        "40",
        "23",
        "23",
        "3",
        "1",
        "Перед вступлением в бой АТК, ЗАЩ И МЗАЩ солдат увеличиваюся на 45% в обмен на 5% от текущего кол-ва ОЗ юнита",
        "Before entering battle, soldier's ATK, DEF and MDEF increase by 45% in exchange for 5% of the unit's current HP.",
        "sword"
    ],
    [
        "Киборг-сосуд",
        "Cyborg Vessel",
        "40",
        "43",
        "22",
        "19",
        "3",
        "1",
        "Когда атакуете, может атаковать на расстоянии вместе с героем, а солдаты наносят +30% урона",
        "When attacking, can engage in ranged attack along with the hero,and soldier's dealed damage increases by 30%.",
        "sword"
    ],
    [
        "Королевский страж",
        "Royal Protector",
        "43",
        "40",
        "22",
        "23",
        "3",
        "1",
        "Когда атакован, солдаты получают +1 к дальности, 30% к АТК и получают на 30% меньше магического урона",
        "When attacked, soldiers gain +1 range, ATK increases by 30% and magic damage taken decreases by 30%.",
        "sword"
    ],
    [
        "Воин-варвар",
        "Barbarian Warrior",
        "48",
        "43",
        "20",
        "19",
        "3",
        "1",
        "Когда атакуете врагов, чей процент ОЗ равен или ниже, чем у этого юнита, АТК солдат увеличивается на 45%. Когда атакуете врагов, чей процент ОЗ выше, чем у этого юнита, АТК и ЗАЩ  солдат увеличиваются на 30%",
        "When attacking enemies with equal or lower HP%, soldier's ATK increases by 45%. When attacking enemies with higher HP%, soldier's ATK and DEF increases by 30%.",
        "sword"
    ],
    [
        "Наемник пустыни",
        "Sand Sea Mercenary",
        "45",
        "43",
        "22",
        "20",
        "3",
        "1",
        "При вступлении в бой АТК, ЗАЩ и МЗАЩ солдат повышается на 20%. После совершения действия солдаты восстанавливают 20% ОЗ. Если в радиусе 1 клетки нет дружественных юнитов, эффект удваивается",
        "When entering battle, soldier's ATK, DEF and MDEF increase by 20%. After taking action, soldiers recover 20% of HP. When there are no allies within 1 block, all of the above effect are doubled.",
        "sword"
    ],
    [
        "Галантный дуэлянт",
        "Gallant Duelist",
        "43",
        "43",
        "23",
        "20",
        "4",
        "1",
        "При атаке солдат АТК и шанс критического удара увеличиваются на 30%. При атаке есть 60% шанс, что солдаты получат меньше физического урона на 25%",
        "When initiating battle, soldier's ATK and Crit Rate increase by 30%. When attacked, there is a 60% chance that soldiers will take reduced by 25% physical damage.",
        "sword"
    ],
    [
        "Копейщик",
        "Lancer",
        "31",
        "24",
        "17",
        "10",
        "3",
        "1",
        "Базовый юнит",
        "Basic Lancer",
        "lance"
    ],
    [
        "Элитный копейщик",
        "Elite Lancer",
        "37",
        "29",
        "20",
        "12",
        "3",
        "1",
        "Когда атакованы, наносимый в ответ урон увеличивается на 20%",
        "When attacked, damage dealt increases by 20%.",
        "lance"
    ],
    [
        "Амазонка",
        "Amazon",
        "31",
        "34",
        "17",
        "16",
        "3",
        "1",
        "При инициировании боя АТК  увеличивается на 20%",
        "When attacking, ATK increases by 20%.",
        "lance"
    ],
    [
        "Горный голем",
        "Rock Golem",
        "37",
        "26",
        "22",
        "12",
        "3",
        "1",
        "Когда ОЗ солдат ниже 70%, ЗАЩ увеличивается на 20%",
        "When soldier's HP is below 70%, DEF increases by 20%.",
        "lance"
    ],
    [
        "Фаланга",
        "Phalanx",
        "48",
        "37",
        "26",
        "16",
        "3",
        "1",
        "Получаемый физ. Урон снижается на 30%",
        "Physical damage taken decreased by 30%.",
        "lance"
    ],
    [
        "Каменный колосс",
        "Stone Colossus",
        "48",
        "34",
        "28",
        "16",
        "3",
        "1",
        "Когда ОЗ солдат ниже 70%, получаемый урон снижается на 30%",
        "When soldier's HP is below 70%, damage taken decreased by 30%.",
        "lance"
    ],
    [
        "Тяжелый центурион",
        "Heavy Centurion",
        "48",
        "37",
        "23",
        "17",
        "3",
        "1",
        "Когда атакованы, АТК и ЗАЩ увеличиваются на 30%",
        "When attacked, ATK and DEF increase by 30%.",
        "lance"
    ],
    [
        "Лавовый титан",
        "Lava Titan",
        "53",
        "34",
        "26",
        "19",
        "3",
        "1",
        "После совершения действия накладывает [Ожог] на 1 врага в пределах 2 клеток. Ожог: после совершения действия теряет 30% макс. ОЗ в виде фиксированного урона",
        "After taking action, casts Burn on 1 enemy within 2 block. Burn: Lose 30% of max HP as fixed damage after taking action.",
        "lance"
    ],
    [
        "Копейщик авангарда",
        "Vanguard Lancer",
        "43",
        "40",
        "23",
        "17",
        "3",
        "1",
        "Когда ОЗ солдат ниже 70%, АТК увеличивается на 45%",
        "When soldier's HP is below 70%, ATK iincreases by 45%.",
        "lance"
    ],
    [
        "Темный центурион",
        "Dark Centurion",
        "48",
        "40",
        "26",
        "16",
        "3",
        "1",
        "Когда атакованы и ОЗ солдат выше 10%, после боя с 100% шансом активирует урон героя [Шип]",
        "When attacked, and soldier's HP is above 10%, 100% chance to trigger Hero's Barb damage after the battle. Barb: deals fixed damage to enemy.",
        "lance"
    ],
    [
        "Амазонка-чемпион",
        "Amazon Champion",
        "40",
        "43",
        "22",
        "20",
        "3",
        "1",
        "При инициировании боя АТК увеличивается на 30%. С 75% шансом снижает ЗАЩ врага на 20%. Длится 1 ход",
        "When attacking, ATK increases by 30%. 75% chance to reduce enemy's DEF by 20%. Lasts 1 turn.",
        "lance"
    ],
    [
        "Ваятель кристаллов",
        "Crystal Molder",
        "48",
        "34",
        "22",
        "22",
        "3",
        "1",
        "После совершения действия восстанавливает 30% ОЗ солдат. Будучи втянутыми в бой из-за магической атаки, войска отражают 30% полученного урона",
        "After taking action, restores 30% of soldier's HP. When forced into battle with magic attack, unit reflects 30% of damage received.",
        "lance"
    ],
    [
        "Страж-энт",
        "Treant Guard",
        "43",
        "43",
        "23",
        "17",
        "3",
        "1",
        "Эффективность исцеления солдат увеличивается на 30%. Когда ОЗ солдат равно 100%, АТК ЗАЩ и МЗАЩ увеличиваются на 45%",
        "Healing received by soldiers increased by 30%. When soldier's HP is at 100%, ATK, DEF and MDEF increase by 45%.",
        "lance"
    ],
    [
        "Солдат фаланги",
        "Hoplite",
        "43",
        "43",
        "23",
        "17",
        "3",
        "1",
        "АТК и ЗАЩ солдат увеличиваются на 20%. Когда активно атакуете, наносимый солдатами урон увеличивается на 20% и юнит игнорирует недостатки класса",
        "Soldier's ATK and DEF increase by 20%. When attacking, damage dealt increase by 20%, and unit ignores class disadvantage.",
        "lance"
    ],
    [
        "Страж государства",
        "State Guard",
        "43",
        "43",
        "22",
        "22",
        "3",
        "1",
        "АТК солдат увеличивается на 30%. При инициировании боя солдаты игнорируют 15% ЗАЩ врага. Перед тем, как быть втянутыми в бой, вражеские солдаты наносят на 6% больше урона за каждую 1 клетку, пройденную врагом перед атакой (до 30%)",
        "Soldier's ATK increases by 30%. When attacking, soldiers ignore 15% of enemy's DEF. Before being forced into battle, for every block moved by the enemy, soldiers deal 6% increased damage (up to 30%).",
        "lance"
    ],
    [
        "Эльфийский метатель копья",
        "Elven Spear Thrower",
        "45",
        "43",
        "24",
        "20",
        "3",
        "1",
        "АТК солдат увеличивается на 30%. При дальней атаке может контратаковать, получаемый физ. Урон снижен на 20%",
        "Soldier's ATK increases by 30%. When attacked with a range attack, can counterattack and taked 20% reduced physical damage.",
        "lance"
    ],
    [
        "Кавалерия",
        "Cavalry",
        "26",
        "28",
        "14",
        "11",
        "5",
        "1",
        "Базовый юнит",
        "Basic Cavalry",
        "cavalry"
    ],
    [
        "Волк",
        "Wolf",
        "22",
        "29",
        "14",
        "11",
        "5",
        "1",
        "Базовый юнит",
        "Basic Cavalry",
        "cavalry"
    ],
    [
        "Элитная кавалерия",
        "Elite Cavalry",
        "31",
        "34",
        "17",
        "13",
        "5",
        "1",
        "При инициировании боя получаемый урон снижается на 20%",
        "When attacking, damage taken is reduced  by 20%.",
        "cavalry"
    ],
    [
        "Рогатый дино",
        "Horned Dino",
        "28",
        "35",
        "16",
        "14",
        "5",
        "1",
        "Когда у солдат 100% ОЗ, АТК увеличивается на 20%",
        "When soldier's HP is 100%, ATK increases by 20%.",
        "cavalry"
    ],
    [
        "Паладин",
        "Paladin",
        "31",
        "31",
        "17",
        "20",
        "5",
        "1",
        "В битвах против демонов АТК и ЗАЩ увеличиваются на 30%",
        "When battling against Demons, ATK and DEF increase by 30%.",
        "cavalry"
    ],
    [
        "Тяжелая кавалерия",
        "Heavy Cavalry",
        "40",
        "43",
        "22",
        "17",
        "5",
        "1",
        "АТК увеличивается на 20%",
        "ATK increases by 20%.",
        "cavalry"
    ],
    [
        "Драгун",
        "Dragoon",
        "43",
        "43",
        "22",
        "19",
        "5",
        "1",
        "При инициировании боя АТК и ЗАЩ увеличиваются на 30%",
        "When attacking, ATK and DEF increase by 30%.",
        "cavalry"
    ],
    [
        "Костяной дино",
        "Bone Dino",
        "36",
        "45",
        "20",
        "19",
        "5",
        "1",
        "Когда ОЗ солдат выше 80%, АТК увеличивается на 45%",
        "When soldier's HP is above 80%, ATK increase by 45%.",
        "cavalry"
    ],
    [
        "Адский пес",
        "Hell Hound",
        "40",
        "45",
        "20",
        "19",
        "5",
        "1",
        "Инициировав битву, увеличивает урон, получаемый всеми вражескими юнитами в радиусе 2 клеток, на 20% на 2 хода",
        "After initiating battle, increases damage taken by all enemy units within 2 blocks by 20% for 2 turns.",
        "cavalry"
    ],
    [
        "Страж-кавалерист",
        "Guardian Cavalry",
        "43",
        "40",
        "23",
        "17",
        "5",
        "1",
        "При инициировании боя получаемый урон снижается на 45%",
        "When attacking, damage taken is reduced by 45%.",
        "cavalry"
    ],
    [
        "Королевская кавалерия",
        "Royal Cavalry",
        "43",
        "43",
        "23",
        "17",
        "5",
        "1",
        "Когда ОЗ солдат выше 80%, получаемый физ. Урон снижается на 45%",
        "When soldier's HP is above 80%, physical damage taken is decreased by 45%.",
        "cavalry"
    ],
    [
        "Небесный страж",
        "Heavensguard",
        "36",
        "43",
        "22",
        "22",
        "5",
        "1",
        "АТК солдат увеличивается на 15% с каждой пройденной до атаки клеткой (до 45%)",
        "Soldier's ATK increases by 15% (up to 45%) for each block moved before battle.",
        "cavalry"
    ],
    [
        "Рыцарь-тамплиер",
        "Templar Knight",
        "40",
        "40",
        "22",
        "26",
        "5",
        "1",
        "В битвах против [Демонов] АТК и ЗАЩ увеличиваются на 45%, МЗАЩ увеличивается на 45%",
        "When battling against Demons, ATK and DEF increase by 45%. MDEF increases by 45%.",
        "cavalry"
    ],
    [
        "Единорог",
        "Unicorn",
        "43",
        "43",
        "22",
        "22",
        "5",
        "1",
        "\"Физический урон, наносимый обычными атаками, считается магическим уроном. Тип перемещения юнита изменяется на \"\"Мастер-партизан\"\". При сражении в лесах, горах или на пастбище АТК и МЗАЩ повышаются на 30%\"",
        "Physical damage, dealt by normal attacks is treated by magic damage. Unit movement type is changed to Terrain Master, When fighting on forest, mountain or grassland, ATK and MDEF increase by 30%.",
        "cavalry"
    ],
    [
        "Скорпион",
        "Scorpio",
        "43",
        "43",
        "23",
        "17",
        "5",
        "1",
        "Когда атакуете, АТК солдат +15% и крит +30%. [Пассивный] Получаемый урон снижен на 30% во время сражений в пустыне, песчаных дюнах или пещерах",
        "When attacking, soldier's ATK increases by 15%, critical rate increases by 30%. Damage taken is reduced by 30%, when fighting in desert, sand dune and cave.",
        "cavalry"
    ],
    [
        "Механический рыцарь",
        "Mechanical Knight",
        "43",
        "43",
        "22",
        "20",
        "5",
        "1",
        "Когда атакуете, АТК солдат +30%. Когда атакован, ЗАЩ солдат +15%. Когда солдаты с 80% или более ОЗ проходят по местности с бонусом защиты, юнит получает шанс отменить снижение мобильности на 2 клетки",
        "When attacking, soldier's ATK increases by 30%. When attacked, soldier's DEF increases by 15%. When soldiers pass defensive terrain with 80% HP or more, unit gains a chance to negate 2 blocks of mobility reduction.",
        "cavalry"
    ],
    [
        "Золотой рыцарь",
        "Godlen Knight",
        "43",
        "43",
        "22",
        "22",
        "5",
        "1",
        "Получаемый урон уменьшается на 20%, когда у солдат 100% ОЗ. АТК и ЗАЩ солдат увеличиваются на 30%, когда у героя класс [Кавалерия]",
        "Damage received is decreased when soldier's HP is 100%. ATK and DEF increases by 30%, when the Hero's class is Cavalry.",
        "cavalry"
    ],
    [
        "Гигантский всадник-ящерица",
        "Giant Lizard Rider",
        "43",
        "43",
        "24",
        "19",
        "5",
        "1",
        "АТК и ЗАЩ солдат увеличиваются на 25%. При начале битвы, если в пределах 1 блока от цели нет других врагов, АТК увеличивается еще на 20%",
        "Soldier's ATK and DEF increase by 25%. When initiating battle, if there are no other enemies within 1 block of the target, ATK increases further by 20%.",
        "cavalry"
    ],
    [
        "Всадник - ястреб",
        "Hawk Rider",
        "26",
        "29",
        "13",
        "15",
        "5",
        "1",
        "Базовый юнит",
        "Basic Flier",
        "fly"
    ],
    [
        "Всадник-грифон",
        "Griffin Rider",
        "31",
        "35",
        "16",
        "18",
        "5",
        "1",
        "Когда ОЗ солдат выше 80%, получаемый урон снижается на 20%",
        "When soldier's HP is above 80%, damage taken is decreased by 20%.",
        "fly"
    ],
    [
        "Малый бес",
        "Lesser Imp",
        "34",
        "35",
        "17",
        "17",
        "5",
        "1",
        "Когда атакуете юниты со 100% ОЗ, АТК увеличивается на 20% после вступления в бой",
        "When attacking units with 100% HP, after entering battle, ATK increases by 20%.",
        "fly"
    ],
    [
        "Всадник-пегас",
        "Pegasus Rider",
        "31",
        "34",
        "18",
        "18",
        "5",
        "1",
        "Когда подвергаетесь дальней атаке, получаемый урон снижается на 30%",
        "When attacked with a ranged attack, damage taken is decreased by 30%.",
        "fly"
    ],
    [
        "Рыцарь-грифон",
        "Griffin Knight",
        "40",
        "45",
        "20",
        "23",
        "5",
        "1",
        "Когда ОЗ солдат выше 80%, АТК и ЗАЩ увеличиваются на 30%",
        "When soldier's HP is above 80%, ATK and DEF increase by 30%.",
        "fly"
    ],
    [
        "Ангел",
        "Angel",
        "43",
        "43",
        "22",
        "26",
        "5",
        "1",
        "Получаемый маг. Урон снижается на 45%. Когда ОЗ солдат выше 50%, АТК и ЗАЩ увеличиваются на 20%",
        "Magic damage taken decreases by 45%. When soldier's HP ATK and DEF increase by 20%.",
        "fly"
    ],
    [
        "Летучая мышь-вампир",
        "Vampire Bat",
        "43",
        "45",
        "22",
        "22",
        "5",
        "1",
        "После инициирования боя солдаты могут восстановить ОЗ (45% от нанесенного урона) после боя",
        "After attacking, soldiers can restore HP (45% of damage dealt) after battle.",
        "fly"
    ],
    [
        "Горгулья",
        "Gargoyle",
        "43",
        "45",
        "22",
        "22",
        "5",
        "1",
        "Когда ОЗ солдат выше 50%, АТК увеличивается на 30%. Когда ОЗ солдат ниже 50%, ЗАЩ увеличивается на 30%",
        "When soldier's HP is above 50%, ATK increases by 30%. When soldier's PH is below 50%, DEF increases by 30%.",
        "fly"
    ],
    [
        "Святой пегас",
        "Holy Pegasus",
        "40",
        "43",
        "23",
        "23",
        "5",
        "1",
        "Если до инициирования боя ОЗ солдат выше 50%, с 100% шансом снижает получаемый урон на 50%",
        "When soldier's HP is above 50%, before attacking, has a 100% chance to decrease damage taken by 50%.",
        "fly"
    ],
    [
        "Железокрылый воин",
        "Steel Wing Warrior",
        "43",
        "45",
        "22",
        "22",
        "5",
        "1",
        "Когда атакуете, к АТК солдат прибавляется 30%. Когда атакованы с дальней дистанции, к ЗАЩ и МЗАЩ солдат прибавляется +30%",
        "When attacking, soldier's ATK increases by 30%. When ranged attacked, soldier's DEF and MDEF increase by 30%.",
        "fly"
    ],
    [
        "Солдат-драконианец",
        "Dragon Trooper",
        "43",
        "43",
        "23",
        "22",
        "5",
        "1",
        "АТК солдат увеличивается на 6% за каждую пройденную перед атакой клетку (до 30%), получаемый урон уменьшается на 6% (до 30%). Когда атакованы, солдаты получают +2 к мобильности, длится 1 ход.",
        "Soldier's ATK increases by 6% (up to 30%) for each block moved before battle, and damage taken is reduced by 6% (up to 30%). After being attacked and taking damage, unit mobility is increased by 2. Lasts 1 turn.",
        "fly"
    ],
    [
        "Рыцарь на механическом драконе",
        "Mechanical Dragon Knight",
        "43",
        "45",
        "24",
        "18",
        "5",
        "1",
        "АТК и ЗАЩ увеличиваются на 25%. Когда подвергаетесь ближней атаке, получаемый физический урон снижается на 25%",
        "ATK and DEF are increased by 25%. When melee attacked, physical damage taken is reduced by 25%.",
        "fly"
    ],
    [
        "Боевой сокол",
        "War Falcon",
        "45",
        "47",
        "24",
        "23",
        "5",
        "1",
        "При сражении с врагом, мобильность которого не выше вашей, АТК и ЗАЩ увеличиваются на 30%. Если тип юнита героя [Ас], при активной атаке он получает 30% меньше урона",
        "When fighting with the enemy, whose mobility is not greater than that unit, ATK and DEF increase by 30%. If the Hero's class is Flier, takes 30% decreased damage when activly attacking.",
        "fly"
    ],
    [
        "Тритон",
        "Merman",
        "28",
        "26",
        "15",
        "12",
        "3",
        "1",
        "Базовый юнит",
        "Basic Aquatic",
        "water"
    ],
    [
        "Элитный тритон",
        "Merman Lord",
        "34",
        "31",
        "18",
        "14",
        "3",
        "1",
        "Во время боев на воде АТК увеличивается на 20%",
        "During water battles, ATK increases by 20%.",
        "water"
    ],
    [
        "Лобстер",
        "Lobster",
        "34",
        "29",
        "20",
        "12",
        "3",
        "1",
        "Когда атакуете юниты со 100% ОЗ, АТК увеличивается на 20% после вступления в бой",
        "When attacking enemy with 100% HP, after entering battle, ATK increases by 20%.",
        "water"
    ],
    [
        "Мастер приливов",
        "Tide Master",
        "43",
        "40",
        "23",
        "19",
        "3",
        "1",
        "Когда в воде, АТК и ЗАЩ увеличиваются на 30%",
        "When in water, ATK and DEF increase by 30%.",
        "water"
    ],
    [
        "Чудище-лобстер",
        "Lobster Behemoth",
        "43",
        "37",
        "26",
        "16",
        "3",
        "1",
        "Когда в воде, получаемый урон снижается на 30%",
        "When in water, damage taken is decreased by 30%.",
        "water"
    ],
    [
        "Левиафан",
        "Leviathan",
        "43",
        "40",
        "23",
        "19",
        "3",
        "2",
        "Когда в воде и атакуете юнит с ОЗ выше 50%, АТК увеличивается на 40%",
        "When in water and attacking enemy with HP above 50%, after entering battle, ATK increases by 40%.",
        "water"
    ],
    [
        "Ящер",
        "Lizardman",
        "40",
        "43",
        "22",
        "19",
        "3",
        "1",
        "Когда в воде, АТК увеличивается на 45%",
        "When in water, ATK increases by 45%.",
        "water"
    ],
    [
        "Эльф прилива",
        "Tidal Elf",
        "43",
        "37",
        "23",
        "22",
        "3",
        "1",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. В воде физический урон, получаемый солдатами, снижается на 45%, а их АТК увеличивается на 20%",
        "Physical damage deals by normal attacks is treated as magic damage. When in water, physical damage taken by soldiers is decreased by 45%, ATK increases by 20%.",
        "water"
    ],
    [
        "Морской пират",
        "Pirate Raider",
        "43",
        "40",
        "22",
        "22",
        "3",
        "2",
        "В воде юнит не подвержен штрафам за ближний бой, весь получаемый солдатами урон снизится на 30%, а их АТК повысится на 20%. После активного нанесения урона врагу в воде крадет 1 бафф",
        "When in water, unit is not affected by melee damage penalty, all damage taken by a soldiers decreased by 30%, and ATK increases by 20%. After actively dealing damage o the enemy in water, steals 1 buff.",
        "water"
    ],
    [
        "Элементаль льда",
        "Glacial Elemental",
        "43",
        "40",
        "22",
        "24",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Когда атакуете и вступаете в бой, после боя может с 50% шансом наложить на цель мощный дебафф. В воде АТК увеличивается на 40%, а атаки юнитов не подвергаются штрафу за ближний бой",
        "Physical damage deals by normal attacks is treated as magic damage. When attacking, and entering battle,  has a 50% chance of applying strong debuff to the target after battle. When in water, ATK increases by 40%, and the unit's attacks are not affected by melee damage reduction.",
        "water"
    ],
    [
        "Жрец океана",
        "Ocean Priest",
        "43",
        "37",
        "23",
        "26",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. В воде АТК и МЗАЩ увеличиваются на 40%, получаемые лечебные эффекты увеличиваются на 30%, а атаки юнитов не подвергаются штрафу за ближний бой",
        "Physical damage deals by normal attacks is treated as magic damage. When in water, ATK and MDEF increase by 40%, healing effects received increase by 30%, and the unit's attacks are not affected by melee damage reduction.",
        "water"
    ],
    [
        "Лучник",
        "Archer",
        "22",
        "26",
        "12",
        "15",
        "3",
        "2",
        "Базовый юнит",
        "Basic Archer",
        "bow"
    ],
    [
        "Всадник - арбалетчик",
        "Crossbow Rider",
        "23",
        "24",
        "13",
        "13",
        "5",
        "2",
        "Базовый юнит",
        "Basic Archer with increased mobility",
        "bow"
    ],
    [
        "Эльф",
        "Elf",
        "26",
        "31",
        "14",
        "18",
        "3",
        "2",
        "АТК увеличивается на 20% в [Лесных] и [Горных] местностях",
        "ATK increases by 20% in wood and mountain terrain.",
        "bow"
    ],
    [
        "Баллиста",
        "Ballista",
        "24",
        "29",
        "13",
        "16",
        "3",
        "2",
        "Увеличивает дальность обычной атаки на 1. Когда атакуете, наносимый урон снижается на 20%",
        "Increases normal attack range by 1. When attacking, unit damage decreases by 20%.",
        "bow"
    ],
    [
        "Темный эльф",
        "Dark Elf",
        "24",
        "31",
        "13",
        "20",
        "3",
        "2",
        "Когда атакуете юниты со 100% ОЗ, АТК  увеличивается на 20% после вступления в бой",
        "When attacking units with 100% HP, after entering battle, ATK increases by 20%.",
        "bow"
    ],
    [
        "Меткий стрелок",
        "Sharpshooter",
        "28",
        "29",
        "16",
        "16",
        "5",
        "2",
        "При инициировании боя с 30% шансом снижает ЗАЩ врага на 20%. Длится 1 ход",
        "When attacking, 30% chance to reduce enemy's DEF by 20%. Lasts 1 turn.",
        "bow"
    ],
    [
        "Эльф-мастер",
        "Elf Master",
        "34",
        "40",
        "19",
        "23",
        "3",
        "2",
        "АТК и ЗАЩ увеличиваются на 30% в [Лесных] и [Горных] местностях",
        "ATK and DEF increases by 30% in woods and mountains.",
        "bow"
    ],
    [
        "Небесный лучник",
        "Sky Archer",
        "36",
        "40",
        "17",
        "23",
        "3",
        "2",
        "Движение юнита изменено на [Полет]. Атаковав и вступив в бой, вы получаете +30% к АТК",
        "Unit's movement status is changed to Flying. Upon attacking and entering battle, ATK increases by 30%.",
        "bow"
    ],
    [
        "Темный эльф-снайпер",
        "Dark Elf Sniper",
        "31",
        "40",
        "17",
        "26",
        "3",
        "2",
        "Когда атакуете юниты со 100% ОЗ, АТК и ЗАЩ  увеличиваются на 45% после вступления в бой",
        "When attacking units with 100% HP, after entering battle, ATK and DEF increase by 45%.",
        "bow"
    ],
    [
        "Снайпер-подстрекатель",
        "Firebrand Sniper",
        "34",
        "40",
        "19",
        "23",
        "3",
        "2",
        "При инициировании боя АТК увеличивается на 30%. После боя наносит доп. Урон, равный 15% от макс. ОЗ",
        "When attacking, ATK increases by 30%. Deals extra damage equal to 15% of enemy's max HP after battle.",
        "bow"
    ],
    [
        "Катапульта",
        "Catapult",
        "31",
        "37",
        "17",
        "20",
        "3",
        "2",
        "Дальность обычной атаки юнита увеличивается на 1. Когда атакуете, урон юнита снижается на 10%, есть 20% шанс наложить сильный дебафф",
        "Unit's normal attack range increased by 1. When attacking, unit's damage decreases by 10%. There is 20% chance to  deal 1 random debuff.",
        "bow"
    ],
    [
        "Охотник на демонов",
        "Demon Hunter",
        "36",
        "37",
        "20",
        "20",
        "5",
        "2",
        "До иниирования боя с 75% шансом снижает мобильность врага на 2 и снижает ЗАЩ на 20%. Длится 1 ход",
        "Before attacking, has a 75% chance to reduce enemy's mobility by 2 and decreae DEF by 20%. Lasts 1 turn.",
        "bow"
    ],
    [
        "Рейнджер вихря",
        "Bolt Ranger",
        "40",
        "37",
        "22",
        "19",
        "5",
        "2",
        "Когда ОЗ выше 50%, перед тем, как быть втянутыми в бой, с 100% шансом снижает получаемый урон на 50%",
        "If attacked when HP is above 50%, has 100% chance to decrease damage taken by 50% before entering damage.",
        "bow"
    ],
    [
        "Гном-авантюрист",
        "Dwarf Adventurer",
        "34",
        "37",
        "17",
        "20",
        "3",
        "2",
        "Все навыки героев становятся линейными. Наносимый юнитом урон увеличивается на 15%",
        "Hero's skills all become linear skills. Unit damage dealt increases by 15%.",
        "bow"
    ],
    [
        "Конный лучник эльфов",
        "Elven Cavarly Archer",
        "36",
        "40",
        "20",
        "23",
        "5",
        "2",
        "АТК солдат увеличивается на 20%. Когда сражаетесь в [Лесу], на [Равнинах] или в [Горах], АТК увеличивается на доп. 15%, получаемый магический урон уменьшается на 30% и урон юнита не уменьшается в ближнем бою",
        "Soldier's ATK increases by 20%. When fighting on forest, crossland and mountain, ATK increases by an extra 15%, magic damage taken decreases by 30%, unit's damage is not reduced in melee battles.",
        "bow"
    ],
    [
        "Осадная баллиста",
        "Siege Ballista",
        "34",
        "41",
        "19",
        "21",
        "3",
        "2",
        "Дальность обычной атаки юнита увеличивается на 1. АТК увеличивается на 20%. Если юнит не двигался перед битвой, АТК увеличивается еще на 15%. Если прошел более чем через 3 клетки, наносимый в бою урон уменьшается на 30%",
        "Unit's normal attack range increased by 1. ATK is increased by 20%. If the unit did not moved before battle, ATK increased by extra 15%. If it moved more than 3 blocks, damage dealt in damage is decreased by 30%.",
        "bow"
    ],
    [
        "Палубный стрелок",
        "Deck Gunner",
        "40",
        "45",
        "22",
        "20",
        "3",
        "2",
        "АТК солдат увеличивается на 30%. При активной атаке, если этот юнит или противник находятся в оборонительной местности, 15% защиты противника игнорируется в этом бою",
        "Soldier's ATK increases by 30%. When actively attacking, is either this unit or the enemy is on defensive terrain, 15% of enemy's DEF is ignored for this battle.",
        "bow"
    ],
    [
        "Вор",
        "Thief",
        "26",
        "26",
        "13",
        "13",
        "3",
        "2",
        "Базовый юнит",
        "Basic  Assassin",
        "assasin"
    ],
    [
        "Засадный боец",
        "Ambusher",
        "31",
        "31",
        "16",
        "16",
        "3",
        "2",
        "Крит увеличивается на 30%",
        "Crit increased by 30%.",
        "assasin"
    ],
    [
        "Куноити",
        "Kunoichi",
        "31",
        "29",
        "17",
        "20",
        "3",
        "2",
        "Крит увеличивается на 30%. Критические удары накладывают на врагов 1 случайный дебафф",
        "Crit increased by 30%. Critical hits inflict 1 random debuff on enemy.",
        "assasin"
    ],
    [
        "Бандит",
        "Bandit",
        "40",
        "40",
        "20",
        "20",
        "3",
        "2",
        "Крит увеличивается на 30%, АТК увеличивается на 15%",
        "Crit increased by 30%, ATK increased by 15%.",
        "assasin"
    ],
    [
        "Самурай",
        "Samurai",
        "40",
        "40",
        "22",
        "22",
        "3",
        "2",
        "Атаки юнитов не подвергаются штрафу за ближний бой. АТК увеличивается на 20% во время ближний атак, крит увеличивается на 20% во время дальних атак",
        "Unit's damage is not reduced in melee battles. ATK increases by 20% during melee attacks, vrit increases by 20% during range attacks.",
        "assasin"
    ],
    [
        "Шиноби",
        "Shinobi",
        "36",
        "43",
        "20",
        "20",
        "3",
        "2",
        "Крит увеличивается на 30%. Критические удары наносят вражеским юнитам урон (20% от макс. ОЗ вражеским юнитам)",
        "Crit increased by 30%, critical hits deals extra damage after battle (20% of enemy's max unit HP).",
        "assasin"
    ],
    [
        "Танцующая в тумане",
        "Mist Dancer",
        "40",
        "37",
        "22",
        "26",
        "3",
        "2",
        "Крит увеличивается на 45%. Критические удары накладывают на врагов 1 случайный сильный дебафф",
        "Crit increased by 45%. Critical hits inflict 1 random strong debuff.",
        "assasin"
    ],
    [
        "Гоблин-рыцарь",
        "Earth Elf Knight",
        "36",
        "43",
        "20",
        "20",
        "5",
        "2",
        "Крит увеличивается на 30%. В случае нанесения критического удара накладывает на врага 1 мощный дебафф и крадет 1 бафф",
        "Crit increases by 30%. Upon landing a critical hit, afflicts the enemy with 1 random strong debuff and sleals 1 buff.",
        "assasin"
    ],
    [
        "Безликий",
        "The Faceless",
        "36",
        "43",
        "20",
        "22",
        "3",
        "2",
        "АТК и крит. шанс солдат увеличиваются на 15%. Перед вступлением в бой увеличивает шанс вражеских юнитов на получение крит. удара на 15%",
        "Soldier's ATK and critical chance increased by 15%. Before entering battle, increases the enemy's unit chance to be critically hit by 15%.",
        "assasin"
    ],
    [
        "Ночной лесной эльф",
        "Forest Night Elf",
        "38",
        "43",
        "20",
        "20",
        "3",
        "2",
        "АТК и крит. шанс солдат увеличиваются на 15%. При активной атаке шанс крита и крит. урон солдат увеличиваются на 15%. Если этот юнит находится в лесу, он атакует первым",
        "Soldier's ATK and critical chance increased by 15%. When actively attacking, critical chance and critical hit of soldiers increase by 15%. If this unit is situated in forest, it attacks first.",
        "assasin"
    ],
    [
        "Убийца из Ковчега",
        "Ark Assassin",
        "38",
        "43",
        "23",
        "18",
        "3",
        "2",
        "АТК увеличивается на 15%, а крит увеличивается на 30%. Наносит на 20% больше крит. урона противнику, у которого менее 100% ОЗ",
        "ATK increases by 15%, crit increases by 30%. Deals 20% increased crit damage when engaging in battle with the enemy that's at less then 100% HP.",
        "assasin"
    ],
    [
        "Чернокнижник",
        "Warlock",
        "22",
        "24",
        "12",
        "15",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном.",
        "Basic Mage. Normal attacks deals magic damage.",
        "mage"
    ],
    [
        "Чудотворец",
        "Traumaturge",
        "26",
        "29",
        "14",
        "18",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. АТК увеличивается на 20%",
        "Normal attacks deals magic damage. ATK increases by 20%.",
        "mage"
    ],
    [
        "Ведьма",
        "Witch",
        "26",
        "31",
        "13",
        "22",
        "5",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Когда у солдат 100% ОЗ, АТК увеличивается на 20%",
        "Normal attacks deals magic damage. When soldier's HP is 100%, ATK increases by 20%.",
        "mage"
    ],
    [
        "Колдун",
        "Wizard",
        "34",
        "37",
        "19",
        "23",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. При инициировании боя АТК и МЗАЩ повышаются на 30%",
        "Normal attacks deals magic damage. When initiating battle, ATK and MDEF increase by 30%.",
        "mage"
    ],
    [
        "Колдунья",
        "Sorceress",
        "34",
        "40",
        "17",
        "28",
        "5",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Когда у солдат 100% ОЗ, АТК и МЗАЩ увеличиваются на 45%",
        "Normal attacks deals magic damage. When soldier's HP is at 100%, ATK and MDEF increase by 45%.",
        "mage"
    ],
    [
        "Кристальный чародей",
        "Crystal Warlock",
        "43",
        "37",
        "22",
        "19",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. После окончания действия восстанавливает 30% ОЗ солдат. Когда втянут в бой в ходе физической атаки, юнит отражает 30% полученного урона",
        "Normal attacks deals magic damage. After taking action restores 30% of soldier's HP. When forced into battle by a physical attack, reflects 30% if damage received.",
        "mage"
    ],
    [
        "Темный алхимик",
        "Dark Alchemist",
        "40",
        "40",
        "20",
        "19",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. После окончания действия восстанавливает 30% ОЗ солдат. Когда у солдат более 80% ОЗ, их дальность увеличивается на 1, а АТК на 30%",
        " Normal attacks deals magic damage. After taking action restores 30% of soldier's HP. When soldier's HP is above 80%, range increases by 1, ATK increases by 30%.",
        "mage"
    ],
    [
        "Фея-ворожея",
        "Fairy Spirit Prophet",
        "37",
        "41",
        "17",
        "22",
        "5",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Когда атакуете и вступаете в бой, АТК солдат увеличивается на 30%, наносимый урон увеличивается на 15%, а отражаемый получаемый урон уменьшается на 50%",
        " Normal attacks deals magic damage. When attacking and entering battle, soldier's ATK increases by 30%, damage dealt increases by 15%, reflect damage taken decreases by 50%.",
        "mage"
    ],
    [
        "Маг - ядовитая летучая мышь",
        "Poison Bat Mage",
        "37",
        "40",
        "18",
        "23",
        "5",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. В начале боя АТК солдат увеличивается на 30%. Перед боем есть 100% шанс применить 1 случайных дебафф к противнику",
        " Normal attacks deals magic damage. When initiating battle, soldier's ATK increases by 30%. There is a 100% chance to apply 1 random debuff to enemy before battle.",
        "mage"
    ],
    [
        "Клирик",
        "Holy",
        "22",
        "20",
        "12",
        "18",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном",
        "Basic Holy.  Normal attacks deals magic damage.",
        "holy"
    ],
    [
        "Инквизитор",
        "Inquisitor",
        "26",
        "24",
        "14",
        "22",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Эффекты исцеления героя увеличиваются на 10%",
        "Normal attacks deals magic damage. Hero's healing effects are increased by 10%.",
        "holy"
    ],
    [
        "Монах",
        "Monk",
        "31",
        "29",
        "17",
        "16",
        "3",
        "1",
        "В битвах против [Демонов] АТК увеличивается на доп. 30%",
        "When battling against Demons, ATK increases by an extra 30%.",
        "holy"
    ],
    [
        "Епископ",
        "Bishop",
        "34",
        "31",
        "19",
        "28",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Эффекты исцеления героя увеличиваются на 15%. Когда у солдат больше 80% ОЗ, ЗАЩ повышается на 30%",
        "Normal attacks deals magic damage. Hero's healing effects are increased by 15%. When soldier's HP is above 80%, DEF increases by 30%.",
        "holy"
    ],
    [
        "Святой рыцарь",
        "Holy Knight",
        "34",
        "34",
        "19",
        "26",
        "5",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Эффекты исцеления героя увеличиваются на +15%. Когда у солдат больше 80% ОЗ, ЗАЩ повышается на 30%",
        "Normal attacks deals magic damage. Hero's healing effects are increased by 15%. When soldier's HP is above 80%, DEF increases by 30%.",
        "holy"
    ],
    [
        "Жрица",
        "Shrine Maiden",
        "36",
        "31",
        "17",
        "28",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Когда у солдат 100% ОЗ, получаемый героем физический урон снижается на 75%",
        "Normal attacks deals magic damage. When soldier's HP is at 100%, hero's physical damage taken is decreased by 75%.",
        "holy"
    ],
    [
        "Экзорцист",
        "Exorcist",
        "40",
        "37",
        "22",
        "20",
        "3",
        "1",
        "В битвах против [Демонов] АТК увеличивается на доп. 30%. Когда атакуете любые юниты, кроме [Демонов], ЗАЩ увеличивается на 30%",
        "When battling against Demons, ATK increases by an extra 30%. When battling against unit other than Demons, DEF increases by 30%.",
        "holy"
    ],
    [
        "Фанатик",
        "Zealot",
        "36",
        "40",
        "20",
        "20",
        "3",
        "1",
        "Когда у солдат более 80% ОЗ, за каждый активный бафф АТК, ЗАЩ и МЗАЩ солдат увеличиваются на 15% (до 45%)",
        "When soldier's HP is above 80%, for every active buff ATK, DEF and MDEF increase by 15% (up to 45%).",
        "holy"
    ],
    [
        "Лесной священник",
        "Forest Priest",
        "40",
        "31",
        "20",
        "23",
        "3",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Эффекты исцеления героя увеличиваются на 15%. Когда герой использует навыки на союзных юнитах, он с 100% шансом снимает 1 дебафф",
        "Normal attacks deals magic damage. Hero's healing effects are increased by 15%. When hero uses skills on friendly units, has a 100% chance to dispel 1 debuff.",
        "holy"
    ],
    [
        "Избавитель",
        "Redeemer",
        "48",
        "34",
        "22",
        "22",
        "3",
        "1",
        "Когда втянуты в бой, получаемый урон снижается на 20%. Когда у юнита нет дебаффов, он не погибает при получении смертельного урона, а восстанавливает 20% ОЗ. После активации макс. ОЗ юнита уменьшается на 20%. Может активироваться только один раз за бой.",
        "When forced into battle, damage taken decreases by 20%. When the unit has no debuffs, it does not die upon taking deadly damage, instead it recovers 20% of HP. After triggering, the unit max HP drops by 20%. (can trigger only once in battle). ",
        "holy"
    ],
    [
        "Боевой монах",
        "Fighting Monk",
        "40",
        "40",
        "19",
        "23",
        "3",
        "2",
        "Атаки юнитов не подвергаются штрафу за ближний бой, когда юниты втянуты в бой. Эффекты исцеления героя увеличиваются на 15%, ЗАЩ солдат увеличивается на 25%. АТК солдат увеличивается на 30%, если класс героя - Святой.",
        "Not affected by melee damage penalty when attacked. Hero's healing effects are increased by 15%, soldier's DEF increases by 25%. Soldier's ATK increases by 30%, when hero's class type is Holy.",
        "holy"
    ],
    [
        "Маг Святой Стражи",
        "Holy Guard Mage",
        "48",
        "37",
        "24",
        "24",
        "3",
        "1",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Когда втянуты в бой, ЗАЩ и МЗАЩ увеличиваются на 30%. Если тип класса героя [Святой], АТК увеличивается на 30%",
        "Normal attacks deals magic damage. When attacked, DEF and MDEF increases by 30%. ATK increases by 30%, when the hero's class type is Holy",
        "holy"
    ],
    [
        "Солдат - скелет",
        "Skeleton Soldier",
        "28",
        "26",
        "14",
        "12",
        "3",
        "1",
        "Базовый юнит",
        "Basic Demon",
        "demon"
    ],
    [
        "Воин-скелет",
        "Skeleton Warrior",
        "34",
        "31",
        "17",
        "14",
        "3",
        "1",
        "Воскрешение: Если при инициировании боя у солдат 0% ОЗ, они восстанавливают 35% ОЗ",
        "Resurrection: after initiating battle. If soldier's HP is 0%, restores 35% HP after battle.",
        "demon"
    ],
    [
        "Скелет-лучник",
        "Skeleton Archer",
        "26",
        "31",
        "16",
        "14",
        "3",
        "2",
        "Воскрешение: Если при инициировании боя у солдат 0% ОЗ, они восстанавливают 35% ОЗ",
        "Resurrection: after initiating battle. If soldier's HP is 0%, restores 35% HP after battle.",
        "demon"
    ],
    [
        "Рыцарь-скелет",
        "Skeleton Knight",
        "43",
        "40",
        "22",
        "19",
        "3",
        "1",
        "Воскрешение: Если при инициировании боя у солдат 0% ОЗ, они восстанавливают 45% ОЗ. Когда атакованы юнитами, не являющимися [Святыми] или [Демонами] ЗАЩ увеличивается на 30% ",
        "Resurrection: after initiating battle. If soldier's HP is 0%, restores 45% HP after battle. When attacked not by Holy and Demons, DEF increases by 30%.",
        "demon"
    ],
    [
        "Рыцарь-нежить",
        "Undead Knight",
        "40",
        "40",
        "22",
        "20",
        "5",
        "1",
        "Воскрешение: Если при инициировании боя у солдат 0% ОЗ, они восстанавливают 45% ОЗ. Когда атакуете любые войска не являющиеся [Святыми] или [Демонами], АТК увеличивается на 30%",
        "Resurrection: after initiating battle. If soldier's HP is 0%, restores 45% HP after battle. When attacked not by Holy and Demons, ATR increases by 30%.",
        "demon"
    ],
    [
        "Лучник адского пламени",
        "Hellfire Archer",
        "34",
        "40",
        "20",
        "19",
        "3",
        "2",
        "Воскрешение: Если при инициировании боя у солдат 0% ОЗ, они восстанавливают 45% ОЗ. После боя наносит доп. Урон (15% от макс. ОЗ врага) ",
        "Resurrection: after initiating battle. If soldier's HP is 0%, restores 45% HP after battle. Deals fixed damage to enemy after battle (15% of max HP).",
        "demon"
    ],
    [
        "Паучий эльф-демон",
        "Spider Demon Elf",
        "43",
        "37",
        "22",
        "22",
        "5",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. Перед атакой с 75% шансом уменьшает мобильность врага на 2, а его МЗАЩ на 20% на 1 ход",
        "Normal attacks deals magic damage. Before attacking, has 75% chance to reduce enemy's mobility by 2 and MDEF by 20%. Lasts 1 turn.",
        "demon"
    ],
    [
        "Сталегривый оборотень",
        "Steelmane Werewolf",
        "48",
        "40",
        "23",
        "19",
        "5",
        "1",
        "После боя и совершения действия восстанавливает 20% ОЗ солдат. Когда у солдат более 70% ОЗ, АТК увеличивается на 40%,когда они совершают активные атаки; а когда они атакованы, ЗАЩ увеличивается на 40%",
        "After battle and after taking action, restores 20% of soldier's HP. When soldier's HP is above 70%, ATK increases by 40% when attacking, and DEF increases by 40% when attacked.",
        "demon"
    ],
    [
        "Зомби-гигант",
        "Giant Zombie",
        "40",
        "42",
        "24",
        "18",
        "3",
        "1",
        "ОЗ, АТК и шанс крита увеличиваются на 35%. Когда ОЗ солдат ниже 100% перед вступлением в бой, восстанавливает 35% ОЗ после боя",
        "HP. ATK and Crit chance increase by 35%. When soldier's HP is lower than 100%, recovers 35% of HP after battle.",
        "demon"
    ],
    [
        "Призрак тумана",
        "Mist Spirit",
        "40",
        "37",
        "22",
        "24",
        "5",
        "2",
        "Физический урон, наносимый обычными атаками, считается магическим уроном. При вступлении в бой АТК увеличивается на 30%. Когда втянуты в бой получают на 15% меньше фзи урона. После боя, если все солдаты были убиты, восстанавливает 45% ОЗ ",
        "Normal attacks deals magic damage. When attacking, ATK increases by 40%. When attacked, physical damage taken decreases by 15%. After the battle, is soldiers are dead, restores 45% HP.",
        "demon"
    ]
]
function soldView (soldClas) {
	var sd = document.getElementById('sold_data');
	sd.innerHTML = '';
	//sd.innerHTML = soldDat[111][8];
	var i;
	for (i=1;i<soldDat.length;i++){
		if (soldDat[i][10]==soldClas){
			sd.innerHTML += '<div style="display:block;width:95%;height:160px;"><div style="display:block;width:130px;float:left;"><img src="soldIcons/' + soldClas + '/' + soldDat[i][0] + 
			'.png" height="150px" /></div><div style="display:block;width:700px;float:left;"><b style="font-size: 23px;margin-right: 50px;vertical-align:super;">' + soldDat[i][0]+ 
			'</b> <img src="Move_Walk.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][6] + 
			'</span> <img src="Icon_Range.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin: 0 10px;">' + soldDat[i][7] + 
			'</span> <img src="icon.png" height="25px" /></div><br><br><div><img src="sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:30px;">ОЗ: ' + soldDat[i][2]  + 
			'</span><img src="sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:30px;">ATK: ' + soldDat[i][3]  + 
			'</span><img src="sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:30px;">ЗАЩ: ' + soldDat[i][4]  + 
			'</span><img src="sold_stats.png" height="23px" /><span style="font-size:20px;vertical-align:super;margin-right:30px;">МЗАЩ: ' + soldDat[i][5]  + 
			'</span></div><br><div style="white-space: normal;"><span style="font-size:18px;">' + soldDat[i][8]  + 
			'</div></div>';
		}
	}
}